---------------------------------------------------------
           PHAML   Version 1.8.0

Output from the master process
  PDE id is     0
  Number of slave processors is     4

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                 1000
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    PHASES
  print_grid_who     MASTER
  print_linsys_when  NEVER
  print_error_when   PHASES
  print_error_who    MASTER
  print_error_what   ENERGY_LINF_ERR
  print_errest_what  ENERGY_LINF_ERREST
  print_time_when    NEVER
  print_eval_when    PHASES
  print_eval_who     MASTER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           250
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ_SMOOTH
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    true
  solver             PETSC_CG_SOLVER
  preconditioner     PETSC_SOR_PRECONDITION
  petsc_matrix_free  false
  petsc_rtol         default
  petsc_atol         default
  petsc_dtol         default
  petsc_maxits       default
  petsc_sor_omega    default
  petsc_sor_its      default
  petsc_sor_lits     default
  eigensolver        BLOPEX_SOLVER
  num_eval                    3
  lambda0            -infinity
  scale_evec         SCALE_LINF
  blopex_maxit              100
  blopex_atol         1.0000000000E-06
  blopex_rtol         1.0000000000E-06
---------------------------------------------------------

Total Grid:
   number of vertices      =         145
   number of leaf elements =         256
   number of levels        =           1
   degrees of freedom      =         145
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       8.5657831418E-01
   energy error estimate      3.3353374079E-01
      effectivity             3.8937915573E-01
   Linf norm of error         1.3374884879E-01
   Linf error estimate        9.8650670117E-02
      effectivity             7.3758145219E-01
 Eigenvector           2
   energy error estimate      6.0198893023E-01
   Linf error estimate        1.1114181693E-01
 Eigenvector           3
   energy error estimate      7.2589535734E-01
   Linf error estimate        1.7696533626E-01

Total Grid:
   number of vertices      =         313
   number of leaf elements =         592
   number of levels        =           6
   degrees of freedom      =         313
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       3.7459628437E-01
      reduced by              4.3731703005E-01
   energy error estimate      1.0116796797E-01
      reduced by              3.0332154020E-01
      effectivity             2.7007200068E-01
   Linf norm of error         3.0168626015E-02
      reduced by              2.2556176213E-01
   Linf error estimate        7.0249076943E-03
      reduced by              7.1209933861E-02
      effectivity             2.3285474422E-01
 Eigenvector           2
   energy error estimate      1.6386169076E-01
      reduced by              2.7220050490E-01
   Linf error estimate        9.0466287830E-03
      reduced by              8.1397164747E-02
 Eigenvector           3
   energy error estimate      2.2823070777E-01
      reduced by              3.1441268423E-01
   Linf error estimate        1.1978777053E-02
      reduced by              6.7689962943E-02

Eigenvalues and error estimates:
     9.8607300457E+00  7.3373469641E-02
     1.7176276791E+01  1.1386428066E-01
     2.4526354310E+01  1.4758213554E-01

Total Grid:
   number of vertices      =         620
   number of leaf elements =        1206
   number of levels        =           8
   degrees of freedom      =         620
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       2.0867536961E-01
      reduced by              2.7853368856E-01
   energy error estimate      5.7558059495E-02
      reduced by              2.8446780464E-01
      effectivity             2.7582584184E-01
   Linf norm of error         1.0394255819E-02
      reduced by              3.4453858831E-01
   Linf error estimate        3.1365281469E-03
      reduced by              4.4648674166E-01
      effectivity             3.0175591227E-01
 Eigenvector           2
   energy error estimate      9.4674998644E-02
      reduced by              2.8888692106E-01
   Linf error estimate        3.7311932178E-03
      reduced by              4.1244018157E-01
 Eigenvector           3
   energy error estimate      1.4363651690E-01
      reduced by              3.1467395055E-01
   Linf error estimate        9.0049889477E-03
      reduced by              7.5174526644E-01

Eigenvalues and error estimates:
     9.7231725071E+00  2.7219075838E-02
     1.6876481272E+01  4.0160147016E-02
     2.2152371272E+01  7.4355206858E-02

Total Grid:
   number of vertices      =        1263
   number of leaf elements =        2492
   number of levels        =          10
   degrees of freedom      =        1263
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       1.4012611501E-01
      reduced by              6.7150289593E-01
   energy error estimate      3.7980764578E-02
      reduced by              6.5986874664E-01
      effectivity             2.7104701059E-01
   Linf norm of error         5.1094713090E-03
      reduced by              4.9156682288E-01
   Linf error estimate        9.9104236478E-04
      reduced by              3.1596794876E-01
      effectivity             1.9396182205E-01
 Eigenvector           2
   energy error estimate      6.3296447173E-02
      reduced by              6.6856559894E-01
   Linf error estimate        1.4282681191E-03
      reduced by              3.8279125087E-01
 Eigenvector           3
   energy error estimate      7.5831355364E-02
      reduced by              5.2793925249E-01
   Linf error estimate        1.7383156250E-03
      reduced by              1.9303917363E-01

Eigenvalues and error estimates:
     9.6882548386E+00  1.0588238284E-02
     1.6796913469E+01  2.0695727018E-02
     2.1993126240E+01  2.0481939385E-02

Total Grid:
   number of vertices      =        1263
   number of leaf elements =        2492
   number of levels        =          10
   degrees of freedom      =        1263
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       1.4012611501E-01
   energy error estimate      3.7980764578E-02
      effectivity             2.7104701059E-01
   Linf norm of error         5.1094713090E-03
   Linf error estimate        9.9104236478E-04
      effectivity             1.9396182205E-01
 Eigenvector           2
   energy error estimate      6.3296447173E-02
   Linf error estimate        1.4282681191E-03
 Eigenvector           3
   energy error estimate      7.5831355364E-02
   Linf error estimate        1.7383156250E-03

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           3
termination condition:
  maximum vertices achieved
---------------------------------------------------------
