---------------------------------------------------------
           PHAML   Version 1.6.2

Output from the master process
  PDE id is     0
  Number of slave processors is     1

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                 1000
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    PHASES
  print_grid_who     MASTER
  print_linsys_when  NEVER
  print_error_when   PHASES
  print_error_who    MASTER
  print_error_what   NEVER
  print_errest_what  ENERGY_LINF_ERREST
  print_time_when    NEVER
  print_eval_when    PHASES
  print_eval_who     MASTER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           250
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ_SMOOTH
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    true
  solver             PETSC_GMRES_SOLVER
  preconditioner     PETSC_SOR_PRECONDITION
  petsc_matrix_free  false
  petsc_rtol         default
  petsc_atol         default
  petsc_dtol         default
  petsc_maxits       default
  petsc_gmres_max_steps  default
  petsc_sor_omega    default
  petsc_sor_its      default
  petsc_sor_lits     default
  eigensolver        BLOPEX_SOLVER
  num_eval                    3
  lambda0             3.0000000000E+01
  scale_evec         SCALE_LINF
  lambda0_side       EIGEN_BOTH
  transformation     SHIFT_SQUARE
  blopex_maxit              100
  blopex_atol         1.0000000000E-06
  blopex_rtol         1.0000000000E-06
---------------------------------------------------------

Total Grid:
   number of vertices      =         145
   number of leaf elements =         256
   number of levels        =           1
   degrees of freedom      =         145
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy error estimate      1.0669224003E+00
      effectivity             1.0669224003E+00
   Linf error estimate        2.1436995759E-01
      effectivity             2.1436995759E-01
 Eigenvector           2
   energy error estimate      1.4442113748E+01
   Linf error estimate        2.8711780822E+00
 Eigenvector           3
   energy error estimate      9.1774405599E+00
   Linf error estimate        1.3652533974E+00

Total Grid:
   number of vertices      =         322
   number of leaf elements =         604
   number of levels        =           7
   degrees of freedom      =         322
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy error estimate      4.2984095922E-01
      reduced by              4.0287930883E-01
      effectivity             4.2984095922E-01
   Linf error estimate        1.2778058198E-01
      reduced by              5.9607504439E-01
      effectivity             1.2778058198E-01
 Eigenvector           2
   energy error estimate      4.5092046089E-01
      reduced by              3.1222608322E-02
   Linf error estimate        1.2622886728E-01
      reduced by              4.3964137251E-02
 Eigenvector           3
   energy error estimate      5.5709432756E-01
      reduced by              6.0702580847E-02
   Linf error estimate        1.2562735879E-01
      reduced by              9.2017613013E-02

Eigenvalues and error estimates:
     2.5625767205E+01  5.9315141284E-01
     3.1761180413E+01  6.3351010363E-01
     3.4520600626E+01  7.1151230879E-01

Total Grid:
   number of vertices      =         514
   number of leaf elements =         994
   number of levels        =           7
   degrees of freedom      =         514
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy error estimate      1.6946263962E-01
      reduced by              3.9424497826E-01
      effectivity             1.6946263962E-01
   Linf error estimate        7.2223739649E-03
      reduced by              5.6521686259E-02
      effectivity             7.2223739649E-03
 Eigenvector           2
   energy error estimate      2.2913689502E-01
      reduced by              5.0815368761E-01
   Linf error estimate        9.9881418199E-03
      reduced by              7.9127239555E-02
 Eigenvector           3
   energy error estimate      2.3709200306E-01
      reduced by              4.2558681956E-01
   Linf error estimate        1.1196337402E-02
      reduced by              8.9123400433E-02

Eigenvalues and error estimates:
     2.4199527128E+01  8.1703064032E-02
     2.9504358348E+01  1.1049006962E-01
     3.1509325049E+01  1.2513487565E-01

Total Grid:
   number of vertices      =        1185
   number of leaf elements =        2336
   number of levels        =           9
   degrees of freedom      =        1185
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy error estimate      1.2645539273E-01
      reduced by              7.4621399152E-01
      effectivity             1.2645539273E-01
   Linf error estimate        2.9083816723E-03
      reduced by              4.0269054004E-01
      effectivity             2.9083816723E-03
 Eigenvector           2
   energy error estimate      1.2830359323E-01
      reduced by              5.5994296866E-01
   Linf error estimate        3.4641964782E-03
      reduced by              3.4683092618E-01
 Eigenvector           3
   energy error estimate      1.5687038599E-01
      reduced by              6.6164351376E-01
   Linf error estimate        8.4272024749E-03
      reduced by              7.5267493039E-01

Eigenvalues and error estimates:
     2.9172743009E+01  3.8870852260E-02
     3.1076777944E+01  3.9990904762E-02
     3.3917663493E+01  6.2795317484E-02

Total Grid:
   number of vertices      =        1185
   number of leaf elements =        2336
   number of levels        =           9
   degrees of freedom      =        1185
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy error estimate      1.2645539273E-01
      effectivity             1.2645539273E-01
   Linf error estimate        2.9083816723E-03
      effectivity             2.9083816723E-03
 Eigenvector           2
   energy error estimate      1.2830359323E-01
   Linf error estimate        3.4641964782E-03
 Eigenvector           3
   energy error estimate      1.5687038599E-01
   Linf error estimate        8.4272024749E-03

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           3
termination condition:
  maximum vertices achieved
---------------------------------------------------------
