---------------------------------------------------------
           PHAML   Version 1.8.0

Output from the master process
  PDE id is     0
  Number of slave processors is     1

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                 1000
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    PHASES
  print_grid_who     MASTER
  print_linsys_when  NEVER
  print_error_when   PHASES
  print_error_who    MASTER
  print_error_what   NEVER
  print_errest_what  ENERGY_LINF_ERREST
  print_time_when    NEVER
  print_eval_when    PHASES
  print_eval_who     MASTER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           250
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ_SMOOTH
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    true
  solver             PETSC_GMRES_SOLVER
  preconditioner     PETSC_SOR_PRECONDITION
  petsc_matrix_free  false
  petsc_rtol         default
  petsc_atol         default
  petsc_dtol         default
  petsc_maxits       default
  petsc_gmres_max_steps  default
  petsc_sor_omega    default
  petsc_sor_its      default
  petsc_sor_lits     default
  eigensolver        BLOPEX_SOLVER
  num_eval                    3
  lambda0             3.0000000000E+01
  scale_evec         SCALE_LINF
  lambda0_side       EIGEN_RIGHT
  transformation     SHIFT_INVERT
  blopex_maxit              100
  blopex_atol         1.0000000000E-06
  blopex_rtol         1.0000000000E-06
---------------------------------------------------------

Total Grid:
   number of vertices      =         145
   number of leaf elements =         256
   number of levels        =           1
   degrees of freedom      =         145
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy error estimate      1.0669295948E+00
      effectivity             1.0669295948E+00
   Linf error estimate        2.1437005692E-01
      effectivity             2.1437005692E-01
 Eigenvector           2
   energy error estimate      7.1116940698E+00
   Linf error estimate        9.4372603668E-01
 Eigenvector           3
   energy error estimate      7.1116115722E+00
   Linf error estimate        9.4372400940E-01

Total Grid:
   number of vertices      =         296
   number of leaf elements =         551
   number of levels        =           6
   degrees of freedom      =         296
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy error estimate      4.5248949606E-01
      reduced by              4.2410436289E-01
      effectivity             4.5248949606E-01
   Linf error estimate        7.1095844851E-02
      reduced by              3.3165007219E-01
      effectivity             7.1095844851E-02
 Eigenvector           2
   energy error estimate      4.5359602742E-01
      reduced by              6.3781712623E-02
   Linf error estimate        6.3365921584E-02
      reduced by              6.7144403271E-02
 Eigenvector           3
   energy error estimate      1.8703677650E+00
      reduced by              2.6300195758E-01
   Linf error estimate        3.6423855507E-01
      reduced by              3.8595876702E-01

Eigenvalues and error estimates:
     3.0833058997E+01  4.7485757305E-01
     3.3902339187E+01  4.4643032324E-01
     3.8510615143E+01  3.1512115713E+00

Total Grid:
   number of vertices      =         607
   number of leaf elements =        1155
   number of levels        =           7
   degrees of freedom      =         607
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy error estimate      3.1030258364E-01
      reduced by              6.8576748487E-01
      effectivity             3.1030258364E-01
   Linf error estimate        2.1674374312E-02
      reduced by              3.0486133694E-01
      effectivity             2.1674374312E-02
 Eigenvector           2
   energy error estimate      3.6813760464E-01
      reduced by              8.1159794704E-01
   Linf error estimate        3.0668788840E-02
      reduced by              4.8399499405E-01
 Eigenvector           3
   energy error estimate      4.1380688228E-01
      reduced by              2.2124359178E-01
   Linf error estimate        3.6710178741E-02
      reduced by              1.0078608711E-01

Eigenvalues and error estimates:
     3.2000321636E+01  2.2533708026E-01
     3.5580776803E+01  2.4697484692E-01
     3.7557094998E+01  3.1878203466E-01

Total Grid:
   number of vertices      =        1282
   number of leaf elements =        2530
   number of levels        =          10
   degrees of freedom      =        1282
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy error estimate      1.3296799629E-01
      reduced by              4.2851076111E-01
      effectivity             1.3296799629E-01
   Linf error estimate        3.3287003770E-03
      reduced by              1.5357769175E-01
      effectivity             3.3287003770E-03
 Eigenvector           2
   energy error estimate      1.4104579756E-01
      reduced by              3.8313336040E-01
   Linf error estimate        3.6391001553E-03
      reduced by              1.1865809811E-01
 Eigenvector           3
   energy error estimate      2.7702168537E-01
      reduced by              6.6944678116E-01
   Linf error estimate        6.2887715118E-03
      reduced by              1.7130865955E-01

Eigenvalues and error estimates:
     3.1079967490E+01  4.1573364425E-02
     3.4377047055E+01  3.8087108999E-02
     3.6727197932E+01  8.4780682782E-02

Total Grid:
   number of vertices      =        1282
   number of leaf elements =        2530
   number of levels        =          10
   degrees of freedom      =        1282
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy error estimate      1.3296799629E-01
      effectivity             1.3296799629E-01
   Linf error estimate        3.3287003770E-03
      effectivity             3.3287003770E-03
 Eigenvector           2
   energy error estimate      1.4104579756E-01
   Linf error estimate        3.6391001553E-03
 Eigenvector           3
   energy error estimate      2.7702168537E-01
   Linf error estimate        6.2887715118E-03

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           3
termination condition:
  maximum vertices achieved
---------------------------------------------------------
