---------------------------------------------------------
           PHAML   Version 1.8.0

Output from the master process
  PDE id is     0
  Number of slave processors is     1

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                 1000
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    PHASES
  print_grid_who     MASTER
  print_linsys_when  NEVER
  print_error_when   PHASES
  print_error_who    MASTER
  print_error_what   NEVER
  print_errest_what  ENERGY_LINF_ERREST
  print_time_when    NEVER
  print_eval_when    PHASES
  print_eval_who     MASTER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           250
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ_SMOOTH
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    true
  solver             PETSC_GMRES_SOLVER
  preconditioner     PETSC_SOR_PRECONDITION
  petsc_matrix_free  false
  petsc_rtol         default
  petsc_atol         default
  petsc_dtol         default
  petsc_maxits       default
  petsc_gmres_max_steps  default
  petsc_sor_omega    default
  petsc_sor_its      default
  petsc_sor_lits     default
  eigensolver        BLOPEX_SOLVER
  num_eval                    3
  lambda0             3.0000000000E+01
  scale_evec         SCALE_LINF
  lambda0_side       EIGEN_BOTH
  transformation     SHIFT_SQUARE
  blopex_maxit              100
  blopex_atol         1.0000000000E-06
  blopex_rtol         1.0000000000E-06
---------------------------------------------------------

Total Grid:
   number of vertices      =         145
   number of leaf elements =         256
   number of levels        =           1
   degrees of freedom      =         145
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy error estimate      1.0667811111E+00
      effectivity             1.0667811111E+00
   Linf error estimate        2.1436480227E-01
      effectivity             2.1436480227E-01
 Eigenvector           2
   energy error estimate      1.6913076184E+01
   Linf error estimate        2.7080674283E+00
 Eigenvector           3
   energy error estimate      1.4350827072E+01
   Linf error estimate        2.9268474938E+00

Total Grid:
   number of vertices      =         404
   number of leaf elements =         765
   number of levels        =           7
   degrees of freedom      =         404
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy error estimate      3.4216745758E-01
      reduced by              3.2074757795E-01
      effectivity             3.4216745758E-01
   Linf error estimate        4.6760453666E-02
      reduced by              2.1813494180E-01
      effectivity             4.6760453666E-02
 Eigenvector           2
   energy error estimate      2.9817224550E-01
      reduced by              1.7629687365E-02
   Linf error estimate        2.7914619900E-02
      reduced by              1.0307948616E-02
 Eigenvector           3
   energy error estimate      4.7671470973E+00
      reduced by              3.3218622686E-01
   Linf error estimate        5.9347591018E-01
      reduced by              2.0276967333E-01

Eigenvalues and error estimates:
     2.9996925226E+01  3.2916322311E-01
     3.1982332978E+01  2.1456883914E-01
     7.3177084137E+02  6.5023971293E+00

Total Grid:
   number of vertices      =         587
   number of leaf elements =        1138
   number of levels        =           7
   degrees of freedom      =         587
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy error estimate      2.3300095433E-01
      reduced by              6.8095591550E-01
      effectivity             2.3300095433E-01
   Linf error estimate        3.0684497536E-02
      reduced by              6.5620615564E-01
      effectivity             3.0684497536E-02
 Eigenvector           2
   energy error estimate      3.2074638200E-01
      reduced by              1.0757083761E+00
   Linf error estimate        4.6469245356E-02
      reduced by              1.6646920331E+00
 Eigenvector           3
   energy error estimate      2.9487041713E-01
      reduced by              6.1854692357E-02
   Linf error estimate        2.8095212488E-02
      reduced by              4.7340105986E-02

Eigenvalues and error estimates:
     2.4514926704E+01  1.6927111131E-01
     2.9896121837E+01  2.6896045540E-01
     3.1946129273E+01  2.0073424342E-01

Total Grid:
   number of vertices      =        1155
   number of leaf elements =        2276
   number of levels        =           9
   degrees of freedom      =        1155
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy error estimate      1.3031364706E-01
      reduced by              5.5928374815E-01
      effectivity             1.3031364706E-01
   Linf error estimate        3.1767191568E-03
      reduced by              1.0352847242E-01
      effectivity             3.1767191568E-03
 Eigenvector           2
   energy error estimate      1.3659571048E-01
      reduced by              4.2586828144E-01
   Linf error estimate        3.4840973229E-03
      reduced by              7.4976412813E-02
 Eigenvector           3
   energy error estimate      4.3255067320E+00
      reduced by              1.4669178327E+01
   Linf error estimate        3.2911255551E-01
      reduced by              1.1714186381E+01

Eigenvalues and error estimates:
     2.9191949903E+01  4.0099387368E-02
     3.1108946412E+01  4.7153616804E-02
     1.0986231048E+03  4.7825684916E+00

Total Grid:
   number of vertices      =        1155
   number of leaf elements =        2276
   number of levels        =           9
   degrees of freedom      =        1155
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy error estimate      1.3031364706E-01
      effectivity             1.3031364706E-01
   Linf error estimate        3.1767191568E-03
      effectivity             3.1767191568E-03
 Eigenvector           2
   energy error estimate      1.3659571048E-01
   Linf error estimate        3.4840973229E-03
 Eigenvector           3
   energy error estimate      4.3255067320E+00
   Linf error estimate        3.2911255551E-01

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           3
termination condition:
  maximum vertices achieved
---------------------------------------------------------
