---------------------------------------------------------
           PHAML   Version 1.6.2

Output from the master process
  PDE id is     0
  Number of slave processors is     4

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                  350
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    PHASES
  print_grid_who     MASTER
  print_linsys_when  NEVER
  print_error_when   PHASES
  print_error_who    MASTER
  print_error_what   ENERGY_LINF_ERR
  print_errest_what  ENERGY_LINF_ERREST
  print_time_when    NEVER
  print_eval_when    PHASES
  print_eval_who     MASTER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree                      4
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ_SMOOTH
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    true
  solver             PETSC_CG_SOLVER
  preconditioner     PETSC_SOR_PRECONDITION
  petsc_matrix_free  false
  petsc_rtol         default
  petsc_atol         default
  petsc_dtol         default
  petsc_maxits       default
  petsc_sor_omega    default
  petsc_sor_its      default
  petsc_sor_lits     default
  eigensolver        BLOPEX_SOLVER
  num_eval                    1
  lambda0            -infinity
  scale_evec         SCALE_LINF
  blopex_maxit              100
  blopex_atol         1.0000000000E-06
  blopex_rtol         1.0000000000E-06
---------------------------------------------------------

Total Grid:
   number of vertices      =         145
   number of leaf elements =         256
   number of levels        =           1
   degrees of freedom      =        2113
   min and max degree      =           4          4

Norms of error:
 Eigenvector           1
   energy norm of error       1.9291166704E-02
   energy error estimate      2.0838288530E-02
      effectivity             1.0801984582E+00
   Linf norm of error         6.7057118883E-03
   Linf error estimate        8.5395460100E-03
      effectivity             1.2734734436E+00

Total Grid:
   number of vertices      =         243
   number of leaf elements =         452
   number of levels        =           6
   degrees of freedom      =        3681
   min and max degree      =           4          4

Norms of error:
 Eigenvector           1
   energy norm of error       1.3879139870E-03
      reduced by              3.5972785067E-02
   energy error estimate      1.2073572889E-03
      reduced by              2.8969684511E-02
      effectivity             8.6990786186E-01
   Linf norm of error         1.1736291527E-04
      reduced by              1.7501932267E-02
   Linf error estimate        2.4393942438E-04
      reduced by              2.8565853980E-02
      effectivity             2.0785051548E+00

Eigenvalues and error estimates:
     9.6592625454E+00  2.4267804844E-07

Total Grid:
   number of vertices      =         638
   number of leaf elements =        1242
   number of levels        =          18
   degrees of freedom      =       10001
   min and max degree      =           4          4

Norms of error:
 Eigenvector           1
   energy norm of error       8.4051216076E-04
      reduced by              6.0559383982E-01
   energy error estimate      3.1403801089E-04
      reduced by              2.6010362779E-01
      effectivity             3.7362696883E-01
   Linf norm of error         1.3249462179E-04
      reduced by              1.1289309019E+00
   Linf error estimate        6.3069363353E-05
      reduced by              2.5854518397E-01
      effectivity             4.7601451668E-01

Eigenvalues and error estimates:
     9.6592593053E+00  5.4875637881E-08

Total Grid:
   number of vertices      =         638
   number of leaf elements =        1242
   number of levels        =          18
   degrees of freedom      =       10001
   min and max degree      =           4          4

Norms of error:
 Eigenvector           1
   energy norm of error       8.4051216076E-04
   energy error estimate      3.1403801089E-04
      effectivity             3.7362696883E-01
   Linf norm of error         1.3249462179E-04
   Linf error estimate        6.3069363353E-05
      effectivity             4.7601451668E-01

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           2
termination condition:
  maximum vertices achieved
---------------------------------------------------------
