---------------------------------------------------------
           PHAML   Version 1.8.0

Output from the master process
  PDE id is     0
  Number of slave processors is     4

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                 1000
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    PHASES
  print_grid_who     MASTER
  print_linsys_when  NEVER
  print_error_when   PHASES
  print_error_who    MASTER
  print_error_what   ENERGY_LINF_ERR
  print_errest_what  ENERGY_LINF_ERREST
  print_time_when    NEVER
  print_eval_when    PHASES
  print_eval_who     MASTER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           250
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ_SMOOTH
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    true
  solver             PETSC_CG_SOLVER
  preconditioner     PETSC_SOR_PRECONDITION
  petsc_matrix_free  false
  petsc_rtol         default
  petsc_atol         default
  petsc_dtol         default
  petsc_maxits       default
  petsc_sor_omega    default
  petsc_sor_its      default
  petsc_sor_lits     default
  eigensolver        BLOPEX_SOLVER
  num_eval                    1
  lambda0            -infinity
  scale_evec         SCALE_LINF
  blopex_maxit                1
  blopex_atol         1.0000000000E-01
  blopex_rtol         1.0000000000E-02
---------------------------------------------------------

Total Grid:
   number of vertices      =         145
   number of leaf elements =         256
   number of levels        =           1
   degrees of freedom      =         145
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       2.4804388371E+00
   energy error estimate      1.0482191532E+00
      effectivity             4.2259423513E-01
   Linf norm of error         3.2056754851E-01
   Linf error estimate        1.4165759657E-01
      effectivity             4.4189624692E-01

Total Grid:
   number of vertices      =         290
   number of leaf elements =         530
   number of levels        =           5
   degrees of freedom      =         290
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       7.4059943190E-01
      reduced by              2.9857597003E-01
   energy error estimate      1.8129290493E-01
      reduced by              1.7295324587E-01
      effectivity             2.4479211989E-01
   Linf norm of error         9.2480084989E-02
      reduced by              2.8848860534E-01
   Linf error estimate        1.6011727057E-02
      reduced by              1.1303119243E-01
      effectivity             1.7313702792E-01

Eigenvalues and error estimates:
     1.0297977506E+01  2.2210447177E-01

Total Grid:
   number of vertices      =         595
   number of leaf elements =        1136
   number of levels        =           8
   degrees of freedom      =         595
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       3.4077436472E-01
      reduced by              2.3006658528E-01
   energy error estimate      6.7006463971E-02
      reduced by              1.8480167219E-01
      effectivity             1.9663000187E-01
   Linf norm of error         6.5187614778E-02
      reduced by              7.0488273000E-01
   Linf error estimate        2.3578779198E-03
      reduced by              1.4725943750E-01
      effectivity             3.6170642658E-02

Eigenvalues and error estimates:
     9.7838141503E+00  4.3123448123E-02

Total Grid:
   number of vertices      =        1251
   number of leaf elements =        2446
   number of levels        =          10
   degrees of freedom      =        1251
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       2.3702802555E-01
      reduced by              6.9555709023E-01
   energy error estimate      3.8472095087E-02
      reduced by              5.7415498158E-01
      effectivity             1.6231032173E-01
   Linf norm of error         5.3171161403E-02
      reduced by              8.1566355179E-01
   Linf error estimate        8.0634709894E-04
      reduced by              3.4198000336E-01
      effectivity             1.5165121048E-02

Eigenvalues and error estimates:
     9.7179144251E+00  1.6881650848E-02

Total Grid:
   number of vertices      =        1251
   number of leaf elements =        2446
   number of levels        =          10
   degrees of freedom      =        1251
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       2.3702802555E-01
   energy error estimate      3.8472095087E-02
      effectivity             1.6231032173E-01
   Linf norm of error         5.3171161403E-02
   Linf error estimate        8.0634709894E-04
      effectivity             1.5165121048E-02

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           3
termination condition:
  maximum vertices achieved
---------------------------------------------------------
