---------------------------------------------------------
           PHAML   Version 1.6.2

Output from the master process
  PDE id is     0
  Number of slave processors is     4

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                 1000
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    PHASES
  print_grid_who     MASTER
  print_linsys_when  NEVER
  print_error_when   PHASES
  print_error_who    MASTER
  print_error_what   ENERGY_LINF_ERR
  print_errest_what  ENERGY_LINF_ERREST
  print_time_when    NEVER
  print_eval_when    PHASES
  print_eval_who     MASTER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           250
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ_SMOOTH
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    true
  solver             PETSC_CG_SOLVER
  preconditioner     PETSC_SOR_PRECONDITION
  petsc_matrix_free  false
  petsc_rtol         default
  petsc_atol         default
  petsc_dtol         default
  petsc_maxits       default
  petsc_sor_omega    default
  petsc_sor_its      default
  petsc_sor_lits     default
  eigensolver        BLOPEX_SOLVER
  num_eval                    1
  lambda0            -infinity
  scale_evec         SCALE_LINF
  blopex_maxit                1
  blopex_atol         1.0000000000E-01
  blopex_rtol         1.0000000000E-02
---------------------------------------------------------

Total Grid:
   number of vertices      =         145
   number of leaf elements =         256
   number of levels        =           1
   degrees of freedom      =         145
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       2.4804388371E+00
   energy error estimate      1.0482191532E+00
      effectivity             4.2259423513E-01
   Linf norm of error         3.2056754851E-01
   Linf error estimate        1.4165759657E-01
      effectivity             4.4189624692E-01

Total Grid:
   number of vertices      =         291
   number of leaf elements =         532
   number of levels        =           5
   degrees of freedom      =         291
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       7.3191806588E-01
      reduced by              2.9507603853E-01
   energy error estimate      1.7884324956E-01
      reduced by              1.7061627716E-01
      effectivity             2.4434872959E-01
   Linf norm of error         9.1221951507E-02
      reduced by              2.8456389903E-01
   Linf error estimate        1.5885961475E-02
      reduced by              1.1214337854E-01
      effectivity             1.7414625770E-01

Eigenvalues and error estimates:
     1.0287680619E+01  2.1864282656E-01

Total Grid:
   number of vertices      =         626
   number of leaf elements =        1196
   number of levels        =           8
   degrees of freedom      =         626
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       3.3695137265E-01
      reduced by              2.3018380633E-01
   energy error estimate      6.4196735598E-02
      reduced by              1.7947765922E-01
      effectivity             1.9052225575E-01
   Linf norm of error         6.4018778782E-02
      reduced by              7.0179137504E-01
   Linf error estimate        2.3394838323E-03
      reduced by              1.4726737415E-01
      effectivity             3.6543712279E-02

Eigenvalues and error estimates:
     9.7783348205E+00  4.0059276107E-02

Total Grid:
   number of vertices      =        1239
   number of leaf elements =        2422
   number of levels        =          10
   degrees of freedom      =        1239
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       2.3591691557E-01
      reduced by              7.0015122276E-01
   energy error estimate      3.8939918207E-02
      reduced by              6.0657162462E-01
      effectivity             1.6505776244E-01
   Linf norm of error         5.0658149577E-02
      reduced by              7.9130140469E-01
   Linf error estimate        9.2847276964E-04
      reduced by              3.9687077843E-01
      effectivity             1.8328201433E-02

Eigenvalues and error estimates:
     9.7176732541E+00  1.8762265987E-02

Total Grid:
   number of vertices      =        1239
   number of leaf elements =        2422
   number of levels        =          10
   degrees of freedom      =        1239
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       2.3591691557E-01
   energy error estimate      3.8939918207E-02
      effectivity             1.6505776244E-01
   Linf norm of error         5.0658149577E-02
   Linf error estimate        9.2847276964E-04
      effectivity             1.8328201433E-02

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           3
termination condition:
  maximum vertices achieved
---------------------------------------------------------
