---------------------------------------------------------
           PHAML   Version 1.8.0

Output from the master process
  PDE id is     0
  Number of slave processors is     4

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                 1000
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    PHASES
  print_grid_who     MASTER
  print_linsys_when  NEVER
  print_error_when   PHASES
  print_error_who    MASTER
  print_error_what   ENERGY_LINF_ERR
  print_errest_what  ENERGY_LINF_ERREST
  print_time_when    NEVER
  print_eval_when    PHASES
  print_eval_who     MASTER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           250
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ_SMOOTH
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    true
  solver             PETSC_CG_SOLVER
  preconditioner     PETSC_SOR_PRECONDITION
  petsc_matrix_free  false
  petsc_rtol         default
  petsc_atol         default
  petsc_dtol         default
  petsc_maxits       default
  petsc_sor_omega    default
  petsc_sor_its      default
  petsc_sor_lits     default
  eigensolver        BLOPEX_SOLVER
  num_eval                    1
  lambda0            -infinity
  scale_evec         SCALE_L2
  blopex_maxit              100
  blopex_atol         1.0000000000E-06
  blopex_rtol         1.0000000000E-06
---------------------------------------------------------

Total Grid:
   number of vertices      =         145
   number of leaf elements =         256
   number of levels        =           1
   degrees of freedom      =         145
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       9.2418223443E-01
   energy error estimate      2.8332650670E-01
      effectivity             3.0656995574E-01
   Linf norm of error         2.3597609260E-01
   Linf error estimate        8.3800676562E-02
      effectivity             3.5512358747E-01

Total Grid:
   number of vertices      =         275
   number of leaf elements =         516
   number of levels        =           7
   degrees of freedom      =         275
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       2.1393818839E+00
      reduced by              2.3148918084E+00
   energy error estimate      1.5472754380E-02
      reduced by              5.4611037141E-02
      effectivity             7.2323480425E-03
   Linf norm of error         8.3693330857E-01
      reduced by              3.5466868671E+00
   Linf error estimate        6.9587079160E-04
      reduced by              8.3038803522E-03
      effectivity             8.3145309724E-04

Eigenvalues and error estimates:
     9.8630549324E+00  1.0696621026E-02

Total Grid:
   number of vertices      =         639
   number of leaf elements =        1244
   number of levels        =           9
   degrees of freedom      =         639
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       2.3208237440E+00
      reduced by              5.4240520626E-01
   energy error estimate      4.4973599989E-03
      reduced by              1.4533159024E-01
      effectivity             1.9378291912E-03
   Linf norm of error         9.0868451302E-01
      reduced by              1.0857310896E+00
   Linf error estimate        1.3379852154E-04
      reduced by              1.9227494983E-01
      effectivity             1.4724419711E-04

Eigenvalues and error estimates:
     9.7176761525E+00  1.7977443455E-03

Total Grid:
   number of vertices      =        1209
   number of leaf elements =        2384
   number of levels        =          10
   degrees of freedom      =        1209
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       2.3923141813E+00
      reduced by              1.0308039063E+00
   energy error estimate      2.1156115516E-03
      reduced by              4.7041187544E-01
      effectivity             8.8433683509E-04
   Linf norm of error         9.3668290455E-01
      reduced by              1.0308120047E+00
   Linf error estimate        4.8207347499E-05
      reduced by              3.6029805818E-01
      effectivity             5.1466026833E-05

Eigenvalues and error estimates:
     9.6875164403E+00  5.8334329304E-04

Total Grid:
   number of vertices      =        1209
   number of leaf elements =        2384
   number of levels        =          10
   degrees of freedom      =        1209
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       2.3923141813E+00
   energy error estimate      2.1156115516E-03
      effectivity             8.8433683509E-04
   Linf norm of error         9.3668290455E-01
   Linf error estimate        4.8207347499E-05
      effectivity             5.1466026833E-05

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           3
termination condition:
  maximum vertices achieved
---------------------------------------------------------
