---------------------------------------------------------
           PHAML   Version 1.8.0

Output from the master process
  PDE id is     0
  Number of slave processors is     4

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                 1000
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    PHASES
  print_grid_who     MASTER
  print_linsys_when  NEVER
  print_error_when   PHASES
  print_error_who    MASTER
  print_error_what   ENERGY_LINF_ERR
  print_errest_what  ENERGY_LINF_ERREST
  print_time_when    NEVER
  print_eval_when    PHASES
  print_eval_who     MASTER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           250
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ_SMOOTH
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    true
  solver             PETSC_CG_SOLVER
  preconditioner     PETSC_SOR_PRECONDITION
  petsc_matrix_free  false
  petsc_rtol         default
  petsc_atol         default
  petsc_dtol         default
  petsc_maxits       default
  petsc_sor_omega    default
  petsc_sor_its      default
  petsc_sor_lits     default
  eigensolver        BLOPEX_SOLVER
  num_eval                    1
  lambda0            -infinity
  scale_evec         SCALE_M
  blopex_maxit              100
  blopex_atol         1.0000000000E-06
  blopex_rtol         1.0000000000E-06
---------------------------------------------------------

Total Grid:
   number of vertices      =         145
   number of leaf elements =         256
   number of levels        =           1
   degrees of freedom      =         145
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       1.2216930248E+00
   energy error estimate      4.5104234878E-01
      effectivity             3.6919450272E-01
   Linf norm of error         3.5231410548E-01
   Linf error estimate        1.3340669896E-01
      effectivity             3.7865840987E-01

Total Grid:
   number of vertices      =         275
   number of leaf elements =         516
   number of levels        =           7
   degrees of freedom      =         275
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       7.1974212130E-01
      reduced by              5.8913500091E-01
   energy error estimate      1.1576864275E-01
      reduced by              2.5666912001E-01
      effectivity             1.6084739148E-01
   Linf norm of error         2.2250312047E-01
      reduced by              6.3154757930E-01
   Linf error estimate        5.2065724752E-03
      reduced by              3.9027818812E-02
      effectivity             2.3399997556E-02

Eigenvalues and error estimates:
     9.8630549324E+00  8.0033151676E-02

Total Grid:
   number of vertices      =         639
   number of leaf elements =        1244
   number of levels        =           9
   degrees of freedom      =         639
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       6.0511403355E-01
      reduced by              4.2036864013E-01
   energy error estimate      5.9987101275E-02
      reduced by              2.5908181979E-01
      effectivity             9.9133548306E-02
   Linf norm of error         2.1809591956E-01
      reduced by              9.8019263326E-01
   Linf error estimate        1.7846437608E-03
      reduced by              3.4276748654E-01
      effectivity             8.1828388370E-03

Eigenvalues and error estimates:
     9.7176761525E+00  2.3978839174E-02

Total Grid:
   number of vertices      =        1209
   number of leaf elements =        2384
   number of levels        =          10
   degrees of freedom      =        1209
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       5.7925320447E-01
      reduced by              9.5726288329E-01
   energy error estimate      4.0723902581E-02
      reduced by              6.7887765395E-01
      effectivity             7.0304147248E-02
   Linf norm of error         2.1880560966E-01
      reduced by              1.0032540274E+00
   Linf error estimate        9.2795453010E-04
      reduced by              5.1996625348E-01
      effectivity             4.2409997235E-03

Eigenvalues and error estimates:
     9.6875164403E+00  1.1228911763E-02

Total Grid:
   number of vertices      =        1209
   number of leaf elements =        2384
   number of levels        =          10
   degrees of freedom      =        1209
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       5.7925320447E-01
   energy error estimate      4.0723902581E-02
      effectivity             7.0304147248E-02
   Linf norm of error         2.1880560966E-01
   Linf error estimate        9.2795453010E-04
      effectivity             4.2409997235E-03

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           3
termination condition:
  maximum vertices achieved
---------------------------------------------------------
