---------------------------------------------------------
           PHAML   Version 1.8.0

Output from the master process
  PDE id is     0
  Number of slave processors is     4

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                  350
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    PHASES
  print_grid_who     MASTER
  print_linsys_when  NEVER
  print_error_when   PHASES
  print_error_who    MASTER
  print_error_what   ENERGY_LINF_ERR
  print_errest_what  ENERGY_LINF_ERREST
  print_time_when    NEVER
  print_eval_when    PHASES
  print_eval_who     MASTER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree                      4
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ_SMOOTH
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    true
  solver             PETSC_CG_SOLVER
  preconditioner     PETSC_SOR_PRECONDITION
  petsc_matrix_free  false
  petsc_rtol         default
  petsc_atol         default
  petsc_dtol         default
  petsc_maxits       default
  petsc_sor_omega    default
  petsc_sor_its      default
  petsc_sor_lits     default
  eigensolver        BLOPEX_SOLVER
  num_eval                    1
  lambda0            -infinity
  scale_evec         SCALE_LINF
  blopex_maxit              100
  blopex_atol         1.0000000000E-06
  blopex_rtol         1.0000000000E-06
---------------------------------------------------------

Total Grid:
   number of vertices      =         145
   number of leaf elements =         256
   number of levels        =           1
   degrees of freedom      =        2113
   min and max degree      =           4          4

Norms of error:
 Eigenvector           1
   energy norm of error       1.9291166704E-02
   energy error estimate      2.0838288530E-02
      effectivity             1.0801984582E+00
   Linf norm of error         6.7057118883E-03
   Linf error estimate        8.5395460100E-03
      effectivity             1.2734734436E+00

Total Grid:
   number of vertices      =         197
   number of leaf elements =         360
   number of levels        =           6
   degrees of freedom      =        2945
   min and max degree      =           4          4

Norms of error:
 Eigenvector           1
   energy norm of error       1.5455175509E-03
      reduced by              4.0057648525E-02
   energy error estimate      1.9662534548E-03
      reduced by              4.7178861449E-02
      effectivity             1.2722297806E+00
   Linf norm of error         1.2062645869E-04
      reduced by              1.7988613394E-02
   Linf error estimate        4.8584226219E-04
      reduced by              5.6893219103E-02
      effectivity             4.0276591674E+00

Eigenvalues and error estimates:
     9.6592642276E+00  7.1404610395E-07

Total Grid:
   number of vertices      =         341
   number of leaf elements =         648
   number of levels        =           6
   degrees of freedom      =        5249
   min and max degree      =           4          4

Norms of error:
 Eigenvector           1
   energy norm of error       4.5537015831E-04
      reduced by              2.9463926698E-01
   energy error estimate      2.6979356150E-04
      reduced by              1.3721199617E-01
      effectivity             5.9247088677E-01
   Linf norm of error         6.7610458432E-05
      reduced by              5.6049443186E-01
   Linf error estimate        4.3084086617E-05
      reduced by              8.8679165997E-02
      effectivity             6.3723997168E-01

Eigenvalues and error estimates:
     9.6592586058E+00  4.3347418422E-08

Total Grid:
   number of vertices      =         628
   number of leaf elements =        1222
   number of levels        =           8
   degrees of freedom      =        9841
   min and max degree      =           4          4

Norms of error:
 Eigenvector           1
   energy norm of error       3.9094411209E-05
      reduced by              8.5851939342E-02
   energy error estimate      4.6781484576E-05
      reduced by              1.7339733504E-01
      effectivity             1.1966284471E+00
   Linf norm of error         2.4625705028E-06
      reduced by              3.6422922724E-02
   Linf error estimate        5.7044324186E-06
      reduced by              1.3240230597E-01
      effectivity             2.3164544576E+00

Eigenvalues and error estimates:
     9.6592582674E+00  1.7014467093E-09

Total Grid:
   number of vertices      =         628
   number of leaf elements =        1222
   number of levels        =           8
   degrees of freedom      =        9841
   min and max degree      =           4          4

Norms of error:
 Eigenvector           1
   energy norm of error       3.9094411209E-05
   energy error estimate      4.6781484576E-05
      effectivity             1.1966284471E+00
   Linf norm of error         2.4625705028E-06
   Linf error estimate        5.7044324186E-06
      effectivity             2.3164544576E+00

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           3
termination condition:
  maximum vertices achieved
---------------------------------------------------------
