---------------------------------------------------------
           PHAML   Version 1.8.0

Output from the master process
  PDE id is     0
  Number of slave processors is     1

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                 1000
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    PHASES
  print_grid_who     MASTER
  print_linsys_when  NEVER
  print_error_when   PHASES
  print_error_who    MASTER
  print_error_what   NEVER
  print_errest_what  ENERGY_LINF_ERREST
  print_time_when    NEVER
  print_eval_when    PHASES
  print_eval_who     MASTER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           250
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ_SMOOTH
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    true
  solver             PETSC_GMRES_SOLVER
  preconditioner     PETSC_SOR_PRECONDITION
  petsc_matrix_free  false
  petsc_rtol         default
  petsc_atol         default
  petsc_dtol         default
  petsc_maxits       default
  petsc_gmres_max_steps  default
  petsc_sor_omega    default
  petsc_sor_its      default
  petsc_sor_lits     default
  eigensolver        BLOPEX_SOLVER
  num_eval                    3
  lambda0             3.0000000000E+01
  scale_evec         SCALE_LINF
  lambda0_side       EIGEN_LEFT
  transformation     SHIFT_INVERT
  blopex_maxit              100
  blopex_atol         1.0000000000E-06
  blopex_rtol         1.0000000000E-06
---------------------------------------------------------

Total Grid:
   number of vertices      =         145
   number of leaf elements =         256
   number of levels        =           1
   degrees of freedom      =         145
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy error estimate      3.3353455505E-01
      effectivity             3.3353455505E-01
   Linf error estimate        9.8650565352E-02
      effectivity             9.8650565352E-02
 Eigenvector           2
   energy error estimate      6.0198675160E-01
   Linf error estimate        1.1114170948E-01
 Eigenvector           3
   energy error estimate      7.2589547797E-01
   Linf error estimate        1.7696591520E-01

Total Grid:
   number of vertices      =         313
   number of leaf elements =         592
   number of levels        =           6
   degrees of freedom      =         313
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy error estimate      1.6387735178E-01
      reduced by              4.9133545325E-01
      effectivity             1.6387735178E-01
   Linf error estimate        9.0461382068E-03
      reduced by              9.1698797412E-02
      effectivity             9.0461382068E-03
 Eigenvector           2
   energy error estimate      2.2823029004E-01
      reduced by              3.7912842671E-01
   Linf error estimate        1.1978965089E-02
      reduced by              1.0778100449E-01
 Eigenvector           3
   energy error estimate      5.8241343302E-01
      reduced by              8.0233787191E-01
   Linf error estimate        5.5745171055E-02
      reduced by              3.1500512961E-01

Eigenvalues and error estimates:
     1.7176277050E+01  1.1387462140E-01
     2.4526354313E+01  1.4758184675E-01
     7.9750891420E+01  3.7935042648E-01

Total Grid:
   number of vertices      =         646
   number of leaf elements =        1258
   number of levels        =          12
   degrees of freedom      =         646
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy error estimate      1.5328068460E-01
      reduced by              9.3533781779E-01
      effectivity             1.5328068460E-01
   Linf error estimate        6.9994634485E-03
      reduced by              7.7375154883E-01
      effectivity             6.9994634485E-03
 Eigenvector           2
   energy error estimate      2.0732720591E-01
      reduced by              9.0841231408E-01
   Linf error estimate        9.6382911313E-03
      reduced by              8.0460132073E-01
 Eigenvector           3
   energy error estimate      2.4979498628E+00
      reduced by              4.2889633397E+00
   Linf error estimate        2.1759398089E-01
      reduced by              3.9033691488E+00

Eigenvalues and error estimates:
     2.4107036205E+01  9.0868488947E-02
     2.9433048012E+01  1.2617068933E-01
     2.7180486655E+02  1.7029673845E+00

Total Grid:
   number of vertices      =        1333
   number of leaf elements =        2628
   number of levels        =          13
   degrees of freedom      =        1333
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy error estimate      1.4367883524E-01
      reduced by              9.3735773440E-01
      effectivity             1.4367883524E-01
   Linf error estimate        7.7271824035E-03
      reduced by              1.1039678199E+00
      effectivity             7.7271824035E-03
 Eigenvector           2
   energy error estimate      1.4367883525E-01
      reduced by              6.9300521663E-01
   Linf error estimate        7.7271824042E-03
      reduced by              8.0171705740E-01
 Eigenvector           3
   energy error estimate      1.4367883516E-01
      reduced by              5.7518702558E-02
   Linf error estimate        7.7271823911E-03
      reduced by              3.5511930797E-02

Eigenvalues and error estimates:
     2.9196691069E+01  5.1095076207E-02
     2.9196691069E+01  5.1095076209E-02
     2.9196691069E+01  5.1095076165E-02

Total Grid:
   number of vertices      =        1333
   number of leaf elements =        2628
   number of levels        =          13
   degrees of freedom      =        1333
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy error estimate      1.4367883524E-01
      effectivity             1.4367883524E-01
   Linf error estimate        7.7271824035E-03
      effectivity             7.7271824035E-03
 Eigenvector           2
   energy error estimate      1.4367883525E-01
   Linf error estimate        7.7271824042E-03
 Eigenvector           3
   energy error estimate      1.4367883516E-01
   Linf error estimate        7.7271823911E-03

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           3
termination condition:
  maximum vertices achieved
---------------------------------------------------------
