---------------------------------------------------------
           PHAML   Version 1.8.0

Output from the master process
  PDE id is     0
  Number of slave processors is     4

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                 1000
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    PHASES
  print_grid_who     MASTER
  print_linsys_when  NEVER
  print_error_when   PHASES
  print_error_who    MASTER
  print_error_what   ENERGY_LINF_ERR
  print_errest_what  ENERGY_LINF_ERREST
  print_time_when    NEVER
  print_eval_when    PHASES
  print_eval_who     MASTER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           250
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ_SMOOTH
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    true
  solver             PETSC_CG_SOLVER
  preconditioner     PETSC_SOR_PRECONDITION
  petsc_matrix_free  false
  petsc_rtol         default
  petsc_atol         default
  petsc_dtol         default
  petsc_maxits       default
  petsc_sor_omega    default
  petsc_sor_its      default
  petsc_sor_lits     default
  eigensolver        BLOPEX_SOLVER
  num_eval                    1
  lambda0            -infinity
  scale_evec         SCALE_LINF
  blopex_maxit              100
  blopex_atol         1.0000000000E-06
  blopex_rtol         1.0000000000E-06
---------------------------------------------------------

Total Grid:
   number of vertices      =         145
   number of leaf elements =         256
   number of levels        =           1
   degrees of freedom      =         145
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       8.5657830115E-01
   energy error estimate      3.3353371599E-01
      effectivity             3.8937913269E-01
   Linf norm of error         1.3374892324E-01
   Linf error estimate        9.8650674733E-02
      effectivity             7.3758107611E-01

Total Grid:
   number of vertices      =         275
   number of leaf elements =         516
   number of levels        =           7
   degrees of freedom      =         275
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       3.7678720034E-01
      reduced by              4.3987479001E-01
   energy error estimate      9.4698034558E-02
      reduced by              2.8392342369E-01
      effectivity             2.5133028529E-01
   Linf norm of error         2.7322001405E-02
      reduced by              2.0427829057E-01
   Linf error estimate        4.2589441188E-03
      reduced by              4.3171971508E-02
      effectivity             1.5587965375E-01

Eigenvalues and error estimates:
     9.8630549324E+00  6.5466623631E-02

Total Grid:
   number of vertices      =         639
   number of leaf elements =        1244
   number of levels        =           9
   degrees of freedom      =         639
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       1.9965187489E-01
      reduced by              2.6493983170E-01
   energy error estimate      4.9246615403E-02
      reduced by              2.6001920543E-01
      effectivity             2.4666242393E-01
   Linf norm of error         7.3659655253E-03
      reduced by              2.6959831442E-01
   Linf error estimate        1.4651093827E-03
      reduced by              3.4400765585E-01
      effectivity             1.9890255767E-01

Eigenvalues and error estimates:
     9.7176761525E+00  1.9685509810E-02

Total Grid:
   number of vertices      =        1209
   number of leaf elements =        2384
   number of levels        =          10
   degrees of freedom      =        1209
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       1.3842343032E-01
      reduced by              6.9332396903E-01
   energy error estimate      3.3412959588E-02
      reduced by              6.7848235486E-01
      effectivity             2.4138225378E-01
   Linf norm of error         5.6067912751E-03
      reduced by              7.6117533484E-01
   Linf error estimate        7.6136384895E-04
      reduced by              5.1966348583E-01
      effectivity             1.3579315006E-01

Eigenvalues and error estimates:
     9.6875164403E+00  9.2130456846E-03

Total Grid:
   number of vertices      =        1209
   number of leaf elements =        2384
   number of levels        =          10
   degrees of freedom      =        1209
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       1.3842343032E-01
   energy error estimate      3.3412959588E-02
      effectivity             2.4138225378E-01
   Linf norm of error         5.6067912751E-03
   Linf error estimate        7.6136384895E-04
      effectivity             1.3579315006E-01

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           3
termination condition:
  maximum vertices achieved
---------------------------------------------------------
