---------------------------------------------------------
           PHAML   Version 1.8.0

Output from the master process
  PDE id is     0
  Number of slave processors is     4

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                  500
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    PHASES
  print_grid_who     MASTER
  print_linsys_when  NEVER
  print_error_when   PHASES
  print_error_who    MASTER
  print_error_what   ENERGY_L2_ERR
  print_errest_what  NEVER
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree                      4
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ_SMOOTH
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    true
  solver             CG_SOLVER
  preconditioner     MG_PRECONDITION
  mg_cycles                   5
  mg_tol             MG_NO_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              2
  mg_postrelax_ho             2
  mg_comm            MGCOMM_NONE
  krylov_iter               100
  krylov_tol         KRYLOV_ERREST_TOL
---------------------------------------------------------

Total Grid:
   number of vertices      =           9
   number of leaf elements =           8
   number of levels        =           1
   degrees of freedom      =          81
   min and max degree      =           4          4

Norms of error:
   energy norm of error       5.4337516374E-02
   L2 norm of error           4.3529268743E-03

Total Grid:
   number of vertices      =          16
   number of leaf elements =          20
   number of levels        =           3
   degrees of freedom      =         181
   min and max degree      =           4          4

Norms of error:
   energy norm of error       1.5675086112E-02
      reduced by              2.8847630805E-01
   L2 norm of error           8.6422364288E-04
      reduced by              1.9853851623E-01

Total Grid:
   number of vertices      =          28
   number of leaf elements =          40
   number of levels        =           4
   degrees of freedom      =         349
   min and max degree      =           4          4

Norms of error:
   energy norm of error       3.3910552459E-03
      reduced by              2.1633407444E-01
   L2 norm of error           1.2138042692E-04
      reduced by              1.4045025025E-01

Total Grid:
   number of vertices      =          51
   number of leaf elements =          76
   number of levels        =           5
   degrees of freedom      =         657
   min and max degree      =           4          4

Norms of error:
   energy norm of error       5.6560628193E-04
      reduced by              1.6679359106E-01
   L2 norm of error           1.6252799273E-05
      reduced by              1.3389967136E-01

Total Grid:
   number of vertices      =          94
   number of leaf elements =         154
   number of levels        =           7
   degrees of freedom      =        1297
   min and max degree      =           4          4

Norms of error:
   energy norm of error       1.8147031337E-04
      reduced by              3.2084211080E-01
   L2 norm of error           3.4898773660E-06
      reduced by              2.1472469495E-01

Total Grid:
   number of vertices      =         193
   number of leaf elements =         332
   number of levels        =           7
   degrees of freedom      =        2761
   min and max degree      =           4          4

Norms of error:
   energy norm of error       2.5633847905E-05
      reduced by              1.4125642607E-01
   L2 norm of error           3.6954108278E-07
      reduced by              1.0588941789E-01

Total Grid:
   number of vertices      =         369
   number of leaf elements =         676
   number of levels        =          10
   degrees of freedom      =        5529
   min and max degree      =           4          4

Norms of error:
   energy norm of error       9.9280071120E-06
      reduced by              1.9365034755E-01
   L2 norm of error           9.4800520926E-08
      reduced by              1.2826790490E-01

Total Grid:
   number of vertices      =         696
   number of leaf elements =        1294
   number of levels        =          10
   degrees of freedom      =       10545
   min and max degree      =           4          4

Norms of error:
   energy norm of error       1.8790208517E-06
      reduced by              1.8926465609E-01
   L2 norm of error           1.5576409074E-08
      reduced by              1.6430720973E-01

Total Grid:
   number of vertices      =         696
   number of leaf elements =        1294
   number of levels        =          10
   degrees of freedom      =       10545
   min and max degree      =           4          4

Norms of error:
   energy norm of error       1.8790208517E-06
   L2 norm of error           1.5576409074E-08

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           7
termination condition:
  maximum vertices achieved
---------------------------------------------------------
