---------------------------------------------------------
           PHAML   Version 1.8.0

Output from the master process
  PDE id is     0
  Number of slave processors is     4

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                  500
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    PHASES
  print_grid_who     MASTER
  print_linsys_when  NEVER
  print_error_when   PHASES
  print_error_who    MASTER
  print_error_what   ENERGY_L2_ERR
  print_errest_what  NEVER
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree                      4
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ_SMOOTH
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    false
  solver             MG_SOLVER
  mg_cycles                 100
  mg_tol             MG_ERREST_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_CONVENTIONAL
---------------------------------------------------------

Total Grid:
   number of vertices      =           9
   number of leaf elements =           8
   number of levels        =           1
   degrees of freedom      =          81
   min and max degree      =           4          4

Norms of error:
   energy norm of error       5.4395415695E-02
   L2 norm of error           4.5719937672E-03

Total Grid:
   number of vertices      =          16
   number of leaf elements =          20
   number of levels        =           3
   degrees of freedom      =         181
   min and max degree      =           4          4

Norms of error:
   energy norm of error       1.5675824098E-02
      reduced by              2.8818281647E-01
   L2 norm of error           8.6428944442E-04
      reduced by              1.8903994371E-01

Total Grid:
   number of vertices      =          28
   number of leaf elements =          40
   number of levels        =           4
   degrees of freedom      =         349
   min and max degree      =           4          4

Norms of error:
   energy norm of error       3.3913276552E-03
      reduced by              2.1634126755E-01
   L2 norm of error           1.2135647507E-04
      reduced by              1.4041184450E-01

Total Grid:
   number of vertices      =          51
   number of leaf elements =          76
   number of levels        =           5
   degrees of freedom      =         657
   min and max degree      =           4          4

Norms of error:
   energy norm of error       5.6564269242E-04
      reduced by              1.6679092966E-01
   L2 norm of error           1.6255206239E-05
      reduced by              1.3394593267E-01

Total Grid:
   number of vertices      =          94
   number of leaf elements =         154
   number of levels        =           7
   degrees of freedom      =        1297
   min and max degree      =           4          4

Norms of error:
   energy norm of error       1.8147054553E-04
      reduced by              3.2082186858E-01
   L2 norm of error           3.4899482040E-06
      reduced by              2.1469725777E-01

Total Grid:
   number of vertices      =         193
   number of leaf elements =         332
   number of levels        =           7
   degrees of freedom      =        2761
   min and max degree      =           4          4

Norms of error:
   energy norm of error       2.5633936945E-05
      reduced by              1.4125673601E-01
   L2 norm of error           3.6954103196E-07
      reduced by              1.0588725401E-01

Total Grid:
   number of vertices      =         369
   number of leaf elements =         676
   number of levels        =          10
   degrees of freedom      =        5529
   min and max degree      =           4          4

Norms of error:
   energy norm of error       1.4995912049E-04
      reduced by              2.9250114958E+00
   L2 norm of error           3.0088490267E-06
      reduced by              4.0710621643E+00

Total Grid:
   number of vertices      =         441
   number of leaf elements =         818
   number of levels        =          13
   degrees of freedom      =        6669
   min and max degree      =           4          4

Norms of error:
   energy norm of error       3.6983480055E-05
      reduced by              2.4662374609E-01
   L2 norm of error           1.0253145051E-06
      reduced by              3.4076635152E-01

Total Grid:
   number of vertices      =         753
   number of leaf elements =        1418
   number of levels        =          17
   degrees of freedom      =       11517
   min and max degree      =           4          4

Norms of error:
   energy norm of error       1.3053281237E-04
      reduced by              3.5294897120E+00
   L2 norm of error           2.6523379123E-06
      reduced by              2.5868530086E+00

Total Grid:
   number of vertices      =         753
   number of leaf elements =        1418
   number of levels        =          17
   degrees of freedom      =       11517
   min and max degree      =           4          4

Norms of error:
   energy norm of error       1.3053281237E-04
   L2 norm of error           2.6523379123E-06

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           8
termination condition:
  maximum vertices achieved
---------------------------------------------------------
