---------------------------------------------------------
           PHAML   Version 1.6.2

Output from slave number     1
  PDE id is     0
  Number of slave processors is     1

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                  500
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    PHASES
  print_grid_who     SLAVES
  print_linsys_when  NEVER
  print_error_when   PHASES
  print_error_who    SLAVES
  print_error_what   ENERGY_L2_ERR
  print_errest_what  NEVER
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree                      4
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ_SMOOTH
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    true
  solver             CG_SOLVER
  preconditioner     MG_PRECONDITION
  mg_cycles                   2
  mg_tol             MG_NO_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_NONE
  krylov_iter               100
  krylov_tol         KRYLOV_ERREST_TOL
---------------------------------------------------------

My Grid:
   number of vertices       =           9
   number of vertices I own =           9
   number of elements       =           8
   number of leaf elements  =           8
   leaf elements I own      =           8
   number of levels         =           1
   degrees of freedom       =          81
   degrees of freedom I own =          81
   min and max degree       =           4          4

Norms of error:
   energy norm of error       5.4350058876E-02
   L2 norm of error           4.3482488022E-03

My Grid:
   number of vertices       =          16
   number of vertices I own =          16
   number of elements       =          32
   number of leaf elements  =          20
   leaf elements I own      =          20
   number of levels         =           3
   degrees of freedom       =         181
   degrees of freedom I own =         181
   min and max degree       =           4          4

Norms of error:
   energy norm of error       1.5675650516E-02
      reduced by              2.8842012024E-01
   L2 norm of error           8.6410348200E-04
      reduced by              1.9872447997E-01

My Grid:
   number of vertices       =          28
   number of vertices I own =          28
   number of elements       =          72
   number of leaf elements  =          40
   leaf elements I own      =          40
   number of levels         =           4
   degrees of freedom       =         349
   degrees of freedom I own =         349
   min and max degree       =           4          4

Norms of error:
   energy norm of error       3.3911222655E-03
      reduced by              2.1633056070E-01
   L2 norm of error           1.2136834171E-04
      reduced by              1.4045579522E-01

My Grid:
   number of vertices       =          51
   number of vertices I own =          51
   number of elements       =         144
   number of leaf elements  =          76
   leaf elements I own      =          76
   number of levels         =           5
   degrees of freedom       =         657
   degrees of freedom I own =         657
   min and max degree       =           4          4

Norms of error:
   energy norm of error       5.6559617453E-04
      reduced by              1.6678731413E-01
   L2 norm of error           1.6250094023E-05
      reduced by              1.3389071477E-01

My Grid:
   number of vertices       =          94
   number of vertices I own =          94
   number of elements       =         300
   number of leaf elements  =         154
   leaf elements I own      =         154
   number of levels         =           7
   degrees of freedom       =        1297
   degrees of freedom I own =        1297
   min and max degree       =           4          4

Norms of error:
   energy norm of error       1.8147796067E-04
      reduced by              3.2086136513E-01
   L2 norm of error           3.4893063074E-06
      reduced by              2.1472529959E-01

My Grid:
   number of vertices       =         193
   number of vertices I own =         193
   number of elements       =         656
   number of leaf elements  =         332
   leaf elements I own      =         332
   number of levels         =           7
   degrees of freedom       =        2761
   degrees of freedom I own =        2761
   min and max degree       =           4          4

Norms of error:
   energy norm of error       2.5633907149E-05
      reduced by              1.4125080012E-01
   L2 norm of error           3.6952805319E-07
      reduced by              1.0590301356E-01

My Grid:
   number of vertices       =         361
   number of vertices I own =         361
   number of elements       =        1316
   number of leaf elements  =         662
   leaf elements I own      =         662
   number of levels         =           9
   degrees of freedom       =        5413
   degrees of freedom I own =        5413
   min and max degree       =           4          4

Norms of error:
   energy norm of error       9.4261922388E-06
      reduced by              3.6772358516E-01
   L2 norm of error           9.0411853640E-08
      reduced by              2.4466844360E-01

My Grid:
   number of vertices       =         688
   number of vertices I own =         688
   number of elements       =        2540
   number of leaf elements  =        1274
   leaf elements I own      =        1274
   number of levels         =           9
   degrees of freedom       =       10393
   degrees of freedom I own =       10393
   min and max degree       =           4          4

Norms of error:
   energy norm of error       1.9385108053E-06
      reduced by              2.0565152463E-01
   L2 norm of error           1.6336825820E-08
      reduced by              1.8069340648E-01

My Grid:
   number of vertices       =         688
   number of vertices I own =         688
   number of elements       =        2540
   number of leaf elements  =        1274
   leaf elements I own      =        1274
   number of levels         =           9
   degrees of freedom       =       10393
   degrees of freedom I own =       10393
   min and max degree       =           4          4

Norms of error:
   energy norm of error       1.9385108053E-06
   L2 norm of error           1.6336825820E-08

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           7
termination condition:
  maximum vertices achieved
---------------------------------------------------------
