---------------------------------------------------------
           PHAML   Version 1.6.2

Output from the master process
  PDE id is     0
  Number of slave processors is     4

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                  500
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    PHASES
  print_grid_who     MASTER
  print_linsys_when  NEVER
  print_error_when   PHASES
  print_error_who    MASTER
  print_error_what   ENERGY_L2_ERR
  print_errest_what  NEVER
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ_SMOOTH
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    false
  solver             MG_SOLVER
  mg_cycles                 100
  mg_tol             MG_ERREST_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_CONVENTIONAL
---------------------------------------------------------

Total Grid:
   number of vertices      =           9
   number of leaf elements =           8
   number of levels        =           1
   degrees of freedom      =           9
   min and max degree      =           1          1

Norms of error:
   energy norm of error       2.4791277665E+00
   L2 norm of error           3.5000011056E-01

Total Grid:
   number of vertices      =          27
   number of leaf elements =          38
   number of levels        =           4
   degrees of freedom      =          27
   min and max degree      =           1          1

Norms of error:
   energy norm of error       1.4285611863E+00
      reduced by              5.7623540248E-01
   L2 norm of error           1.0588604099E-01
      reduced by              3.0253145013E-01

Total Grid:
   number of vertices      =          38
   number of leaf elements =          52
   number of levels        =           6
   degrees of freedom      =          38
   min and max degree      =           1          1

Norms of error:
   energy norm of error       1.3336106370E+00
      reduced by              9.3353413897E-01
   L2 norm of error           8.1309003306E-02
      reduced by              7.6789161766E-01

Total Grid:
   number of vertices      =          74
   number of leaf elements =         118
   number of levels        =           7
   degrees of freedom      =          74
   min and max degree      =           1          1

Norms of error:
   energy norm of error       8.1773957052E-01
      reduced by              6.1317715066E-01
   L2 norm of error           2.7883265771E-02
      reduced by              3.4292962203E-01

Total Grid:
   number of vertices      =         145
   number of leaf elements =         246
   number of levels        =           8
   degrees of freedom      =         145
   min and max degree      =           1          1

Norms of error:
   energy norm of error       5.1482102381E-01
      reduced by              6.2956599188E-01
   L2 norm of error           1.3406391964E-02
      reduced by              4.8080422410E-01

Total Grid:
   number of vertices      =         345
   number of leaf elements =         613
   number of levels        =          10
   degrees of freedom      =         345
   min and max degree      =           1          1

Norms of error:
   energy norm of error       3.3131828931E-01
      reduced by              3.2178006918E-01
   L2 norm of error           5.2436439829E-03
      reduced by              1.9556507063E-01

Total Grid:
   number of vertices      =         631
   number of leaf elements =        1175
   number of levels        =          11
   degrees of freedom      =         631
   min and max degree      =           1          1

Norms of error:
   energy norm of error       2.4598536540E-01
      reduced by              7.4244426987E-01
   L2 norm of error           3.4568880575E-03
      reduced by              6.5925300587E-01

Total Grid:
   number of vertices      =         631
   number of leaf elements =        1175
   number of levels        =          11
   degrees of freedom      =         631
   min and max degree      =           1          1

Norms of error:
   energy norm of error       2.4598536540E-01
   L2 norm of error           3.4568880575E-03

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           6
termination condition:
  maximum vertices achieved
---------------------------------------------------------
