---------------------------------------------------------
           PHAML   Version 1.8.0

Output from the master process
  PDE id is     0
  Number of slave processors is     4

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                  500
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    PHASES
  print_grid_who     MASTER_ALL
  print_linsys_when  NEVER
  print_error_when   NEVER
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert            50
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ_SMOOTH
  derefine           true
  partition_method   ZOLTAN_HSFC
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    false
  solver             MG_SOLVER
  mg_cycles          infinity
  mg_tol             MG_ERREST_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_FUDOP
---------------------------------------------------------

Individual Grids:
   number of vertices       =           9          9          9          9
   number of vertices I own =           9          9          9          9
   number of elements       =           8          8          8          8
   number of leaf elements  =           8          8          8          8
   leaf elements I own      =           8          8          8          8
   number of levels         =           1          1          1          1
   degrees of freedom       =           9          9          9          9
   degrees of freedom I own =           9          9          9          9
   min degree               =           1          1          1          1
   max degree               =           1          1          1          1

Total Grid:
   number of vertices      =           9
   number of leaf elements =           8
   number of levels        =           1
   degrees of freedom      =           9
   min and max degree      =           1          1

Individual Grids:
   number of vertices       =          25         25         25         25
   number of vertices I own =          25         25         25         25
   number of elements       =          56         56         56         56
   number of leaf elements  =          32         32         32         32
   leaf elements I own      =          32         32         32         32
   number of levels         =           3          3          3          3
   degrees of freedom       =          25         25         25         25
   degrees of freedom I own =          25         25         25         25
   min degree               =           1          1          1          1
   max degree               =           1          1          1          1

Total Grid:
   number of vertices      =          25
   number of leaf elements =          32
   number of levels        =           3
   degrees of freedom      =          25
   min and max degree      =           1          1

Individual Grids:
   number of vertices       =          41         41         41         41
   number of vertices I own =          41         41         41         41
   number of elements       =         120        120        120        120
   number of leaf elements  =          64         64         64         64
   leaf elements I own      =          64         64         64         64
   number of levels         =           4          4          4          4
   degrees of freedom       =          41         41         41         41
   degrees of freedom I own =          41         41         41         41
   min degree               =           1          1          1          1
   max degree               =           1          1          1          1

Total Grid:
   number of vertices      =          41
   number of leaf elements =          64
   number of levels        =           4
   degrees of freedom      =          41
   min and max degree      =           1          1

Individual Grids:
   number of vertices       =          81         81         81         81
   number of vertices I own =          81         81         81         81
   number of elements       =         248        248        248        248
   number of leaf elements  =         128        128        128        128
   leaf elements I own      =         128        128        128        128
   number of levels         =           5          5          5          5
   degrees of freedom       =          81         81         81         81
   degrees of freedom I own =          81         81         81         81
   min degree               =           1          1          1          1
   max degree               =           1          1          1          1

Total Grid:
   number of vertices      =          81
   number of leaf elements =         128
   number of levels        =           5
   degrees of freedom      =          81
   min and max degree      =           1          1

Individual Grids:
   number of vertices       =          79         79         73         73
   number of vertices I own =          40         42         37         38
   number of elements       =         268        268        244        244
   number of leaf elements  =         138        138        126        126
   leaf elements I own      =          76         76         64         64
   number of levels         =           7          7          6          6
   degrees of freedom       =          79         79         73         73
   degrees of freedom I own =          40         42         37         38
   min degree               =           1          1          1          1
   max degree               =           1          1          1          1

Total Grid:
   number of vertices      =         157
   number of leaf elements =         280
   number of levels        =           7
   degrees of freedom      =         157
   min and max degree      =           1          1

Individual Grids:
   number of vertices       =         187        194        169        135
   number of vertices I own =         119        120         75         77
   number of elements       =         684        704        622        488
   number of leaf elements  =         346        356        315        248
   leaf elements I own      =         238        230        133        131
   number of levels         =           8          8          8          8
   degrees of freedom       =         187        194        169        135
   degrees of freedom I own =         119        120         75         77
   min degree               =           1          1          1          1
   max degree               =           1          1          1          1

Total Grid:
   number of vertices      =         391
   number of leaf elements =         732
   number of levels        =           8
   degrees of freedom      =         391
   min and max degree      =           1          1

Individual Grids:
   number of vertices       =         288        291        294        294
   number of vertices I own =         183        178        157        213
   number of elements       =        1090       1096       1108       1088
   number of leaf elements  =         549        552        558        548
   leaf elements I own      =         364        360        288        384
   number of levels         =           9          9          9          9
   degrees of freedom       =         288        291        294        294
   degrees of freedom I own =         183        178        157        213
   min degree               =           1          1          1          1
   max degree               =           1          1          1          1

Total Grid:
   number of vertices      =         731
   number of leaf elements =        1396
   number of levels        =           9
   degrees of freedom      =         731
   min and max degree      =           1          1

Individual Grids:
   number of vertices       =         288        291        294        294
   number of vertices I own =         183        178        157        213
   number of elements       =        1090       1096       1108       1088
   number of leaf elements  =         549        552        558        548
   leaf elements I own      =         364        360        288        384
   number of levels         =           9          9          9          9
   degrees of freedom       =         288        291        294        294
   degrees of freedom I own =         183        178        157        213
   min degree               =           1          1          1          1
   max degree               =           1          1          1          1

Total Grid:
   number of vertices      =         731
   number of leaf elements =        1396
   number of levels        =           9
   degrees of freedom      =         731
   min and max degree      =           1          1

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           6
termination condition:
  maximum vertices achieved
---------------------------------------------------------
