---------------------------------------------------------
           PHAML   Version 1.8.0

Output from slave number     2
  PDE id is     0
  Number of slave processors is     2

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                  500
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    PHASES
  print_grid_who     EVERYONE
  print_linsys_when  PHASES
  print_linsys_who   EVERYONE
  print_error_when   PHASES
  print_error_who    EVERYONE
  print_error_what   LINF_ERR
  print_errest_what  LINF_ERREST
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ_SMOOTH
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    false
  solver             MG_SOLVER
  mg_cycles                   2
  mg_tol             MG_ERREST_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_FUDOP
---------------------------------------------------------

My Grid:
   number of vertices       =           9
   number of vertices I own =           9
   number of elements       =           8
   number of leaf elements  =           8
   leaf elements I own      =           8
   number of levels         =           1
   degrees of freedom       =           9
   degrees of freedom I own =           9
   min and max degree       =           1          1

My Linear System:
   number of equations =           9
   number of equations I own =           9
   number of nonzeroes =          41
   condensed matrix number of equations =           9
   condensed matrix number of equations I own =           9
   condensed matrix number of nonzeroes =          41
   coarse matrix neq =           1
   coarse (half) bandwidth =           0

Norms of error:
   Linf norm of error         1.0536246503E+00
   Linf error estimate        1.1645061848E+00
      effectivity             1.1052381742E+00

My Grid:
   number of vertices       =          27
   number of vertices I own =          27
   number of elements       =          68
   number of leaf elements  =          38
   leaf elements I own      =          38
   number of levels         =           4
   degrees of freedom       =          27
   degrees of freedom I own =          27
   min and max degree       =           1          1

My Linear System:
   number of equations =          27
   number of equations I own =          27
   number of nonzeroes =         155
   condensed matrix number of equations =          27
   condensed matrix number of equations I own =          27
   condensed matrix number of nonzeroes =         155
   coarse matrix neq =           1
   coarse (half) bandwidth =           0

Norms of error:
   Linf norm of error         6.7489276612E-01
      reduced by              6.4054382737E-01
   Linf error estimate        3.1966359115E-01
      reduced by              2.7450570493E-01
      effectivity             4.7365093715E-01

My Grid:
   number of vertices       =          36
   number of vertices I own =          36
   number of elements       =          88
   number of leaf elements  =          48
   leaf elements I own      =          48
   number of levels         =           6
   degrees of freedom       =          36
   degrees of freedom I own =          36
   min and max degree       =           1          1

My Linear System:
   number of equations =          36
   number of equations I own =          36
   number of nonzeroes =         202
   condensed matrix number of equations =          36
   condensed matrix number of equations I own =          36
   condensed matrix number of nonzeroes =         202
   coarse matrix neq =           1
   coarse (half) bandwidth =           0

Norms of error:
   Linf norm of error         4.7530105786E-01
      reduced by              7.0426159787E-01
   Linf error estimate        1.3917147125E-01
      reduced by              4.3536854087E-01
      effectivity             2.9280698821E-01

My Grid:
   number of vertices       =          75
   number of vertices I own =          75
   number of elements       =         208
   number of leaf elements  =         108
   leaf elements I own      =         108
   number of levels         =           8
   degrees of freedom       =          75
   degrees of freedom I own =          75
   min and max degree       =           1          1

My Linear System:
   number of equations =          75
   number of equations I own =          75
   number of nonzeroes =         439
   condensed matrix number of equations =          75
   condensed matrix number of equations I own =          75
   condensed matrix number of nonzeroes =         439
   coarse matrix neq =           1
   coarse (half) bandwidth =           0

Norms of error:
   Linf norm of error         2.5534403332E-01
      reduced by              5.3722588893E-01
   Linf error estimate        5.3212994702E-02
      reduced by              3.8235562379E-01
      effectivity             2.0839725139E-01

My Grid:
   number of vertices       =         171
   number of vertices I own =         171
   number of elements       =         580
   number of leaf elements  =         294
   leaf elements I own      =         294
   number of levels         =           9
   degrees of freedom       =         171
   degrees of freedom I own =         171
   min and max degree       =           1          1

My Linear System:
   number of equations =         171
   number of equations I own =         171
   number of nonzeroes =        1099
   condensed matrix number of equations =         171
   condensed matrix number of equations I own =         171
   condensed matrix number of nonzeroes =        1099
   coarse matrix neq =           1
   coarse (half) bandwidth =           0

Norms of error:
   Linf norm of error         1.0115694205E-01
      reduced by              3.9615941182E-01
   Linf error estimate        1.6603506558E-02
      reduced by              3.1201977358E-01
      effectivity             1.6413610595E-01

My Grid:
   number of vertices       =         176
   number of vertices I own =         149
   number of elements       =         600
   number of leaf elements  =         304
   leaf elements I own      =         252
   number of levels         =          10
   degrees of freedom       =         176
   degrees of freedom I own =         149
   min and max degree       =           1          1

My Linear System:
   number of equations =         176
   number of equations I own =         149
   number of nonzeroes =        1134
   condensed matrix number of equations =         176
   condensed matrix number of equations I own =         149
   condensed matrix number of nonzeroes =        1134
   coarse matrix neq =           1
   coarse (half) bandwidth =           0

Norms of error:
   Linf norm of error         4.0757234166E-02
      reduced by              4.0291089607E-01
   Linf error estimate        9.2017496201E-03
      reduced by              5.5420519682E-01
      effectivity             2.2576972674E-01

My Grid:
   number of vertices       =         405
   number of vertices I own =         370
   number of elements       =        1446
   number of leaf elements  =         727
   leaf elements I own      =         657
   number of levels         =          12
   degrees of freedom       =         405
   degrees of freedom I own =         370
   min and max degree       =           1          1

My Linear System:
   number of equations =         405
   number of equations I own =         370
   number of nonzeroes =        2667
   condensed matrix number of equations =         405
   condensed matrix number of equations I own =         370
   condensed matrix number of nonzeroes =        2667
   coarse matrix neq =           1
   coarse (half) bandwidth =           0

Norms of error:
   Linf norm of error         3.0902407719E-02
      reduced by              7.5820669266E-01
   Linf error estimate        3.4627402338E-03
      reduced by              3.7631324223E-01
      effectivity             1.1205405952E-01

My Grid:
   number of vertices       =         405
   number of vertices I own =         370
   number of elements       =        1446
   number of leaf elements  =         727
   leaf elements I own      =         657
   number of levels         =          12
   degrees of freedom       =         405
   degrees of freedom I own =         370
   min and max degree       =           1          1

Norms of error:
   Linf norm of error         3.0902407719E-02
   Linf error estimate        3.4627402338E-03
      effectivity             1.1205405952E-01

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           6
termination condition:
  maximum vertices achieved
---------------------------------------------------------
