---------------------------------------------------------
           PHAML   Version 1.6.2

Output from slave number     1
  PDE id is     0
  Number of slave processors is     1

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                  500
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    PHASES
  print_grid_who     SLAVES
  print_linsys_when  PHASES
  print_linsys_who   SLAVES
  print_error_when   PHASES
  print_error_who    SLAVES
  print_error_what   ENERGY_LINF_L2_ERR
  print_errest_what  ENERGY_LINF_L2_ERREST
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            RELATIVE ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ_SMOOTH
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    false
  solver             MG_SOLVER
  mg_cycles                   2
  mg_tol             MG_ERREST_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_FUDOP
---------------------------------------------------------

My Grid:
   number of vertices       =           9
   number of vertices I own =           9
   number of elements       =           8
   number of leaf elements  =           8
   leaf elements I own      =           8
   number of levels         =           1
   degrees of freedom       =           9
   degrees of freedom I own =           9
   min and max degree       =           1          1

My Linear System:
   number of equations =           9
   number of equations I own =           9
   number of nonzeroes =          41
   condensed matrix number of equations =           9
   condensed matrix number of equations I own =           9
   condensed matrix number of nonzeroes =          41
   coarse matrix neq =           1
   coarse (half) bandwidth =           0

Norms of error:
   energy norm of error       8.8185483929E-01
   energy error estimate      9.2214211182E-01
      effectivity             1.0456846986E+00
   Linf norm of error         5.2681232515E-01
   Linf error estimate        5.8225309239E-01
      effectivity             1.1052381742E+00
   L2 norm of error           2.0483313171E+00
   L2 error estimate          6.4224833636E-01
      effectivity             3.1354709611E-01

My Grid:
   number of vertices       =          27
   number of vertices I own =          27
   number of elements       =          68
   number of leaf elements  =          38
   leaf elements I own      =          38
   number of levels         =           4
   degrees of freedom       =          27
   degrees of freedom I own =          27
   min and max degree       =           1          1

My Linear System:
   number of equations =          27
   number of equations I own =          27
   number of nonzeroes =         155
   condensed matrix number of equations =          27
   condensed matrix number of equations I own =          27
   condensed matrix number of nonzeroes =         155
   coarse matrix neq =           1
   coarse (half) bandwidth =           0

Norms of error:
   energy norm of error       6.5026965583E-01
      reduced by              7.3738854385E-01
   energy error estimate      3.3825623891E-01
      reduced by              3.6681573759E-01
      effectivity             5.2017841503E-01
   Linf norm of error         3.3744638306E-01
      reduced by              6.4054382737E-01
   Linf error estimate        1.5983179557E-01
      reduced by              2.7450570493E-01
      effectivity             4.7365093715E-01
   L2 norm of error           7.9421424625E-01
      reduced by              3.8773719838E-01
   L2 error estimate          1.5612524188E-01
      reduced by              2.4309170308E-01
      effectivity             1.9657824399E-01

My Grid:
   number of vertices       =          36
   number of vertices I own =          36
   number of elements       =          88
   number of leaf elements  =          48
   leaf elements I own      =          48
   number of levels         =           6
   degrees of freedom       =          36
   degrees of freedom I own =          36
   min and max degree       =           1          1

My Linear System:
   number of equations =          36
   number of equations I own =          36
   number of nonzeroes =         202
   condensed matrix number of equations =          36
   condensed matrix number of equations I own =          36
   condensed matrix number of nonzeroes =         202
   coarse matrix neq =           1
   coarse (half) bandwidth =           0

Norms of error:
   energy norm of error       6.4537620763E-01
      reduced by              9.9247474004E-01
   energy error estimate      2.5212094969E-01
      reduced by              7.4535491347E-01
      effectivity             3.9065733553E-01
   Linf norm of error         2.3765052893E-01
      reduced by              7.0426159787E-01
   Linf error estimate        6.9585735623E-02
      reduced by              4.3536854087E-01
      effectivity             2.9280698821E-01
   L2 norm of error           6.9616016512E-01
      reduced by              8.7653950859E-01
   L2 error estimate          1.0119695103E-01
      reduced by              6.4817802561E-01
      effectivity             1.4536446654E-01

My Grid:
   number of vertices       =          75
   number of vertices I own =          75
   number of elements       =         208
   number of leaf elements  =         108
   leaf elements I own      =         108
   number of levels         =           8
   degrees of freedom       =          75
   degrees of freedom I own =          75
   min and max degree       =           1          1

My Linear System:
   number of equations =          75
   number of equations I own =          75
   number of nonzeroes =         439
   condensed matrix number of equations =          75
   condensed matrix number of equations I own =          75
   condensed matrix number of nonzeroes =         439
   coarse matrix neq =           1
   coarse (half) bandwidth =           0

Norms of error:
   energy norm of error       4.5692486556E-01
      reduced by              7.0799769213E-01
   energy error estimate      1.3074970177E-01
      reduced by              5.1859911654E-01
      effectivity             2.8615142581E-01
   Linf norm of error         1.2767201666E-01
      reduced by              5.3722588893E-01
   Linf error estimate        2.6606497351E-02
      reduced by              3.8235562379E-01
      effectivity             2.0839725139E-01
   L2 norm of error           2.8252545205E-01
      reduced by              4.0583398219E-01
   L2 error estimate          4.3864825524E-02
      reduced by              4.3345995188E-01
      effectivity             1.5525973043E-01

My Grid:
   number of vertices       =         171
   number of vertices I own =         171
   number of elements       =         580
   number of leaf elements  =         294
   leaf elements I own      =         294
   number of levels         =           9
   degrees of freedom       =         171
   degrees of freedom I own =         171
   min and max degree       =           1          1

My Linear System:
   number of equations =         171
   number of equations I own =         171
   number of nonzeroes =        1099
   condensed matrix number of equations =         171
   condensed matrix number of equations I own =         171
   condensed matrix number of nonzeroes =        1099
   coarse matrix neq =           1
   coarse (half) bandwidth =           0

Norms of error:
   energy norm of error       2.6576786716E-01
      reduced by              5.8164457047E-01
   energy error estimate      8.0158920904E-02
      reduced by              6.1307153913E-01
      effectivity             3.0161253789E-01
   Linf norm of error         5.0578471025E-02
      reduced by              3.9615941182E-01
   Linf error estimate        8.3017532792E-03
      reduced by              3.1201977358E-01
      effectivity             1.6413610595E-01
   L2 norm of error           8.8038870003E-02
      reduced by              3.1161394261E-01
   L2 error estimate          1.9435784363E-02
      reduced by              4.4308358989E-01
      effectivity             2.2076367362E-01

My Grid:
   number of vertices       =         290
   number of vertices I own =         290
   number of elements       =         996
   number of leaf elements  =         502
   leaf elements I own      =         502
   number of levels         =          10
   degrees of freedom       =         290
   degrees of freedom I own =         290
   min and max degree       =           1          1

My Linear System:
   number of equations =         290
   number of equations I own =         290
   number of nonzeroes =        1872
   condensed matrix number of equations =         290
   condensed matrix number of equations I own =         290
   condensed matrix number of nonzeroes =        1872
   coarse matrix neq =           1
   coarse (half) bandwidth =           0

Norms of error:
   energy norm of error       1.7116424833E-01
      reduced by              6.4403665559E-01
   energy error estimate      5.7517866492E-02
      reduced by              7.1754791411E-01
      effectivity             3.3603902131E-01
   Linf norm of error         2.0391796884E-02
      reduced by              4.0317147732E-01
   Linf error estimate        4.5990492190E-03
      reduced by              5.5398529254E-01
      effectivity             2.2553427955E-01
   L2 norm of error           4.2356990832E-02
      reduced by              4.8111692972E-01
   L2 error estimate          1.0626551474E-02
      reduced by              5.4675187146E-01
      effectivity             2.5088069916E-01

My Grid:
   number of vertices       =         730
   number of vertices I own =         730
   number of elements       =        2620
   number of leaf elements  =        1314
   leaf elements I own      =        1314
   number of levels         =          12
   degrees of freedom       =         730
   degrees of freedom I own =         730
   min and max degree       =           1          1

My Linear System:
   number of equations =         730
   number of equations I own =         730
   number of nonzeroes =        4816
   condensed matrix number of equations =         730
   condensed matrix number of equations I own =         730
   condensed matrix number of nonzeroes =        4816
   coarse matrix neq =           1
   coarse (half) bandwidth =           0

Norms of error:
   energy norm of error       1.0280478467E-01
      reduced by              6.0062066510E-01
   energy error estimate      3.4125868709E-02
      reduced by              5.9330901492E-01
      effectivity             3.3194825335E-01
   Linf norm of error         1.5451204794E-02
      reduced by              7.5771668784E-01
   Linf error estimate        1.7316296714E-03
      reduced by              3.7651905621E-01
      effectivity             1.1207085107E-01
   L2 norm of error           1.5725482578E-02
      reduced by              3.7126061766E-01
   L2 error estimate          4.3090313449E-03
      reduced by              4.0549668022E-01
      effectivity             2.7401584170E-01

My Grid:
   number of vertices       =         730
   number of vertices I own =         730
   number of elements       =        2620
   number of leaf elements  =        1314
   leaf elements I own      =        1314
   number of levels         =          12
   degrees of freedom       =         730
   degrees of freedom I own =         730
   min and max degree       =           1          1

Norms of error:
   energy norm of error       1.0280478467E-01
   energy error estimate      3.4125868709E-02
      effectivity             3.3194825335E-01
   Linf norm of error         1.5451204794E-02
   Linf error estimate        1.7316296714E-03
      effectivity             1.1207085107E-01
   L2 norm of error           1.5725482578E-02
   L2 error estimate          4.3090313449E-03
      effectivity             2.7401584170E-01

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           6
termination condition:
  maximum vertices achieved
---------------------------------------------------------
