---------------------------------------------------------
           PHAML   Version 1.8.0

Output from the master process
  PDE id is     0
  Number of slave processors is     4

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                  500
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    PHASES
  print_grid_who     MASTER
  print_linsys_when  PHASES
  print_linsys_who   MASTER
  print_error_when   PHASES
  print_error_who    MASTER
  print_error_what   ENERGY_LINF_L2_ERR
  print_errest_what  ENERGY_LINF_L2_ERREST
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ_SMOOTH
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    false
  solver             MG_SOLVER
  mg_cycles                   2
  mg_tol             MG_ERREST_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_FUDOP
---------------------------------------------------------

Total Grid:
   number of vertices      =           9
   number of leaf elements =           8
   number of levels        =           1
   degrees of freedom      =           9
   min and max degree      =           1          1

Total Linear System:
   number of equations =           9
   number of nonzeroes =          41
   condensed matrix number of equations =           9
   condensed matrix number of nonzeroes =          41
   coarse matrix neq =           1
   coarse (half) bandwidth =           0

Norms of error:
   energy norm of error       3.8589726446E+00
   energy error estimate      2.7431604171E+00
      effectivity             7.1085251689E-01
   Linf norm of error         1.0536246503E+00
   Linf error estimate        1.1645061848E+00
      effectivity             1.1052381742E+00
   L2 norm of error           4.5345860840E-01
   L2 error estimate          3.8794146656E-01
      effectivity             8.5551681976E-01

Total Grid:
   number of vertices      =          27
   number of leaf elements =          38
   number of levels        =           4
   degrees of freedom      =          27
   min and max degree      =           1          1

Total Linear System:
   number of equations =          27
   number of nonzeroes =         155
   condensed matrix number of equations =          27
   condensed matrix number of nonzeroes =         155
   coarse matrix neq =           1
   coarse (half) bandwidth =           0

Norms of error:
   energy norm of error       2.9445536356E+00
      reduced by              7.6304081598E-01
   energy error estimate      1.1756930091E+00
      reduced by              4.2859068753E-01
      effectivity             3.9927715866E-01
   Linf norm of error         6.7489276612E-01
      reduced by              6.4054382737E-01
   Linf error estimate        3.1966359115E-01
      reduced by              2.7450570493E-01
      effectivity             4.7365093715E-01
   L2 norm of error           1.8334069947E-01
      reduced by              4.0431628393E-01
   L2 error estimate          5.8854826900E-02
      reduced by              1.5171058516E-01
      effectivity             3.2101343057E-01

Total Grid:
   number of vertices      =          36
   number of leaf elements =          48
   number of levels        =           6
   degrees of freedom      =          36
   min and max degree      =           1          1

Total Linear System:
   number of equations =          36
   number of nonzeroes =         202
   condensed matrix number of equations =          36
   condensed matrix number of nonzeroes =         202
   coarse matrix neq =           1
   coarse (half) bandwidth =           0

Norms of error:
   energy norm of error       2.9224671391E+00
      reduced by              9.9249920388E-01
   energy error estimate      8.7510266200E-01
      reduced by              7.4432922132E-01
      effectivity             2.9943969268E-01
   Linf norm of error         4.7530105786E-01
      reduced by              7.0426159787E-01
   Linf error estimate        1.3917147125E-01
      reduced by              4.3536854087E-01
      effectivity             2.9280698821E-01
   L2 norm of error           1.6071015387E-01
      reduced by              8.7656561985E-01
   L2 error estimate          3.5587864849E-02
      reduced by              6.0467198230E-01
      effectivity             2.2144129659E-01

Total Grid:
   number of vertices      =          75
   number of leaf elements =         108
   number of levels        =           8
   degrees of freedom      =          75
   min and max degree      =           1          1

Total Linear System:
   number of equations =          75
   number of nonzeroes =         439
   condensed matrix number of equations =          75
   condensed matrix number of nonzeroes =         439
   coarse matrix neq =           1
   coarse (half) bandwidth =           0

Norms of error:
   energy norm of error       2.0694572753E+00
      reduced by              7.0811994689E-01
   energy error estimate      5.2463178417E-01
      reduced by              5.9950884273E-01
      effectivity             2.5351177356E-01
   Linf norm of error         2.5534403332E-01
      reduced by              5.3722588893E-01
   Linf error estimate        5.3212994702E-02
      reduced by              3.8235562379E-01
      effectivity             2.0839725139E-01
   L2 norm of error           6.5235431360E-02
      reduced by              4.0591978657E-01
   L2 error estimate          1.2385956688E-02
      reduced by              3.4803876940E-01
      effectivity             1.8986548306E-01

Total Grid:
   number of vertices      =         171
   number of leaf elements =         294
   number of levels        =           9
   degrees of freedom      =         171
   min and max degree      =           1          1

Total Linear System:
   number of equations =         171
   number of nonzeroes =        1099
   condensed matrix number of equations =         171
   condensed matrix number of nonzeroes =        1099
   coarse matrix neq =           1
   coarse (half) bandwidth =           0

Norms of error:
   energy norm of error       1.2036913481E+00
      reduced by              5.8164590417E-01
   energy error estimate      3.4962141610E-01
      reduced by              6.6641295220E-01
      effectivity             2.9045769637E-01
   Linf norm of error         1.0115694205E-01
      reduced by              3.9615941182E-01
   Linf error estimate        1.6603506558E-02
      reduced by              3.1201977358E-01
      effectivity             1.6413610595E-01
   L2 norm of error           2.0328331279E-02
      reduced by              3.1161488252E-01
   L2 error estimate          4.8125393184E-03
      reduced by              3.8854805000E-01
      effectivity             2.3674050035E-01

Total Grid:
   number of vertices      =         308
   number of leaf elements =         537
   number of levels        =          11
   degrees of freedom      =         308
   min and max degree      =           1          1

Total Linear System:
   number of equations =         308
   number of nonzeroes =        1996
   condensed matrix number of equations =         308
   condensed matrix number of nonzeroes =        1996
   coarse matrix neq =           1
   coarse (half) bandwidth =           0

Norms of error:
   energy norm of error       7.5894375720E-01
      reduced by              3.1525679670E-01
   energy error estimate      2.4726662838E-01
      reduced by              3.5362054066E-01
      effectivity             3.2580362647E-01
   Linf norm of error         4.0665439316E-02
      reduced by              4.0200344625E-01
   Linf error estimate        9.2018216206E-03
      reduced by              5.5420953328E-01
      effectivity             2.2628113148E-01
   L2 norm of error           9.5399389192E-03
      reduced by              2.3464638558E-01
   L2 error estimate          2.4202255319E-03
      reduced by              2.5144994895E-01
      effectivity             2.5369402807E-01

Total Grid:
   number of vertices      =         730
   number of leaf elements =        1314
   number of levels        =          12
   degrees of freedom      =         730
   min and max degree      =           1          1

Total Linear System:
   number of equations =         730
   number of nonzeroes =        4816
   condensed matrix number of equations =         730
   condensed matrix number of nonzeroes =        4816
   coarse matrix neq =           1
   coarse (half) bandwidth =           0

Norms of error:
   energy norm of error       4.6561440088E-01
      reduced by              6.1350316998E-01
   energy error estimate      1.5366745744E-01
      reduced by              6.2146460463E-01
      effectivity             3.3003158226E-01
   Linf norm of error         3.0902420799E-02
      reduced by              7.5991852832E-01
   Linf error estimate        3.4631256050E-03
      reduced by              3.7635217762E-01
      effectivity             1.1206648267E-01
   L2 norm of error           3.6450299452E-03
      reduced by              3.8208105692E-01
   L2 error estimate          1.0059043897E-03
      reduced by              4.1562423684E-01
      effectivity             2.7596601531E-01

Total Grid:
   number of vertices      =         730
   number of leaf elements =        1314
   number of levels        =          12
   degrees of freedom      =         730
   min and max degree      =           1          1

Norms of error:
   energy norm of error       4.6561440088E-01
   energy error estimate      1.5366745744E-01
      effectivity             3.3003158226E-01
   Linf norm of error         3.0902420799E-02
   Linf error estimate        3.4631256050E-03
      effectivity             1.1206648267E-01
   L2 norm of error           3.6450299452E-03
   L2 error estimate          1.0059043897E-03
      effectivity             2.7596601531E-01

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           6
termination condition:
  maximum vertices achieved
---------------------------------------------------------
