---------------------------------------------------------
           PHAML   Version 1.8.0

Output from slave number     1
  PDE id is     0
  Number of slave processors is     1

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                  500
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    FREQUENTLY
  print_grid_who     SLAVES
  print_linsys_when  FREQUENTLY
  print_linsys_who   SLAVES
  print_error_when   FREQUENTLY
  print_error_who    SLAVES
  print_error_what   LINF_L2_ERR
  print_errest_what   LINF_L2_ERREST
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ_SMOOTH
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    false
  solver             MG_SOLVER
  mg_cycles                   2
  mg_tol             MG_ERREST_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_FUDOP
---------------------------------------------------------

My Grid:
   number of vertices       =           9
   number of vertices I own =           9
   number of elements       =           8
   number of leaf elements  =           8
   leaf elements I own      =           8
   number of levels         =           1
   degrees of freedom       =           9
   degrees of freedom I own =           9
   min and max degree       =           1          1

My Linear System:
   number of equations =           9
   number of equations I own =           9
   number of nonzeroes =          41
   condensed matrix number of equations =           9
   condensed matrix number of equations I own =           9
   condensed matrix number of nonzeroes =          41
   coarse matrix neq =           1
   coarse (half) bandwidth =           0

Norms of error:
   Linf norm of error         1.0536246503E+00
   Linf error estimate        1.1645061848E+00
      effectivity             1.1052381742E+00
   L2 norm of error           4.5345860840E-01
   L2 error estimate          3.8794146656E-01
      effectivity             8.5551681976E-01

Norms of error:
   Linf norm of error         1.0536246503E+00
      reduced by              1.0000000000E+00
   Linf error estimate        1.1645061848E+00
      reduced by              1.0000000000E+00
      effectivity             1.1052381742E+00
   L2 norm of error           4.5345860840E-01
      reduced by              1.0000000000E+00
   L2 error estimate          3.8794146656E-01
      reduced by              1.0000000000E+00
      effectivity             8.5551681976E-01

My Grid:
   number of vertices       =           9
   number of vertices I own =           9
   number of elements       =           8
   number of leaf elements  =           8
   leaf elements I own      =           8
   number of levels         =           1
   degrees of freedom       =           9
   degrees of freedom I own =           9
   min and max degree       =           1          1

My Grid:
   number of vertices       =          27
   number of vertices I own =          27
   number of elements       =          68
   number of leaf elements  =          38
   leaf elements I own      =          38
   number of levels         =           4
   degrees of freedom       =          27
   degrees of freedom I own =          27
   min and max degree       =           1          1

My Linear System:
   number of equations =          27
   number of equations I own =          27
   number of nonzeroes =         155
   condensed matrix number of equations =          27
   condensed matrix number of equations I own =          27
   condensed matrix number of nonzeroes =         155
   coarse matrix neq =           1
   coarse (half) bandwidth =           0

Norms of error:
   Linf norm of error         6.7489276612E-01
      reduced by              6.4054382737E-01
   Linf error estimate        3.1966359115E-01
      reduced by              2.7450570493E-01
      effectivity             4.7365093715E-01
   L2 norm of error           1.8334069947E-01
      reduced by              4.0431628393E-01
   L2 error estimate          5.8854826900E-02
      reduced by              1.5171058516E-01
      effectivity             3.2101343057E-01

My Grid:
   number of vertices       =          27
   number of vertices I own =          27
   number of elements       =          68
   number of leaf elements  =          38
   leaf elements I own      =          38
   number of levels         =           4
   degrees of freedom       =          27
   degrees of freedom I own =          27
   min and max degree       =           1          1

My Grid:
   number of vertices       =          36
   number of vertices I own =          36
   number of elements       =          88
   number of leaf elements  =          48
   leaf elements I own      =          48
   number of levels         =           6
   degrees of freedom       =          36
   degrees of freedom I own =          36
   min and max degree       =           1          1

My Linear System:
   number of equations =          36
   number of equations I own =          36
   number of nonzeroes =         202
   condensed matrix number of equations =          36
   condensed matrix number of equations I own =          36
   condensed matrix number of nonzeroes =         202
   coarse matrix neq =           1
   coarse (half) bandwidth =           0

Norms of error:
   Linf norm of error         4.7530105786E-01
      reduced by              7.0426159787E-01
   Linf error estimate        1.3917147125E-01
      reduced by              4.3536854087E-01
      effectivity             2.9280698821E-01
   L2 norm of error           1.6071015387E-01
      reduced by              8.7656561985E-01
   L2 error estimate          3.5587864849E-02
      reduced by              6.0467198230E-01
      effectivity             2.2144129659E-01

My Grid:
   number of vertices       =          36
   number of vertices I own =          36
   number of elements       =          88
   number of leaf elements  =          48
   leaf elements I own      =          48
   number of levels         =           6
   degrees of freedom       =          36
   degrees of freedom I own =          36
   min and max degree       =           1          1

My Grid:
   number of vertices       =          75
   number of vertices I own =          75
   number of elements       =         208
   number of leaf elements  =         108
   leaf elements I own      =         108
   number of levels         =           8
   degrees of freedom       =          75
   degrees of freedom I own =          75
   min and max degree       =           1          1

My Linear System:
   number of equations =          75
   number of equations I own =          75
   number of nonzeroes =         439
   condensed matrix number of equations =          75
   condensed matrix number of equations I own =          75
   condensed matrix number of nonzeroes =         439
   coarse matrix neq =           1
   coarse (half) bandwidth =           0

Norms of error:
   Linf norm of error         2.5534403332E-01
      reduced by              5.3722588893E-01
   Linf error estimate        5.3212994702E-02
      reduced by              3.8235562379E-01
      effectivity             2.0839725139E-01
   L2 norm of error           6.5235431360E-02
      reduced by              4.0591978657E-01
   L2 error estimate          1.2385956688E-02
      reduced by              3.4803876940E-01
      effectivity             1.8986548306E-01

My Grid:
   number of vertices       =          75
   number of vertices I own =          75
   number of elements       =         208
   number of leaf elements  =         108
   leaf elements I own      =         108
   number of levels         =           8
   degrees of freedom       =          75
   degrees of freedom I own =          75
   min and max degree       =           1          1

My Grid:
   number of vertices       =         171
   number of vertices I own =         171
   number of elements       =         580
   number of leaf elements  =         294
   leaf elements I own      =         294
   number of levels         =           9
   degrees of freedom       =         171
   degrees of freedom I own =         171
   min and max degree       =           1          1

My Linear System:
   number of equations =         171
   number of equations I own =         171
   number of nonzeroes =        1099
   condensed matrix number of equations =         171
   condensed matrix number of equations I own =         171
   condensed matrix number of nonzeroes =        1099
   coarse matrix neq =           1
   coarse (half) bandwidth =           0

Norms of error:
   Linf norm of error         1.0115694205E-01
      reduced by              3.9615941182E-01
   Linf error estimate        1.6603506558E-02
      reduced by              3.1201977358E-01
      effectivity             1.6413610595E-01
   L2 norm of error           2.0328331279E-02
      reduced by              3.1161488252E-01
   L2 error estimate          4.8125393184E-03
      reduced by              3.8854805000E-01
      effectivity             2.3674050035E-01

My Grid:
   number of vertices       =         171
   number of vertices I own =         171
   number of elements       =         580
   number of leaf elements  =         294
   leaf elements I own      =         294
   number of levels         =           9
   degrees of freedom       =         171
   degrees of freedom I own =         171
   min and max degree       =           1          1

My Grid:
   number of vertices       =         290
   number of vertices I own =         290
   number of elements       =         996
   number of leaf elements  =         502
   leaf elements I own      =         502
   number of levels         =          10
   degrees of freedom       =         290
   degrees of freedom I own =         290
   min and max degree       =           1          1

My Linear System:
   number of equations =         290
   number of equations I own =         290
   number of nonzeroes =        1872
   condensed matrix number of equations =         290
   condensed matrix number of equations I own =         290
   condensed matrix number of nonzeroes =        1872
   coarse matrix neq =           1
   coarse (half) bandwidth =           0

Norms of error:
   Linf norm of error         4.0783593768E-02
      reduced by              4.0317147732E-01
   Linf error estimate        9.1980984379E-03
      reduced by              5.5398529254E-01
      effectivity             2.2553427955E-01
   L2 norm of error           9.7803045443E-03
      reduced by              4.8111694019E-01
   L2 error estimate          2.5305422783E-03
      reduced by              5.2582267092E-01
      effectivity             2.5873859723E-01

My Grid:
   number of vertices       =         290
   number of vertices I own =         290
   number of elements       =         996
   number of leaf elements  =         502
   leaf elements I own      =         502
   number of levels         =          10
   degrees of freedom       =         290
   degrees of freedom I own =         290
   min and max degree       =           1          1

My Grid:
   number of vertices       =         730
   number of vertices I own =         730
   number of elements       =        2620
   number of leaf elements  =        1314
   leaf elements I own      =        1314
   number of levels         =          12
   degrees of freedom       =         730
   degrees of freedom I own =         730
   min and max degree       =           1          1

My Linear System:
   number of equations =         730
   number of equations I own =         730
   number of nonzeroes =        4816
   condensed matrix number of equations =         730
   condensed matrix number of equations I own =         730
   condensed matrix number of nonzeroes =        4816
   coarse matrix neq =           1
   coarse (half) bandwidth =           0

Norms of error:
   Linf norm of error         3.0902409588E-02
      reduced by              7.5771668784E-01
   Linf error estimate        3.4632593427E-03
      reduced by              3.7651905621E-01
      effectivity             1.1207085107E-01
   L2 norm of error           3.6310420078E-03
      reduced by              3.7126062807E-01
   L2 error estimate          1.0059228191E-03
      reduced by              3.9751274963E-01
      effectivity             2.7703420036E-01

My Grid:
   number of vertices       =         730
   number of vertices I own =         730
   number of elements       =        2620
   number of leaf elements  =        1314
   leaf elements I own      =        1314
   number of levels         =          12
   degrees of freedom       =         730
   degrees of freedom I own =         730
   min and max degree       =           1          1

Norms of error:
   Linf norm of error         3.0902409588E-02
   Linf error estimate        3.4632593427E-03
      effectivity             1.1207085107E-01
   L2 norm of error           3.6310420078E-03
   L2 error estimate          1.0059228191E-03
      effectivity             2.7703420036E-01

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           6
termination condition:
  maximum vertices achieved
---------------------------------------------------------
