---------------------------------------------------------
           PHAML   Version 1.8.0

Output from slave number     1
  PDE id is     0
  Number of slave processors is     1

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                  500
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    PHASES
  print_grid_who     SLAVES
  print_linsys_when  PHASES
  print_linsys_who   SLAVES
  print_error_when   TOO_MUCH
  print_error_who    SLAVES
  print_error_what   ENERGY_ERR
  print_errest_what  ENERGY_ERREST
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ_SMOOTH
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    false
  solver             MG_SOLVER
  mg_cycles                   2
  mg_tol             MG_ERREST_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_FUDOP
---------------------------------------------------------

My Grid:
   number of vertices       =           9
   number of vertices I own =           9
   number of elements       =           8
   number of leaf elements  =           8
   leaf elements I own      =           8
   number of levels         =           1
   degrees of freedom       =           9
   degrees of freedom I own =           9
   min and max degree       =           1          1

My Linear System:
   number of equations =           9
   number of equations I own =           9
   number of nonzeroes =          41
   condensed matrix number of equations =           9
   condensed matrix number of equations I own =           9
   condensed matrix number of nonzeroes =          41
   coarse matrix neq =           1
   coarse (half) bandwidth =           0

Norms of error:
   energy norm of error       3.8589726446E+00
   energy error estimate      2.7431604171E+00
      effectivity             7.1085251689E-01

Norms of error:
   energy norm of error       3.8589726446E+00
      reduced by              1.0000000000E+00
   energy error estimate      2.7431604171E+00
      reduced by              1.0000000000E+00
      effectivity             7.1085251689E-01

My Grid:
   number of vertices       =          27
   number of vertices I own =          27
   number of elements       =          68
   number of leaf elements  =          38
   leaf elements I own      =          38
   number of levels         =           4
   degrees of freedom       =          27
   degrees of freedom I own =          27
   min and max degree       =           1          1

My Linear System:
   number of equations =          27
   number of equations I own =          27
   number of nonzeroes =         155
   condensed matrix number of equations =          27
   condensed matrix number of equations I own =          27
   condensed matrix number of nonzeroes =         155
   coarse matrix neq =           1
   coarse (half) bandwidth =           0

Norms of error:
   energy norm of error       2.9445325982E+00
      reduced by              7.6303536442E-01
   energy error estimate      1.1756831885E+00
      reduced by              4.2858710748E-01
      effectivity             3.9927667611E-01

My Grid:
   number of vertices       =          36
   number of vertices I own =          36
   number of elements       =          88
   number of leaf elements  =          48
   leaf elements I own      =          48
   number of levels         =           6
   degrees of freedom       =          36
   degrees of freedom I own =          36
   min and max degree       =           1          1

My Linear System:
   number of equations =          36
   number of equations I own =          36
   number of nonzeroes =         202
   condensed matrix number of equations =          36
   condensed matrix number of equations I own =          36
   condensed matrix number of nonzeroes =         202
   coarse matrix neq =           1
   coarse (half) bandwidth =           0

Norms of error:
   energy norm of error       2.9224776076E+00
      reduced by              9.9250985007E-01
   energy error estimate      8.7511040785E-01
      reduced by              7.4434202717E-01
      effectivity             2.9944127051E-01

My Grid:
   number of vertices       =          75
   number of vertices I own =          75
   number of elements       =         208
   number of leaf elements  =         108
   leaf elements I own      =         108
   number of levels         =           8
   degrees of freedom       =          75
   degrees of freedom I own =          75
   min and max degree       =           1          1

My Linear System:
   number of equations =          75
   number of equations I own =          75
   number of nonzeroes =         439
   condensed matrix number of equations =          75
   condensed matrix number of equations I own =          75
   condensed matrix number of nonzeroes =         439
   coarse matrix neq =           1
   coarse (half) bandwidth =           0

Norms of error:
   energy norm of error       2.0694628300E+00
      reduced by              7.0811931104E-01
   energy error estimate      5.2471032703E-01
      reduced by              5.9959328826E-01
      effectivity             2.5354904637E-01

My Grid:
   number of vertices       =         171
   number of vertices I own =         171
   number of elements       =         580
   number of leaf elements  =         294
   leaf elements I own      =         294
   number of levels         =           9
   degrees of freedom       =         171
   degrees of freedom I own =         171
   min and max degree       =           1          1

My Linear System:
   number of equations =         171
   number of equations I own =         171
   number of nonzeroes =        1099
   condensed matrix number of equations =         171
   condensed matrix number of equations I own =         171
   condensed matrix number of nonzeroes =        1099
   coarse matrix neq =           1
   coarse (half) bandwidth =           0

Norms of error:
   energy norm of error       1.2037153855E+00
      reduced by              5.8165595828E-01
   energy error estimate      3.4981331996E-01
      reduced by              6.6667893109E-01
      effectivity             2.9061132239E-01

My Grid:
   number of vertices       =         290
   number of vertices I own =         290
   number of elements       =         996
   number of leaf elements  =         502
   leaf elements I own      =         502
   number of levels         =          10
   degrees of freedom       =         290
   degrees of freedom I own =         290
   min and max degree       =           1          1

My Linear System:
   number of equations =         290
   number of equations I own =         290
   number of nonzeroes =        1872
   condensed matrix number of equations =         290
   condensed matrix number of equations I own =         290
   condensed matrix number of nonzeroes =        1872
   coarse matrix neq =           1
   coarse (half) bandwidth =           0

Norms of error:
   energy norm of error       7.7570668043E-01
      reduced by              6.4442698812E-01
   energy error estimate      2.5777800043E-01
      reduced by              7.3690161502E-01
      effectivity             3.3231375587E-01

My Grid:
   number of vertices       =         730
   number of vertices I own =         730
   number of elements       =        2620
   number of leaf elements  =        1314
   leaf elements I own      =        1314
   number of levels         =          12
   degrees of freedom       =         730
   degrees of freedom I own =         730
   min and max degree       =           1          1

My Linear System:
   number of equations =         730
   number of equations I own =         730
   number of nonzeroes =        4816
   condensed matrix number of equations =         730
   condensed matrix number of equations I own =         730
   condensed matrix number of nonzeroes =        4816
   coarse matrix neq =           1
   coarse (half) bandwidth =           0

Norms of error:
   energy norm of error       4.6988499676E-01
      reduced by              6.0575087029E-01
   energy error estimate      1.5607959726E-01
      reduced by              6.0548067330E-01
      effectivity             3.3216552633E-01

My Grid:
   number of vertices       =         730
   number of vertices I own =         730
   number of elements       =        2620
   number of leaf elements  =        1314
   leaf elements I own      =        1314
   number of levels         =          12
   degrees of freedom       =         730
   degrees of freedom I own =         730
   min and max degree       =           1          1

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           6
termination condition:
  maximum vertices achieved
---------------------------------------------------------
