
Total Grid:
   number of vertices      =         655
   number of leaf elements =        1257
   number of levels        =          14
   degrees of freedom      =         655
   min and max degree      =           1          1

Norms of error:
   energy error estimate      1.5712816210E-02
   Linf error estimate        9.3811881753E-04
time =  1.000000000000E-02

Total Grid:
   number of vertices      =         659
   number of leaf elements =        1264
   number of levels        =          14
   degrees of freedom      =         659
   min and max degree      =           1          1

Norms of error:
   energy error estimate      1.6734486975E-02
   Linf error estimate        9.6188421333E-04
time =  2.000000000000E-02

Total Grid:
   number of vertices      =         657
   number of leaf elements =        1257
   number of levels        =          14
   degrees of freedom      =         657
   min and max degree      =           1          1

Norms of error:
   energy error estimate      1.7248884042E-02
   Linf error estimate        1.1857780409E-03
time =  3.000000000000E-02

Total Grid:
   number of vertices      =         656
   number of leaf elements =        1253
   number of levels        =          15
   degrees of freedom      =         656
   min and max degree      =           1          1

Norms of error:
   energy error estimate      1.7701115491E-02
   Linf error estimate        1.5997084337E-03
time =  4.000000000000E-02

Total Grid:
   number of vertices      =         655
   number of leaf elements =        1249
   number of levels        =          15
   degrees of freedom      =         655
   min and max degree      =           1          1

Norms of error:
   energy error estimate      1.7561895071E-02
   Linf error estimate        1.1637407582E-03
time =  5.000000000000E-02
