---------------------------------------------------------
           PHAML   Version 1.8.0

Output from the master process
  PDE id is     0
  Number of slave processors is     4

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert           infinity
  max_eq                    500
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    PHASES
  print_grid_who     MASTER
  print_linsys_when  NEVER
  print_error_when   PHASES
  print_error_who    MASTER
  print_error_what   ENERGY_LINF_L2_ERR
  print_errest_what  ENERGY_LINF_L2_ERREST
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    LOCAL_PROBLEM_H
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ_SMOOTH
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    false
  solver             MG_SOLVER
  mg_cycles                   2
  mg_tol             MG_ERREST_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_FUDOP
---------------------------------------------------------

Total Grid:
   number of vertices      =           9
   number of leaf elements =           8
   number of levels        =           1
   degrees of freedom      =           9
   min and max degree      =           1          1

Norms of error:
   energy norm of error       3.8589726446E+00
   energy error estimate      2.2483194801E+00
      effectivity             5.8262125366E-01
   Linf norm of error         1.0536246503E+00
   Linf error estimate        6.8623959248E-01
      effectivity             6.5131315244E-01
   L2 norm of error           4.5345860840E-01
   L2 error estimate          3.9745048765E-01
      effectivity             8.7648680671E-01

Total Grid:
   number of vertices      =          36
   number of leaf elements =          52
   number of levels        =           6
   degrees of freedom      =          36
   min and max degree      =           1          1

Norms of error:
   energy norm of error       2.5606835450E+00
      reduced by              6.6356613037E-01
   energy error estimate      1.6059393613E+00
      reduced by              7.1428432459E-01
      effectivity             6.2715260712E-01
   Linf norm of error         4.4165866724E-01
      reduced by              4.1918027175E-01
   Linf error estimate        2.7776537084E-01
      reduced by              4.0476442030E-01
      effectivity             6.2891411727E-01
   L2 norm of error           1.1147975597E-01
      reduced by              2.4584328957E-01
   L2 error estimate          8.6154851263E-02
      reduced by              2.1676876476E-01
      effectivity             7.7282956452E-01

Total Grid:
   number of vertices      =          38
   number of leaf elements =          56
   number of levels        =           6
   degrees of freedom      =          38
   min and max degree      =           1          1

Norms of error:
   energy norm of error       2.3959767314E+00
      reduced by              9.3567857539E-01
   energy error estimate      1.3162664597E+00
      reduced by              8.1962401040E-01
      effectivity             5.4936529327E-01
   Linf norm of error         3.2889082818E-01
      reduced by              7.4467196634E-01
   Linf error estimate        2.5954558950E-01
      reduced by              9.3440585742E-01
      effectivity             7.8915423375E-01
   L2 norm of error           9.0434169068E-02
      reduced by              8.1121606588E-01
   L2 error estimate          5.7782744804E-02
      reduced by              6.7068474912E-01
      effectivity             6.3894814759E-01

Total Grid:
   number of vertices      =          75
   number of leaf elements =         120
   number of levels        =           8
   degrees of freedom      =          75
   min and max degree      =           1          1

Norms of error:
   energy norm of error       1.5026738555E+00
      reduced by              6.2716546276E-01
   energy error estimate      9.2385789997E-01
      reduced by              7.0187756676E-01
      effectivity             6.1480932576E-01
   Linf norm of error         2.3826017814E-01
      reduced by              7.2443545920E-01
   Linf error estimate        1.6167536530E-01
      reduced by              6.2291702053E-01
      effectivity             6.7856645859E-01
   L2 norm of error           3.4863153261E-02
      reduced by              3.8550863707E-01
   L2 error estimate          2.5246421492E-02
      reduced by              4.3691973404E-01
      effectivity             7.2415771754E-01

Total Grid:
   number of vertices      =         156
   number of leaf elements =         264
   number of levels        =          10
   degrees of freedom      =         156
   min and max degree      =           1          1

Norms of error:
   energy norm of error       8.2577622940E-01
      reduced by              5.4953789630E-01
   energy error estimate      4.3494816067E-01
      reduced by              4.7079552026E-01
      effectivity             5.2671431458E-01
   Linf norm of error         5.4102663633E-02
      reduced by              2.2707388224E-01
   Linf error estimate        3.5161786351E-02
      reduced by              2.1748388374E-01
      effectivity             6.4990859950E-01
   L2 norm of error           1.3102491607E-02
      reduced by              3.7582634905E-01
   L2 error estimate          8.5324279381E-03
      reduced by              3.3796583570E-01
      effectivity             6.5120651814E-01

Total Grid:
   number of vertices      =         349
   number of leaf elements =         614
   number of levels        =          11
   degrees of freedom      =         349
   min and max degree      =           1          1

Norms of error:
   energy norm of error       6.5944466649E-01
      reduced by              3.9928775073E-01
   energy error estimate      4.2932992123E-01
      reduced by              4.9354148386E-01
      effectivity             6.5104768155E-01
   Linf norm of error         4.1635828273E-02
      reduced by              7.6957076561E-01
   Linf error estimate        3.2909000115E-02
      reduced by              9.3593083659E-01
      effectivity             7.9040099549E-01
   L2 norm of error           7.6920649690E-03
      reduced by              2.9353443604E-01
   L2 error estimate          6.2834715500E-03
      reduced by              3.6821122871E-01
      effectivity             8.1687707726E-01

Total Grid:
   number of vertices      =         574
   number of leaf elements =        1058
   number of levels        =          12
   degrees of freedom      =         574
   min and max degree      =           1          1

Norms of error:
   energy norm of error       4.5791270453E-01
      reduced by              6.9439139901E-01
   energy error estimate      2.5675699175E-01
      reduced by              5.9804122436E-01
      effectivity             5.6071165793E-01
   Linf norm of error         2.7471714955E-02
      reduced by              6.5980949808E-01
   Linf error estimate        1.2378911470E-02
      reduced by              3.7615580621E-01
      effectivity             4.5060570445E-01
   L2 norm of error           3.9661052702E-03
      reduced by              5.1560995470E-01
   L2 error estimate          2.6517436306E-03
      reduced by              4.2201888073E-01
      effectivity             6.6860142381E-01

Total Grid:
   number of vertices      =         574
   number of leaf elements =        1058
   number of levels        =          12
   degrees of freedom      =         574
   min and max degree      =           1          1

Norms of error:
   energy norm of error       4.5791270453E-01
   energy error estimate      2.5675699175E-01
      effectivity             5.6071165793E-01
   Linf norm of error         2.7471714955E-02
   Linf error estimate        1.2378911470E-02
      effectivity             4.5060570445E-01
   L2 norm of error           3.9661052702E-03
   L2 error estimate          2.6517436306E-03
      effectivity             6.6860142381E-01

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           6
termination condition:
  maximum equations achieved
---------------------------------------------------------
