---------------------------------------------------------
           PHAML   Version 1.8.0

Output from the master process
  PDE id is     0
  Number of slave processors is     4

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert           infinity
  max_eq                    500
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    21
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    PHASES
  print_grid_who     MASTER
  print_linsys_when  NEVER
  print_error_when   PHASES
  print_error_who    MASTER
  print_error_what   ENERGY_LINF_L2_ERR
  print_errest_what  ENERGY_LINF_L2_ERREST
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    LOCAL_PROBLEM_P
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ_SMOOTH
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    false
  solver             MG_SOLVER
  mg_cycles                   2
  mg_tol             MG_ERREST_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_FUDOP
---------------------------------------------------------

Total Grid:
   number of vertices      =           9
   number of leaf elements =           8
   number of levels        =           1
   degrees of freedom      =           9
   min and max degree      =           1          1

Norms of error:
   energy norm of error       3.8589726446E+00
   energy error estimate      5.3069652709E+00
      effectivity             1.3752274918E+00
   Linf norm of error         1.0536246503E+00
   Linf error estimate        1.4604995752E+00
      effectivity             1.3861668620E+00
   L2 norm of error           4.5345860840E-01
   L2 error estimate          1.0196667538E+00
      effectivity             2.2486435033E+00

Total Grid:
   number of vertices      =          27
   number of leaf elements =          36
   number of levels        =           5
   degrees of freedom      =          27
   min and max degree      =           1          1

Norms of error:
   energy norm of error       3.1276250369E+00
      reduced by              8.1048126662E-01
   energy error estimate      3.8617689268E+00
      reduced by              7.2767932890E-01
      effectivity             1.2347288698E+00
   Linf norm of error         5.2603635394E-01
      reduced by              4.9926352216E-01
   Linf error estimate        6.4256899897E-01
      reduced by              4.3996520771E-01
      effectivity             1.2215296417E+00
   L2 norm of error           1.7937776274E-01
      reduced by              3.9557692679E-01
   L2 error estimate          3.1846909201E-01
      reduced by              3.1232664085E-01
      effectivity             1.7754101018E+00

Total Grid:
   number of vertices      =          40
   number of leaf elements =          56
   number of levels        =           6
   degrees of freedom      =          40
   min and max degree      =           1          1

Norms of error:
   energy norm of error       2.7567092086E+00
      reduced by              8.8140655486E-01
   energy error estimate      3.5536136454E+00
      reduced by              9.2020359394E-01
      effectivity             1.2890781640E+00
   Linf norm of error         4.7526983627E-01
      reduced by              9.0349237786E-01
   Linf error estimate        5.8677776369E-01
      reduced by              9.1317471685E-01
      effectivity             1.2346202492E+00
   L2 norm of error           1.4349455674E-01
      reduced by              7.9995733336E-01
   L2 error estimate          2.2732707548E-01
      reduced by              7.1381205017E-01
      effectivity             1.5842208976E+00

Total Grid:
   number of vertices      =         121
   number of leaf elements =         200
   number of levels        =           9
   degrees of freedom      =         121
   min and max degree      =           1          1

Norms of error:
   energy norm of error       1.4284883160E+00
      reduced by              5.1818607181E-01
   energy error estimate      2.7405100836E+00
      reduced by              7.7118965566E-01
      effectivity             1.9184686728E+00
   Linf norm of error         2.5178260370E-01
      reduced by              5.2976769087E-01
   Linf error estimate        2.8767566343E-01
      reduced by              4.9026340333E-01
      effectivity             1.1425557572E+00
   L2 norm of error           3.2320097126E-02
      reduced by              2.2523570133E-01
   L2 error estimate          9.8092262744E-02
      reduced by              4.3150276990E-01
      effectivity             3.0350237613E+00

Total Grid:
   number of vertices      =         165
   number of leaf elements =         285
   number of levels        =          10
   degrees of freedom      =         165
   min and max degree      =           1          1

Norms of error:
   energy norm of error       1.1988785602E+00
      reduced by              4.1963190975E-01
   energy error estimate      2.3141760289E+00
      reduced by              4.2221629521E-01
      effectivity             1.9302839385E+00
   Linf norm of error         1.1104994071E-01
      reduced by              4.4105485874E-01
   Linf error estimate        2.2083436553E-01
      reduced by              7.6765049535E-01
      effectivity             1.9886040832E+00
   L2 norm of error           2.1047592860E-02
      reduced by              3.2561153480E-01
   L2 error estimate          7.4432684426E-02
      reduced by              3.7940140406E-01
      effectivity             3.5363989089E+00

Total Grid:
   number of vertices      =         350
   number of leaf elements =         635
   number of levels        =          11
   degrees of freedom      =         350
   min and max degree      =           1          1

Norms of error:
   energy norm of error       7.3957871156E-01
      reduced by              6.1689209911E-01
   energy error estimate      1.6542172861E+00
      reduced by              7.1481912585E-01
      effectivity             2.2367021389E+00
   Linf norm of error         9.7708507898E-02
      reduced by              8.7986096413E-01
   Linf error estimate        1.0845048506E-01
      reduced by              4.9109424070E-01
      effectivity             1.1099390155E+00
   L2 norm of error           9.6322465582E-03
      reduced by              4.5764124297E-01
   L2 error estimate          3.1356043130E-02
      reduced by              4.2126712710E-01
      effectivity             3.2553198198E+00

Total Grid:
   number of vertices      =         580
   number of leaf elements =        1077
   number of levels        =          12
   degrees of freedom      =         580
   min and max degree      =           1          1

Norms of error:
   energy norm of error       6.3568593299E-01
      reduced by              8.5952437929E-01
   energy error estimate      1.2719090710E+00
      reduced by              7.6888875584E-01
      effectivity             2.0008450792E+00
   Linf norm of error         3.1300036097E-02
      reduced by              3.2034094850E-01
   Linf error estimate        8.0430192003E-02
      reduced by              7.4163054188E-01
      effectivity             2.5696517331E+00
   L2 norm of error           7.0316572121E-03
      reduced by              7.3001217002E-01
   L2 error estimate          2.1292608231E-02
      reduced by              6.7905915751E-01
      effectivity             3.0281066879E+00

Total Grid:
   number of vertices      =         580
   number of leaf elements =        1077
   number of levels        =          12
   degrees of freedom      =         580
   min and max degree      =           1          1

Norms of error:
   energy norm of error       6.3568593299E-01
   energy error estimate      1.2719090710E+00
      effectivity             2.0008450792E+00
   Linf norm of error         3.1300036097E-02
   Linf error estimate        8.0430192003E-02
      effectivity             2.5696517331E+00
   L2 norm of error           7.0316572121E-03
   L2 error estimate          2.1292608231E-02
      effectivity             3.0281066879E+00

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           6
termination condition:
  maximum equations achieved
---------------------------------------------------------
