---------------------------------------------------------
           PHAML   Version 1.6.2

Output from slave number     1
  PDE id is     0
  Number of slave processors is     1

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert           infinity
  max_eq                    500
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    PHASES
  print_grid_who     SLAVES
  print_linsys_when  NEVER
  print_error_when   NEVER
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NELEM_SMOOTH
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    false
  solver             MG_SOLVER
  mg_cycles                   2
  mg_tol             MG_ERREST_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_FUDOP
---------------------------------------------------------

My Grid:
   number of vertices       =           9
   number of vertices I own =           9
   number of elements       =           8
   number of leaf elements  =           8
   leaf elements I own      =           8
   number of levels         =           1
   degrees of freedom       =           9
   degrees of freedom I own =           9
   min and max degree       =           1          1

My Grid:
   number of vertices       =          16
   number of vertices I own =          16
   number of elements       =          28
   number of leaf elements  =          18
   leaf elements I own      =          18
   number of levels         =           3
   degrees of freedom       =          16
   degrees of freedom I own =          16
   min and max degree       =           1          1

My Grid:
   number of vertices       =          27
   number of vertices I own =          27
   number of elements       =          68
   number of leaf elements  =          38
   leaf elements I own      =          38
   number of levels         =           4
   degrees of freedom       =          27
   degrees of freedom I own =          27
   min and max degree       =           1          1

My Grid:
   number of vertices       =          60
   number of vertices I own =          60
   number of elements       =         176
   number of leaf elements  =          92
   leaf elements I own      =          92
   number of levels         =           7
   degrees of freedom       =          60
   degrees of freedom I own =          60
   min and max degree       =           1          1

My Grid:
   number of vertices       =          91
   number of vertices I own =          91
   number of elements       =         272
   number of leaf elements  =         140
   leaf elements I own      =         140
   number of levels         =           8
   degrees of freedom       =          91
   degrees of freedom I own =          91
   min and max degree       =           1          1

My Grid:
   number of vertices       =         226
   number of vertices I own =         226
   number of elements       =         744
   number of leaf elements  =         376
   leaf elements I own      =         376
   number of levels         =          10
   degrees of freedom       =         226
   degrees of freedom I own =         226
   min and max degree       =           1          1

My Grid:
   number of vertices       =         295
   number of vertices I own =         295
   number of elements       =        1016
   number of leaf elements  =         512
   leaf elements I own      =         512
   number of levels         =          10
   degrees of freedom       =         295
   degrees of freedom I own =         295
   min and max degree       =           1          1

My Grid:
   number of vertices       =         732
   number of vertices I own =         732
   number of elements       =        2628
   number of leaf elements  =        1318
   leaf elements I own      =        1318
   number of levels         =          12
   degrees of freedom       =         732
   degrees of freedom I own =         732
   min and max degree       =           1          1

My Grid:
   number of vertices       =         732
   number of vertices I own =         732
   number of elements       =        2628
   number of leaf elements  =        1318
   leaf elements I own      =        1318
   number of levels         =          12
   degrees of freedom       =         732
   degrees of freedom I own =         732
   min and max degree       =           1          1

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           7
termination condition:
  maximum equations achieved
---------------------------------------------------------
