---------------------------------------------------------
           PHAML   Version 1.8.0

Output from slave number     1
  PDE id is     0
  Number of slave processors is     1

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert           infinity
  max_eq                    500
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    PHASES
  print_grid_who     SLAVES
  print_linsys_when  NEVER
  print_error_when   NEVER
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            HALVE_ERREST
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    false
  solver             MG_SOLVER
  mg_cycles                   2
  mg_tol             MG_ERREST_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_FUDOP
---------------------------------------------------------

My Grid:
   number of vertices       =           9
   number of vertices I own =           9
   number of elements       =           8
   number of leaf elements  =           8
   leaf elements I own      =           8
   number of levels         =           1
   degrees of freedom       =           9
   degrees of freedom I own =           9
   min and max degree       =           1          1

My Grid:
   number of vertices       =          17
   number of vertices I own =          17
   number of elements       =          32
   number of leaf elements  =          20
   leaf elements I own      =          20
   number of levels         =           4
   degrees of freedom       =          17
   degrees of freedom I own =          17
   min and max degree       =           1          1

My Grid:
   number of vertices       =          38
   number of vertices I own =          38
   number of elements       =          96
   number of leaf elements  =          52
   leaf elements I own      =          52
   number of levels         =           6
   degrees of freedom       =          38
   degrees of freedom I own =          38
   min and max degree       =           1          1

My Grid:
   number of vertices       =          76
   number of vertices I own =          76
   number of elements       =         212
   number of leaf elements  =         110
   leaf elements I own      =         110
   number of levels         =           8
   degrees of freedom       =          76
   degrees of freedom I own =          76
   min and max degree       =           1          1

My Grid:
   number of vertices       =         124
   number of vertices I own =         124
   number of elements       =         396
   number of leaf elements  =         202
   leaf elements I own      =         202
   number of levels         =           9
   degrees of freedom       =         124
   degrees of freedom I own =         124
   min and max degree       =           1          1

My Grid:
   number of vertices       =         291
   number of vertices I own =         291
   number of elements       =        1000
   number of leaf elements  =         504
   leaf elements I own      =         504
   number of levels         =          10
   degrees of freedom       =         291
   degrees of freedom I own =         291
   min and max degree       =           1          1

My Grid:
   number of vertices       =         490
   number of vertices I own =         490
   number of elements       =        1780
   number of leaf elements  =         894
   leaf elements I own      =         894
   number of levels         =          11
   degrees of freedom       =         490
   degrees of freedom I own =         490
   min and max degree       =           1          1

My Grid:
   number of vertices       =         985
   number of vertices I own =         985
   number of elements       =        3636
   number of leaf elements  =        1822
   leaf elements I own      =        1822
   number of levels         =          12
   degrees of freedom       =         985
   degrees of freedom I own =         985
   min and max degree       =           1          1

My Grid:
   number of vertices       =         985
   number of vertices I own =         985
   number of elements       =        3636
   number of leaf elements  =        1822
   leaf elements I own      =        1822
   number of levels         =          12
   degrees of freedom       =         985
   degrees of freedom I own =         985
   min and max degree       =           1          1

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           7
termination condition:
  maximum equations achieved
---------------------------------------------------------
