---------------------------------------------------------
           PHAML   Version 1.8.0

Output from slave number     1
  PDE id is     0
  Number of slave processors is     1

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert           infinity
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop            3
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    FINAL
  print_grid_who     SLAVES
  print_linsys_when  NEVER
  print_error_when   NEVER
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ_SMOOTH
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    false
  solver             MG_SOLVER
  mg_cycles          infinity
  mg_tol             MG_ERREST_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_FUDOP
---------------------------------------------------------

My Grid:
   number of vertices       =          75
   number of vertices I own =          75
   number of elements       =         208
   number of leaf elements  =         108
   leaf elements I own      =         108
   number of levels         =           8
   degrees of freedom       =          75
   degrees of freedom I own =          75
   min and max degree       =           1          1

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           3
termination condition:
  maximum loops through phases achieved
---------------------------------------------------------
---------------------------------------------------------
           PHAML   Version 1.8.0

Output from slave number     1
  PDE id is     0
  Number of slave processors is     1

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert           infinity
  max_eq                   5000
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    21
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    PHASES
  print_grid_who     SLAVES
  print_linsys_when  NEVER
  print_error_when   NEVER
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    LOCAL_PROBLEM_P
  errtype            ABSOLUTE_ERROR
  reftype            P_ADAPTIVE
  edge_rule          MAXIMUM_RULE
  refterm            DOUBLE_NEQ_SMOOTH
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    false
  solver             MG_SOLVER
  mg_cycles          infinity
  mg_tol             MG_ERREST_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_FUDOP
---------------------------------------------------------

My Grid:
   number of vertices       =          75
   number of vertices I own =          75
   number of elements       =         208
   number of leaf elements  =         108
   leaf elements I own      =         108
   number of levels         =           8
   degrees of freedom       =          75
   degrees of freedom I own =          75
   min and max degree       =           1          1

My Grid:
   number of vertices       =          75
   number of vertices I own =          75
   number of elements       =         208
   number of leaf elements  =         108
   leaf elements I own      =         108
   number of levels         =           8
   degrees of freedom       =         167
   degrees of freedom I own =         167
   min and max degree       =           1          2

My Grid:
   number of vertices       =          75
   number of vertices I own =          75
   number of elements       =         208
   number of leaf elements  =         108
   leaf elements I own      =         108
   number of levels         =           8
   degrees of freedom       =         259
   degrees of freedom I own =         259
   min and max degree       =           1          3

My Grid:
   number of vertices       =          75
   number of vertices I own =          75
   number of elements       =         208
   number of leaf elements  =         108
   leaf elements I own      =         108
   number of levels         =           8
   degrees of freedom       =         572
   degrees of freedom I own =         572
   min and max degree       =           1          4

My Grid:
   number of vertices       =          75
   number of vertices I own =          75
   number of elements       =         208
   number of leaf elements  =         108
   leaf elements I own      =         108
   number of levels         =           8
   degrees of freedom       =         905
   degrees of freedom I own =         905
   min and max degree       =           2          4

My Grid:
   number of vertices       =          75
   number of vertices I own =          75
   number of elements       =         208
   number of leaf elements  =         108
   leaf elements I own      =         108
   number of levels         =           8
   degrees of freedom       =        1563
   degrees of freedom I own =        1563
   min and max degree       =           3          6

My Grid:
   number of vertices       =          75
   number of vertices I own =          75
   number of elements       =         208
   number of leaf elements  =         108
   leaf elements I own      =         108
   number of levels         =           8
   degrees of freedom       =        2249
   degrees of freedom I own =        2249
   min and max degree       =           4          9

My Grid:
   number of vertices       =          75
   number of vertices I own =          75
   number of elements       =         208
   number of leaf elements  =         108
   leaf elements I own      =         108
   number of levels         =           8
   degrees of freedom       =        4057
   degrees of freedom I own =        4057
   min and max degree       =           6         11

My Grid:
   number of vertices       =          75
   number of vertices I own =          75
   number of elements       =         208
   number of leaf elements  =         108
   leaf elements I own      =         108
   number of levels         =           8
   degrees of freedom       =        4814
   degrees of freedom I own =        4814
   min and max degree       =           7         12

My Grid:
   number of vertices       =          75
   number of vertices I own =          75
   number of elements       =         208
   number of leaf elements  =         108
   leaf elements I own      =         108
   number of levels         =           8
   degrees of freedom       =        5019
   degrees of freedom I own =        5019
   min and max degree       =           7         14

My Grid:
   number of vertices       =          75
   number of vertices I own =          75
   number of elements       =         208
   number of leaf elements  =         108
   leaf elements I own      =         108
   number of levels         =           8
   degrees of freedom       =        5019
   degrees of freedom I own =        5019
   min and max degree       =           7         14

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           9
termination condition:
  maximum equations achieved
---------------------------------------------------------
