---------------------------------------------------------
           PHAML   Version 1.8.0

Output from the master process
  PDE id is     0
  Number of slave processors is     4

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert           infinity
  max_eq                    500
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    FINAL
  print_grid_who     MASTER
  print_linsys_when  NEVER
  print_error_when   NEVER
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ_SMOOTH
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    false
  solver             MG_SOLVER
  mg_cycles          infinity
  mg_tol             MG_ERREST_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_FUDOP
---------------------------------------------------------

Total Grid:
   number of vertices      =         761
   number of leaf elements =        1434
   number of levels        =           9
   degrees of freedom      =         761
   min and max degree      =           1          1

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           6
termination condition:
  maximum equations achieved
---------------------------------------------------------
nvert         761
nvert_proc         279        306        279        306
nvert_own         176        205        176        204
nelem        1434
nelem_proc         521        575        521        575
nelem_own         307        410        307        410
neq         761
neq_proc         279        306        279        306
neq_own         176        205        176        204
nlev           9
min_degree           1
max_degree           1
linf_error  1.056014422777E-03
energy_error  2.659318680237E-02
l2_error  6.865121675038E-04
max_error_indicator  4.143350590297E-04
linf_error_estimate  1.838801650492E-04
energy_error_estimate  1.200360952890E-02
l2_error_estimate  1.388938652291E-04
linf_solution  2.000000000000E+00
l2_solution  2.225164699482E+01
energy_solution  1.743878636892E+00
linf_u  2.000000000000E+00
l2_u  7.893600439153E-01
energy_u  1.632811806859E+00
linf_true  2.000000000000E+00
l2_true  7.888106377466E-01
energy_true  1.632993161855E+00
