---------------------------------------------------------
           PHAML   Version 1.8.0

Output from the master process
  PDE id is     0
  Number of slave processors is     4

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert           infinity
  max_eq                   5000
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    PHASES
  print_grid_who     MASTER
  print_linsys_when  NEVER
  print_error_when   NEVER
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            HP_ADAPTIVE
  edge_rule          MINIMUM_RULE
  hp_strategy        HP_ALTERNATE
  t3s_gamma           6.0000000000E+00
  t3s_eta             1.0000000000E-01
  t3s_nunif                    0
  t3s_maxref                   3
  t3s_maxdeginc                3
  refterm            DOUBLE_NEQ_SMOOTH
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    false
  solver             MG_SOLVER
  mg_cycles          infinity
  mg_tol             MG_ERREST_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_FUDOP
---------------------------------------------------------

Total Grid:
   number of vertices      =           9
   number of leaf elements =           8
   number of levels        =           1
   degrees of freedom      =           9
   min and max degree      =           1          1

Total Grid:
   number of vertices      =           9
   number of leaf elements =           8
   number of levels        =           1
   degrees of freedom      =          20
   min and max degree      =           1          2

Total Grid:
   number of vertices      =           9
   number of leaf elements =           8
   number of levels        =           1
   degrees of freedom      =          37
   min and max degree      =           1          3

Total Grid:
   number of vertices      =           9
   number of leaf elements =           8
   number of levels        =           1
   degrees of freedom      =          60
   min and max degree      =           1          4

Total Grid:
   number of vertices      =          12
   number of leaf elements =          14
   number of levels        =           2
   degrees of freedom      =         108
   min and max degree      =           1          4

Total Grid:
   number of vertices      =          12
   number of leaf elements =          14
   number of levels        =           2
   degrees of freedom      =         154
   min and max degree      =           1          5

Total Grid:
   number of vertices      =          12
   number of leaf elements =          14
   number of levels        =           2
   degrees of freedom      =         210
   min and max degree      =           1          6

Total Grid:
   number of vertices      =          18
   number of leaf elements =          22
   number of levels        =           3
   degrees of freedom      =         366
   min and max degree      =           1          6

Total Grid:
   number of vertices      =          18
   number of leaf elements =          22
   number of levels        =           3
   degrees of freedom      =         445
   min and max degree      =           1          7

Total Grid:
   number of vertices      =          30
   number of leaf elements =          44
   number of levels        =           4
   degrees of freedom      =         859
   min and max degree      =           1          7

Total Grid:
   number of vertices      =          30
   number of leaf elements =          44
   number of levels        =           4
   degrees of freedom      =        1051
   min and max degree      =           1          8

Total Grid:
   number of vertices      =          39
   number of leaf elements =          60
   number of levels        =           4
   degrees of freedom      =        1205
   min and max degree      =           1          8

Total Grid:
   number of vertices      =          39
   number of leaf elements =          60
   number of levels        =           4
   degrees of freedom      =        1471
   min and max degree      =           1          9

Total Grid:
   number of vertices      =          56
   number of leaf elements =          90
   number of levels        =           5
   degrees of freedom      =        2449
   min and max degree      =           1          9

Total Grid:
   number of vertices      =          56
   number of leaf elements =          90
   number of levels        =           5
   degrees of freedom      =        2714
   min and max degree      =           1         10

Total Grid:
   number of vertices      =          78
   number of leaf elements =         132
   number of levels        =           6
   degrees of freedom      =        3606
   min and max degree      =           1         10

Total Grid:
   number of vertices      =          90
   number of leaf elements =         156
   number of levels        =           6
   degrees of freedom      =        3695
   min and max degree      =           1         10

Total Grid:
   number of vertices      =          90
   number of leaf elements =         156
   number of levels        =           6
   degrees of freedom      =        4296
   min and max degree      =           1         11

Total Grid:
   number of vertices      =          90
   number of leaf elements =         156
   number of levels        =           6
   degrees of freedom      =        4340
   min and max degree      =           1         11

Total Grid:
   number of vertices      =         132
   number of leaf elements =         232
   number of levels        =           7
   degrees of freedom      =        6771
   min and max degree      =           1         11

Total Grid:
   number of vertices      =         132
   number of leaf elements =         232
   number of levels        =           7
   degrees of freedom      =        6771
   min and max degree      =           1         11

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =          19
termination condition:
  maximum equations achieved
---------------------------------------------------------
