---------------------------------------------------------
           PHAML   Version 1.6.2

Output from slave number     1
  PDE id is     0
  Number of slave processors is     1

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert           infinity
  max_eq                   5000
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    PHASES
  print_grid_who     SLAVES
  print_linsys_when  NEVER
  print_error_when   NEVER
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            HP_ADAPTIVE
  edge_rule          MINIMUM_RULE
  hp_strategy        HP_T3S
  t3s_gamma           6.0000000000E+00
  t3s_eta             1.0000000000E-01
  t3s_nunif                    4
  t3s_maxref                   3
  t3s_maxdeginc                3
  refterm            DOUBLE_NEQ_SMOOTH
  derefine           false
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    false
  solver             MG_SOLVER
  mg_cycles          infinity
  mg_tol             MG_ERREST_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_FUDOP
---------------------------------------------------------

My Grid:
   number of vertices       =           9
   number of vertices I own =           9
   number of elements       =           8
   number of leaf elements  =           8
   leaf elements I own      =           8
   number of levels         =           1
   degrees of freedom       =           9
   degrees of freedom I own =           9
   min and max degree       =           1          1

My Grid:
   number of vertices       =          96
   number of vertices I own =          96
   number of elements       =         308
   number of leaf elements  =         158
   leaf elements I own      =         158
   number of levels         =           6
   degrees of freedom       =          96
   degrees of freedom I own =          96
   min and max degree       =           1          1

My Grid:
   number of vertices       =          96
   number of vertices I own =          96
   number of elements       =         308
   number of leaf elements  =         158
   leaf elements I own      =         158
   number of levels         =           6
   degrees of freedom       =         663
   degrees of freedom I own =         663
   min and max degree       =           1          4

My Grid:
   number of vertices       =         137
   number of vertices I own =         137
   number of elements       =         472
   number of leaf elements  =         240
   leaf elements I own      =         240
   number of levels         =           7
   degrees of freedom       =         776
   degrees of freedom I own =         776
   min and max degree       =           1          4

My Grid:
   number of vertices       =         137
   number of vertices I own =         137
   number of elements       =         472
   number of leaf elements  =         240
   leaf elements I own      =         240
   number of levels         =           7
   degrees of freedom       =        2448
   degrees of freedom I own =        2448
   min and max degree       =           1          7

My Grid:
   number of vertices       =         211
   number of vertices I own =         211
   number of elements       =         764
   number of leaf elements  =         386
   leaf elements I own      =         386
   number of levels         =           8
   degrees of freedom       =        2544
   degrees of freedom I own =        2544
   min and max degree       =           1          7

My Grid:
   number of vertices       =         211
   number of vertices I own =         211
   number of elements       =         764
   number of leaf elements  =         386
   leaf elements I own      =         386
   number of levels         =           8
   degrees of freedom       =        4274
   degrees of freedom I own =        4274
   min and max degree       =           1         10

My Grid:
   number of vertices       =         323
   number of vertices I own =         323
   number of elements       =        1204
   number of leaf elements  =         606
   leaf elements I own      =         606
   number of levels         =          10
   degrees of freedom       =        4625
   degrees of freedom I own =        4625
   min and max degree       =           1         10

My Grid:
   number of vertices       =         323
   number of vertices I own =         323
   number of elements       =        1204
   number of leaf elements  =         606
   leaf elements I own      =         606
   number of levels         =          10
   degrees of freedom       =        9850
   degrees of freedom I own =        9850
   min and max degree       =           1         10

My Grid:
   number of vertices       =         323
   number of vertices I own =         323
   number of elements       =        1204
   number of leaf elements  =         606
   leaf elements I own      =         606
   number of levels         =          10
   degrees of freedom       =        9850
   degrees of freedom I own =        9850
   min and max degree       =           1         10

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           8
termination condition:
  maximum equations achieved
---------------------------------------------------------
