---------------------------------------------------------
           PHAML   Version 1.8.0

Output from slave number     1
  PDE id is     0
  Number of slave processors is     1

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert           infinity
  max_eq                   3500
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    PHASES
  print_grid_who     SLAVES
  print_linsys_when  NEVER
  print_error_when   NEVER
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            HP_ADAPTIVE
  edge_rule          MINIMUM_RULE
  hp_strategy        HP_BIGGER_ERRIND
  refterm            DOUBLE_NEQ_SMOOTH
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    false
  solver             MG_SOLVER
  mg_cycles                  50
  mg_tol             MG_ERREST_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_FUDOP
---------------------------------------------------------

My Grid:
   number of vertices       =           9
   number of vertices I own =           9
   number of elements       =           8
   number of leaf elements  =           8
   leaf elements I own      =           8
   number of levels         =           1
   degrees of freedom       =           9
   degrees of freedom I own =           9
   min and max degree       =           1          1

My Grid:
   number of vertices       =           9
   number of vertices I own =           9
   number of elements       =           8
   number of leaf elements  =           8
   leaf elements I own      =           8
   number of levels         =           1
   degrees of freedom       =          20
   degrees of freedom I own =          20
   min and max degree       =           1          3

My Grid:
   number of vertices       =          13
   number of vertices I own =          13
   number of elements       =          20
   number of leaf elements  =          14
   leaf elements I own      =          14
   number of levels         =           4
   degrees of freedom       =          44
   degrees of freedom I own =          44
   min and max degree       =           1          3

My Grid:
   number of vertices       =          15
   number of vertices I own =          15
   number of elements       =          28
   number of leaf elements  =          18
   leaf elements I own      =          18
   number of levels         =           4
   degrees of freedom       =          83
   degrees of freedom I own =          83
   min and max degree       =           1          4

My Grid:
   number of vertices       =          22
   number of vertices I own =          22
   number of elements       =          48
   number of leaf elements  =          28
   leaf elements I own      =          28
   number of levels         =           6
   degrees of freedom       =         174
   degrees of freedom I own =         174
   min and max degree       =           1          5

My Grid:
   number of vertices       =          31
   number of vertices I own =          31
   number of elements       =          76
   number of leaf elements  =          42
   leaf elements I own      =          42
   number of levels         =           8
   degrees of freedom       =         317
   degrees of freedom I own =         317
   min and max degree       =           1          6

My Grid:
   number of vertices       =          41
   number of vertices I own =          41
   number of elements       =         106
   number of leaf elements  =          57
   leaf elements I own      =          57
   number of levels         =          10
   degrees of freedom       =         622
   degrees of freedom I own =         622
   min and max degree       =           1          7

My Grid:
   number of vertices       =          62
   number of vertices I own =          62
   number of elements       =         182
   number of leaf elements  =          95
   leaf elements I own      =          95
   number of levels         =          13
   degrees of freedom       =        1236
   degrees of freedom I own =        1236
   min and max degree       =           2          8

My Grid:
   number of vertices       =          99
   number of vertices I own =          99
   number of elements       =         322
   number of leaf elements  =         165
   leaf elements I own      =         165
   number of levels         =          14
   degrees of freedom       =        2425
   degrees of freedom I own =        2425
   min and max degree       =           2          8

My Grid:
   number of vertices       =         132
   number of vertices I own =         132
   number of elements       =         442
   number of leaf elements  =         225
   leaf elements I own      =         225
   number of levels         =          14
   degrees of freedom       =        3663
   degrees of freedom I own =        3663
   min and max degree       =           2          8

My Grid:
   number of vertices       =         132
   number of vertices I own =         132
   number of elements       =         442
   number of leaf elements  =         225
   leaf elements I own      =         225
   number of levels         =          14
   degrees of freedom       =        3663
   degrees of freedom I own =        3663
   min and max degree       =           2          8

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           9
termination condition:
  maximum equations achieved
---------------------------------------------------------
