---------------------------------------------------------
           PHAML   Version 1.8.0

Output from the master process
  PDE id is     0
  Number of slave processors is     4

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert           infinity
  max_eq                   5000
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    PHASES
  print_grid_who     MASTER
  print_linsys_when  NEVER
  print_error_when   NEVER
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            HP_ADAPTIVE
  edge_rule          MINIMUM_RULE
  hp_strategy        HP_COEF_DECAY
  refterm            DOUBLE_NEQ_SMOOTH
  derefine           false
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    false
  solver             MG_SOLVER
  mg_cycles          infinity
  mg_tol             MG_ERREST_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_FUDOP
---------------------------------------------------------

Total Grid:
   number of vertices      =           9
   number of leaf elements =           8
   number of levels        =           1
   degrees of freedom      =           9
   min and max degree      =           1          1

Total Grid:
   number of vertices      =           9
   number of leaf elements =           8
   number of levels        =           1
   degrees of freedom      =          20
   min and max degree      =           1          3

Total Grid:
   number of vertices      =          10
   number of leaf elements =          10
   number of levels        =           2
   degrees of freedom      =          40
   min and max degree      =           1          3

Total Grid:
   number of vertices      =          14
   number of leaf elements =          16
   number of levels        =           3
   degrees of freedom      =          75
   min and max degree      =           2          3

Total Grid:
   number of vertices      =          27
   number of leaf elements =          38
   number of levels        =           4
   degrees of freedom      =         180
   min and max degree      =           2          3

Total Grid:
   number of vertices      =          43
   number of leaf elements =          60
   number of levels        =           5
   degrees of freedom      =         294
   min and max degree      =           2          3

Total Grid:
   number of vertices      =          58
   number of leaf elements =          90
   number of levels        =           6
   degrees of freedom      =         585
   min and max degree      =           2          4

Total Grid:
   number of vertices      =         111
   number of leaf elements =         192
   number of levels        =           7
   degrees of freedom      =        1162
   min and max degree      =           2          5

Total Grid:
   number of vertices      =         178
   number of leaf elements =         316
   number of levels        =          11
   degrees of freedom      =        2102
   min and max degree      =           2          5

Total Grid:
   number of vertices      =         214
   number of leaf elements =         387
   number of levels        =          11
   degrees of freedom      =        2915
   min and max degree      =           2          6

Total Grid:
   number of vertices      =         339
   number of leaf elements =         624
   number of levels        =          11
   degrees of freedom      =        5123
   min and max degree      =           2          7

Total Grid:
   number of vertices      =         339
   number of leaf elements =         624
   number of levels        =          11
   degrees of freedom      =        5123
   min and max degree      =           2          7

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =          10
termination condition:
  maximum equations achieved
---------------------------------------------------------
