---------------------------------------------------------
           PHAML   Version 1.8.0

Output from the master process
  PDE id is     0
  Number of slave processors is     4

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert           infinity
  max_eq                   5000
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    PHASES
  print_grid_who     MASTER
  print_linsys_when  NEVER
  print_error_when   NEVER
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            HP_ADAPTIVE
  edge_rule          MINIMUM_RULE
  hp_strategy        HP_T3S
  t3s_gamma           6.0000000000E+00
  t3s_eta             1.0000000000E-01
  t3s_nunif                    4
  t3s_maxref                   3
  t3s_maxdeginc                3
  refterm            DOUBLE_NEQ_SMOOTH
  derefine           false
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    false
  solver             MG_SOLVER
  mg_cycles          infinity
  mg_tol             MG_ERREST_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_FUDOP
---------------------------------------------------------

Total Grid:
   number of vertices      =           9
   number of leaf elements =           8
   number of levels        =           1
   degrees of freedom      =           9
   min and max degree      =           1          1

Total Grid:
   number of vertices      =          96
   number of leaf elements =         158
   number of levels        =           6
   degrees of freedom      =          96
   min and max degree      =           1          1

Total Grid:
   number of vertices      =          96
   number of leaf elements =         158
   number of levels        =           6
   degrees of freedom      =         663
   min and max degree      =           1          4

Total Grid:
   number of vertices      =         202
   number of leaf elements =         368
   number of levels        =           8
   degrees of freedom      =        1318
   min and max degree      =           1          4

Total Grid:
   number of vertices      =         202
   number of leaf elements =         368
   number of levels        =           8
   degrees of freedom      =        3480
   min and max degree      =           1          7

Total Grid:
   number of vertices      =         437
   number of leaf elements =         830
   number of levels        =          10
   degrees of freedom      =        3957
   min and max degree      =           1          7

Total Grid:
   number of vertices      =         437
   number of leaf elements =         830
   number of levels        =          10
   degrees of freedom      =       10663
   min and max degree      =           1         10

Total Grid:
   number of vertices      =         437
   number of leaf elements =         830
   number of levels        =          10
   degrees of freedom      =       10663
   min and max degree      =           1         10

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           6
termination condition:
  maximum equations achieved
---------------------------------------------------------
