---------------------------------------------------------
           PHAML   Version 1.6.2

Output from the master process
  PDE id is     0
  Number of slave processors is     4

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert           infinity
  max_eq                   3000
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    19
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    PHASES
  print_grid_who     MASTER
  print_linsys_when  NEVER
  print_error_when   NEVER
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            HP_ADAPTIVE
  edge_rule          MINIMUM_RULE
  hp_strategy        HP_NEXT3P
  refterm            DOUBLE_NEQ_SMOOTH
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    false
  solver             MG_SOLVER
  mg_cycles          infinity
  mg_tol             MG_ERREST_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_FUDOP
---------------------------------------------------------

Total Grid:
   number of vertices      =           9
   number of leaf elements =           8
   number of levels        =           1
   degrees of freedom      =           9
   min and max degree      =           1          1

Total Grid:
   number of vertices      =          11
   number of leaf elements =          12
   number of levels        =           2
   degrees of freedom      =          22
   min and max degree      =           1          2

Total Grid:
   number of vertices      =          12
   number of leaf elements =          14
   number of levels        =           2
   degrees of freedom      =          37
   min and max degree      =           1          3

Total Grid:
   number of vertices      =          15
   number of leaf elements =          18
   number of levels        =           3
   degrees of freedom      =          73
   min and max degree      =           1          4

Total Grid:
   number of vertices      =          18
   number of leaf elements =          21
   number of levels        =           3
   degrees of freedom      =         152
   min and max degree      =           1          5

Total Grid:
   number of vertices      =          24
   number of leaf elements =          32
   number of levels        =           4
   degrees of freedom      =         332
   min and max degree      =           1          5

Total Grid:
   number of vertices      =          37
   number of leaf elements =          55
   number of levels        =           5
   degrees of freedom      =         600
   min and max degree      =           1          6

Total Grid:
   number of vertices      =          58
   number of leaf elements =          91
   number of levels        =           6
   degrees of freedom      =        1213
   min and max degree      =           1          7

Total Grid:
   number of vertices      =          92
   number of leaf elements =         153
   number of levels        =           7
   degrees of freedom      =        2367
   min and max degree      =           1          7

Total Grid:
   number of vertices      =         111
   number of leaf elements =         188
   number of levels        =           8
   degrees of freedom      =        3025
   min and max degree      =           2          7

Total Grid:
   number of vertices      =         111
   number of leaf elements =         188
   number of levels        =           8
   degrees of freedom      =        3025
   min and max degree      =           2          7

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           9
termination condition:
  maximum equations achieved
---------------------------------------------------------
