---------------------------------------------------------
           PHAML   Version 1.6.2

Output from the master process
  PDE id is     0
  Number of slave processors is     4

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert           infinity
  max_eq                   5000
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    PHASES
  print_grid_who     MASTER
  print_linsys_when  NEVER
  print_error_when   NEVER
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            HP_ADAPTIVE
  edge_rule          MINIMUM_RULE
  hp_strategy        HP_TYPEPARAM
  tp_gamma            2.0000000000E-01
  refterm            DOUBLE_NEQ_SMOOTH
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    false
  solver             MG_SOLVER
  mg_cycles          infinity
  mg_tol             MG_ERREST_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_FUDOP
---------------------------------------------------------

Total Grid:
   number of vertices      =           9
   number of leaf elements =           8
   number of levels        =           1
   degrees of freedom      =           9
   min and max degree      =           1          1

Total Grid:
   number of vertices      =          11
   number of leaf elements =          12
   number of levels        =           2
   degrees of freedom      =          22
   min and max degree      =           1          2

Total Grid:
   number of vertices      =          16
   number of leaf elements =          18
   number of levels        =           3
   degrees of freedom      =          40
   min and max degree      =           1          2

Total Grid:
   number of vertices      =          27
   number of leaf elements =          38
   number of levels        =           4
   degrees of freedom      =          84
   min and max degree      =           1          2

Total Grid:
   number of vertices      =          58
   number of leaf elements =          90
   number of levels        =           6
   degrees of freedom      =         198
   min and max degree      =           1          2

Total Grid:
   number of vertices      =          74
   number of leaf elements =         106
   number of levels        =           7
   degrees of freedom      =         293
   min and max degree      =           1          3

Total Grid:
   number of vertices      =         101
   number of leaf elements =         160
   number of levels        =           7
   degrees of freedom      =         682
   min and max degree      =           1          4

Total Grid:
   number of vertices      =         197
   number of leaf elements =         352
   number of levels        =          13
   degrees of freedom      =        1423
   min and max degree      =           1          4

Total Grid:
   number of vertices      =         239
   number of leaf elements =         433
   number of levels        =          13
   degrees of freedom      =        1977
   min and max degree      =           1          5

Total Grid:
   number of vertices      =         376
   number of leaf elements =         706
   number of levels        =          17
   degrees of freedom      =        3002
   min and max degree      =           1          5

Total Grid:
   number of vertices      =         454
   number of leaf elements =         860
   number of levels        =          17
   degrees of freedom      =        3382
   min and max degree      =           1          5

Total Grid:
   number of vertices      =         480
   number of leaf elements =         912
   number of levels        =          17
   degrees of freedom      =        3868
   min and max degree      =           1          5

Total Grid:
   number of vertices      =         548
   number of leaf elements =        1044
   number of levels        =          17
   degrees of freedom      =        4817
   min and max degree      =           1          5

Total Grid:
   number of vertices      =         430
   number of leaf elements =         812
   number of levels        =          17
   degrees of freedom      =        3813
   min and max degree      =           1          5

Total Grid:
   number of vertices      =         475
   number of leaf elements =         900
   number of levels        =          17
   degrees of freedom      =        4439
   min and max degree      =           1          5

Total Grid:
   number of vertices      =         595
   number of leaf elements =        1139
   number of levels        =          23
   degrees of freedom      =        5215
   min and max degree      =           1          5

Total Grid:
   number of vertices      =         595
   number of leaf elements =        1139
   number of levels        =          23
   degrees of freedom      =        5215
   min and max degree      =           1          5

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =          15
termination condition:
  maximum equations achieved
---------------------------------------------------------
