---------------------------------------------------------
           PHAML   Version 1.6.2

Output from the master process
  PDE id is     0
  Number of slave processors is     4

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert           infinity
  max_eq                   5000
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    PHASES
  print_grid_who     MASTER
  print_linsys_when  NEVER
  print_error_when   NEVER
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            HP_ADAPTIVE
  edge_rule          MINIMUM_RULE
  hp_strategy        HP_COEF_ROOT
  refterm            DOUBLE_NEQ_SMOOTH
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    false
  solver             MG_SOLVER
  mg_cycles          infinity
  mg_tol             MG_ERREST_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_FUDOP
---------------------------------------------------------

Total Grid:
   number of vertices      =           9
   number of leaf elements =           8
   number of levels        =           1
   degrees of freedom      =           9
   min and max degree      =           1          1

Total Grid:
   number of vertices      =          11
   number of leaf elements =          12
   number of levels        =           2
   degrees of freedom      =          22
   min and max degree      =           1          2

Total Grid:
   number of vertices      =          16
   number of leaf elements =          18
   number of levels        =           3
   degrees of freedom      =          40
   min and max degree      =           1          2

Total Grid:
   number of vertices      =          27
   number of leaf elements =          38
   number of levels        =           4
   degrees of freedom      =          84
   min and max degree      =           1          2

Total Grid:
   number of vertices      =          58
   number of leaf elements =          90
   number of levels        =           6
   degrees of freedom      =         198
   min and max degree      =           1          2

Total Grid:
   number of vertices      =          76
   number of leaf elements =         122
   number of levels        =           7
   degrees of freedom      =         294
   min and max degree      =           1          3

Total Grid:
   number of vertices      =          93
   number of leaf elements =         142
   number of levels        =           8
   degrees of freedom      =         632
   min and max degree      =           1          3

Total Grid:
   number of vertices      =         158
   number of leaf elements =         272
   number of levels        =           8
   degrees of freedom      =        1236
   min and max degree      =           1          3

Total Grid:
   number of vertices      =         283
   number of leaf elements =         510
   number of levels        =          13
   degrees of freedom      =        2532
   min and max degree      =           1          4

Total Grid:
   number of vertices      =         293
   number of leaf elements =         527
   number of levels        =          13
   degrees of freedom      =        2625
   min and max degree      =           1          4

Total Grid:
   number of vertices      =         375
   number of leaf elements =         669
   number of levels        =          13
   degrees of freedom      =        3670
   min and max degree      =           1          5

Total Grid:
   number of vertices      =         446
   number of leaf elements =         810
   number of levels        =          13
   degrees of freedom      =        4933
   min and max degree      =           1          5

Total Grid:
   number of vertices      =         459
   number of leaf elements =         834
   number of levels        =          13
   degrees of freedom      =        4899
   min and max degree      =           1          5

Total Grid:
   number of vertices      =         460
   number of leaf elements =         849
   number of levels        =          13
   degrees of freedom      =        5009
   min and max degree      =           1          5

Total Grid:
   number of vertices      =         460
   number of leaf elements =         849
   number of levels        =          13
   degrees of freedom      =        5009
   min and max degree      =           1          5

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =          13
termination condition:
  maximum equations achieved
---------------------------------------------------------
