---------------------------------------------------------
           PHAML   Version 1.8.0

Output from slave number     1
  PDE id is     0
  Number of slave processors is     1

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert           infinity
  max_eq                   5000
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    PHASES
  print_grid_who     SLAVES
  print_linsys_when  NEVER
  print_error_when   NEVER
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            HP_ADAPTIVE
  edge_rule          MINIMUM_RULE
  hp_strategy        HP_TYPEPARAM
  tp_gamma            2.0000000000E-01
  refterm            DOUBLE_NEQ_SMOOTH
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    false
  solver             MG_SOLVER
  mg_cycles          infinity
  mg_tol             MG_ERREST_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_FUDOP
---------------------------------------------------------

My Grid:
   number of vertices       =           9
   number of vertices I own =           9
   number of elements       =           8
   number of leaf elements  =           8
   leaf elements I own      =           8
   number of levels         =           1
   degrees of freedom       =           9
   degrees of freedom I own =           9
   min and max degree       =           1          1

My Grid:
   number of vertices       =          11
   number of vertices I own =          11
   number of elements       =          16
   number of leaf elements  =          12
   leaf elements I own      =          12
   number of levels         =           2
   degrees of freedom       =          22
   degrees of freedom I own =          22
   min and max degree       =           1          2

My Grid:
   number of vertices       =          16
   number of vertices I own =          16
   number of elements       =          28
   number of leaf elements  =          18
   leaf elements I own      =          18
   number of levels         =           3
   degrees of freedom       =          36
   degrees of freedom I own =          36
   min and max degree       =           1          2

My Grid:
   number of vertices       =          25
   number of vertices I own =          25
   number of elements       =          60
   number of leaf elements  =          34
   leaf elements I own      =          34
   number of levels         =           4
   degrees of freedom       =          74
   degrees of freedom I own =          74
   min and max degree       =           1          2

My Grid:
   number of vertices       =          58
   number of vertices I own =          58
   number of elements       =         172
   number of leaf elements  =          90
   leaf elements I own      =          90
   number of levels         =           6
   degrees of freedom       =         196
   degrees of freedom I own =         196
   min and max degree       =           1          2

My Grid:
   number of vertices       =          74
   number of vertices I own =          74
   number of elements       =         204
   number of leaf elements  =         106
   leaf elements I own      =         106
   number of levels         =           7
   degrees of freedom       =         291
   degrees of freedom I own =         291
   min and max degree       =           1          3

My Grid:
   number of vertices       =         125
   number of vertices I own =         125
   number of elements       =         404
   number of leaf elements  =         206
   leaf elements I own      =         206
   number of levels         =           8
   degrees of freedom       =         935
   degrees of freedom I own =         935
   min and max degree       =           1          4

My Grid:
   number of vertices       =         140
   number of vertices I own =         140
   number of elements       =         464
   number of leaf elements  =         236
   leaf elements I own      =         236
   number of levels         =           8
   degrees of freedom       =        1154
   degrees of freedom I own =        1154
   min and max degree       =           1          4

My Grid:
   number of vertices       =         216
   number of vertices I own =         216
   number of elements       =         760
   number of leaf elements  =         384
   leaf elements I own      =         384
   number of levels         =           9
   degrees of freedom       =        2488
   degrees of freedom I own =        2488
   min and max degree       =           1          5

My Grid:
   number of vertices       =         351
   number of vertices I own =         351
   number of elements       =        1288
   number of leaf elements  =         648
   leaf elements I own      =         648
   number of levels         =          10
   degrees of freedom       =        4649
   degrees of freedom I own =        4649
   min and max degree       =           1          6

My Grid:
   number of vertices       =         356
   number of vertices I own =         356
   number of elements       =        1304
   number of leaf elements  =         656
   leaf elements I own      =         656
   number of levels         =          10
   degrees of freedom       =        5086
   degrees of freedom I own =        5086
   min and max degree       =           1          6

My Grid:
   number of vertices       =         356
   number of vertices I own =         356
   number of elements       =        1304
   number of leaf elements  =         656
   leaf elements I own      =         656
   number of levels         =          10
   degrees of freedom       =        5086
   degrees of freedom I own =        5086
   min and max degree       =           1          6

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =          10
termination condition:
  maximum equations achieved
---------------------------------------------------------
