---------------------------------------------------------
           PHAML   Version 1.6.2

Output from the master process
  PDE id is     0
  Number of slave processors is     4

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert           infinity
  max_eq                   5000
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    PHASES
  print_grid_who     MASTER
  print_linsys_when  NEVER
  print_error_when   NEVER
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            HP_ADAPTIVE
  edge_rule          MINIMUM_RULE
  hp_strategy        HP_SMOOTH_PRED
  sp_gamma_h          4.0000000000E+00
  sp_gamma_p          4.0000000000E-01
  refterm            DOUBLE_NEQ_SMOOTH
  derefine           false
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    false
  solver             MG_SOLVER
  mg_cycles          infinity
  mg_tol             MG_ERREST_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_FUDOP
---------------------------------------------------------

Total Grid:
   number of vertices      =           9
   number of leaf elements =           8
   number of levels        =           1
   degrees of freedom      =           9
   min and max degree      =           1          1

Total Grid:
   number of vertices      =          13
   number of leaf elements =          15
   number of levels        =           3
   degrees of freedom      =          20
   min and max degree      =           1          2

Total Grid:
   number of vertices      =          16
   number of leaf elements =          18
   number of levels        =           3
   degrees of freedom      =          40
   min and max degree      =           1          2

Total Grid:
   number of vertices      =          20
   number of leaf elements =          24
   number of levels        =           3
   degrees of freedom      =          75
   min and max degree      =           1          3

Total Grid:
   number of vertices      =          24
   number of leaf elements =          32
   number of levels        =           4
   degrees of freedom      =         200
   min and max degree      =           1          5

Total Grid:
   number of vertices      =          26
   number of leaf elements =          36
   number of levels        =           5
   degrees of freedom      =         296
   min and max degree      =           1          5

Total Grid:
   number of vertices      =          35
   number of leaf elements =          54
   number of levels        =           5
   degrees of freedom      =         529
   min and max degree      =           1          6

Total Grid:
   number of vertices      =          53
   number of leaf elements =          84
   number of levels        =           7
   degrees of freedom      =        1266
   min and max degree      =           1          8

Total Grid:
   number of vertices      =          78
   number of leaf elements =         128
   number of levels        =           7
   degrees of freedom      =        2128
   min and max degree      =           1          9

Total Grid:
   number of vertices      =         104
   number of leaf elements =         176
   number of levels        =           8
   degrees of freedom      =        3643
   min and max degree      =           1          9

Total Grid:
   number of vertices      =         128
   number of leaf elements =         222
   number of levels        =           9
   degrees of freedom      =        4663
   min and max degree      =           1          9

Total Grid:
   number of vertices      =         140
   number of leaf elements =         246
   number of levels        =           9
   degrees of freedom      =        5415
   min and max degree      =           1          9

Total Grid:
   number of vertices      =         140
   number of leaf elements =         246
   number of levels        =           9
   degrees of freedom      =        5415
   min and max degree      =           1          9

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =          11
termination condition:
  maximum equations achieved
---------------------------------------------------------
