---------------------------------------------------------
           PHAML   Version 1.6.2

Output from slave number     1
  PDE id is     0
  Number of slave processors is     1

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert           infinity
  max_eq                   5000
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    PHASES
  print_grid_who     SLAVES
  print_linsys_when  NEVER
  print_error_when   NEVER
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            HP_ADAPTIVE
  edge_rule          MINIMUM_RULE
  hp_strategy        HP_TYPEPARAM
  tp_gamma            2.0000000000E-01
  refterm            DOUBLE_NEQ_SMOOTH
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    false
  solver             MG_SOLVER
  mg_cycles          infinity
  mg_tol             MG_ERREST_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_FUDOP
---------------------------------------------------------

My Grid:
   number of vertices       =           9
   number of vertices I own =           9
   number of elements       =           8
   number of leaf elements  =           8
   leaf elements I own      =           8
   number of levels         =           1
   degrees of freedom       =           9
   degrees of freedom I own =           9
   min and max degree       =           1          1

My Grid:
   number of vertices       =          11
   number of vertices I own =          11
   number of elements       =          16
   number of leaf elements  =          12
   leaf elements I own      =          12
   number of levels         =           2
   degrees of freedom       =          22
   degrees of freedom I own =          22
   min and max degree       =           1          2

My Grid:
   number of vertices       =          16
   number of vertices I own =          16
   number of elements       =          28
   number of leaf elements  =          18
   leaf elements I own      =          18
   number of levels         =           3
   degrees of freedom       =          40
   degrees of freedom I own =          40
   min and max degree       =           1          2

My Grid:
   number of vertices       =          27
   number of vertices I own =          27
   number of elements       =          68
   number of leaf elements  =          38
   leaf elements I own      =          38
   number of levels         =           4
   degrees of freedom       =          84
   degrees of freedom I own =          84
   min and max degree       =           1          2

My Grid:
   number of vertices       =          58
   number of vertices I own =          58
   number of elements       =         172
   number of leaf elements  =          90
   leaf elements I own      =          90
   number of levels         =           6
   degrees of freedom       =         198
   degrees of freedom I own =         198
   min and max degree       =           1          2

My Grid:
   number of vertices       =          74
   number of vertices I own =          74
   number of elements       =         204
   number of leaf elements  =         106
   leaf elements I own      =         106
   number of levels         =           7
   degrees of freedom       =         293
   degrees of freedom I own =         293
   min and max degree       =           1          3

My Grid:
   number of vertices       =         101
   number of vertices I own =         101
   number of elements       =         312
   number of leaf elements  =         160
   leaf elements I own      =         160
   number of levels         =           7
   degrees of freedom       =         682
   degrees of freedom I own =         682
   min and max degree       =           1          4

My Grid:
   number of vertices       =         151
   number of vertices I own =         151
   number of elements       =         508
   number of leaf elements  =         258
   leaf elements I own      =         258
   number of levels         =           9
   degrees of freedom       =        1215
   degrees of freedom I own =        1215
   min and max degree       =           1          4

My Grid:
   number of vertices       =         225
   number of vertices I own =         225
   number of elements       =         796
   number of leaf elements  =         402
   leaf elements I own      =         402
   number of levels         =          10
   degrees of freedom       =        2638
   degrees of freedom I own =        2638
   min and max degree       =           1          6

My Grid:
   number of vertices       =         367
   number of vertices I own =         367
   number of elements       =        1352
   number of leaf elements  =         680
   leaf elements I own      =         680
   number of levels         =          10
   degrees of freedom       =        5168
   degrees of freedom I own =        5168
   min and max degree       =           1          6

My Grid:
   number of vertices       =         367
   number of vertices I own =         367
   number of elements       =        1352
   number of leaf elements  =         680
   leaf elements I own      =         680
   number of levels         =          10
   degrees of freedom       =        5168
   degrees of freedom I own =        5168
   min and max degree       =           1          6

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           9
termination condition:
  maximum equations achieved
---------------------------------------------------------
