---------------------------------------------------------
           PHAML   Version 1.6.2

Output from slave number     1
  PDE id is     0
  Number of slave processors is     1

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert           infinity
  max_eq                   2000
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    PHASES
  print_grid_who     SLAVES
  print_linsys_when  NEVER
  print_error_when   NEVER
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            HP_ADAPTIVE
  edge_rule          MINIMUM_RULE
  hp_strategy        HP_APRIORI
  refterm            DOUBLE_NEQ_SMOOTH
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    false
  solver             MG_SOLVER
  mg_cycles          infinity
  mg_tol             MG_ERREST_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_FUDOP
---------------------------------------------------------

My Grid:
   number of vertices       =           9
   number of vertices I own =           9
   number of elements       =           8
   number of leaf elements  =           8
   leaf elements I own      =           8
   number of levels         =           1
   degrees of freedom       =           9
   degrees of freedom I own =           9
   min and max degree       =           1          1

My Grid:
   number of vertices       =          15
   number of vertices I own =          15
   number of elements       =          24
   number of leaf elements  =          16
   leaf elements I own      =          16
   number of levels         =           5
   degrees of freedom       =          19
   degrees of freedom I own =          19
   min and max degree       =           1          2

My Grid:
   number of vertices       =          18
   number of vertices I own =          18
   number of elements       =          32
   number of leaf elements  =          20
   leaf elements I own      =          20
   number of levels         =           7
   degrees of freedom       =          37
   degrees of freedom I own =          37
   min and max degree       =           1          3

My Grid:
   number of vertices       =          21
   number of vertices I own =          21
   number of elements       =          40
   number of leaf elements  =          24
   leaf elements I own      =          24
   number of levels         =           9
   degrees of freedom       =          80
   degrees of freedom I own =          80
   min and max degree       =           1          4

My Grid:
   number of vertices       =          24
   number of vertices I own =          24
   number of elements       =          48
   number of leaf elements  =          28
   leaf elements I own      =          28
   number of levels         =          11
   degrees of freedom       =         156
   degrees of freedom I own =         156
   min and max degree       =           1          6

My Grid:
   number of vertices       =          28
   number of vertices I own =          28
   number of elements       =          60
   number of leaf elements  =          34
   leaf elements I own      =          34
   number of levels         =          14
   degrees of freedom       =         312
   degrees of freedom I own =         312
   min and max degree       =           1          8

My Grid:
   number of vertices       =          34
   number of vertices I own =          34
   number of elements       =          76
   number of leaf elements  =          42
   leaf elements I own      =          42
   number of levels         =          18
   degrees of freedom       =         595
   degrees of freedom I own =         595
   min and max degree       =           1         11

My Grid:
   number of vertices       =          39
   number of vertices I own =          39
   number of elements       =          88
   number of leaf elements  =          48
   leaf elements I own      =          48
   number of levels         =          21
   degrees of freedom       =         853
   degrees of freedom I own =         853
   min and max degree       =           1         15

My Grid:
   number of vertices       =          45
   number of vertices I own =          45
   number of elements       =         104
   number of leaf elements  =          56
   leaf elements I own      =          56
   number of levels         =          25
   degrees of freedom       =        1310
   degrees of freedom I own =        1310
   min and max degree       =           1         16

My Grid:
   number of vertices       =          51
   number of vertices I own =          51
   number of elements       =         120
   number of leaf elements  =          64
   leaf elements I own      =          64
   number of levels         =          29
   degrees of freedom       =        1739
   degrees of freedom I own =        1739
   min and max degree       =           1         17

My Grid:
   number of vertices       =          57
   number of vertices I own =          57
   number of elements       =         136
   number of leaf elements  =          72
   leaf elements I own      =          72
   number of levels         =          33
   degrees of freedom       =        1941
   degrees of freedom I own =        1941
   min and max degree       =           1         17

My Grid:
   number of vertices       =          61
   number of vertices I own =          61
   number of elements       =         148
   number of leaf elements  =          78
   leaf elements I own      =          78
   number of levels         =          36
   degrees of freedom       =        2006
   degrees of freedom I own =        2006
   min and max degree       =           1         17

My Grid:
   number of vertices       =          61
   number of vertices I own =          61
   number of elements       =         148
   number of leaf elements  =          78
   leaf elements I own      =          78
   number of levels         =          36
   degrees of freedom       =        2006
   degrees of freedom I own =        2006
   min and max degree       =           1         17

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =          11
termination condition:
  maximum equations achieved
---------------------------------------------------------
