---------------------------------------------------------
           PHAML   Version 1.6.2

Output from slave number     1
  PDE id is     0
  Number of slave processors is     1

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert           infinity
  max_eq                   3500
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    PHASES
  print_grid_who     SLAVES
  print_linsys_when  NEVER
  print_error_when   NEVER
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            HP_ADAPTIVE
  edge_rule          MINIMUM_RULE
  hp_strategy        HP_BIGGER_ERRIND
  refterm            DOUBLE_NEQ_SMOOTH
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    false
  solver             MG_SOLVER
  mg_cycles                  50
  mg_tol             MG_ERREST_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_FUDOP
---------------------------------------------------------

My Grid:
   number of vertices       =           9
   number of vertices I own =           9
   number of elements       =           8
   number of leaf elements  =           8
   leaf elements I own      =           8
   number of levels         =           1
   degrees of freedom       =           9
   degrees of freedom I own =           9
   min and max degree       =           1          1

My Grid:
   number of vertices       =           9
   number of vertices I own =           9
   number of elements       =           8
   number of leaf elements  =           8
   leaf elements I own      =           8
   number of levels         =           1
   degrees of freedom       =          20
   degrees of freedom I own =          20
   min and max degree       =           1          3

My Grid:
   number of vertices       =          13
   number of vertices I own =          13
   number of elements       =          20
   number of leaf elements  =          14
   leaf elements I own      =          14
   number of levels         =           4
   degrees of freedom       =          44
   degrees of freedom I own =          44
   min and max degree       =           1          3

My Grid:
   number of vertices       =          16
   number of vertices I own =          16
   number of elements       =          30
   number of leaf elements  =          19
   leaf elements I own      =          19
   number of levels         =           5
   degrees of freedom       =          94
   degrees of freedom I own =          94
   min and max degree       =           1          5

My Grid:
   number of vertices       =          20
   number of vertices I own =          20
   number of elements       =          42
   number of leaf elements  =          25
   leaf elements I own      =          25
   number of levels         =           5
   degrees of freedom       =         170
   degrees of freedom I own =         170
   min and max degree       =           1          5

My Grid:
   number of vertices       =          26
   number of vertices I own =          26
   number of elements       =          62
   number of leaf elements  =          35
   leaf elements I own      =          35
   number of levels         =           6
   degrees of freedom       =         303
   degrees of freedom I own =         303
   min and max degree       =           1          7

My Grid:
   number of vertices       =          34
   number of vertices I own =          34
   number of elements       =          88
   number of leaf elements  =          48
   leaf elements I own      =          48
   number of levels         =           7
   degrees of freedom       =         611
   degrees of freedom I own =         611
   min and max degree       =           1          7

My Grid:
   number of vertices       =          42
   number of vertices I own =          42
   number of elements       =         116
   number of leaf elements  =          62
   leaf elements I own      =          62
   number of levels         =           7
   degrees of freedom       =        1195
   degrees of freedom I own =        1195
   min and max degree       =           3          8

My Grid:
   number of vertices       =          61
   number of vertices I own =          61
   number of elements       =         190
   number of leaf elements  =          99
   leaf elements I own      =          99
   number of levels         =           7
   degrees of freedom       =        1918
   degrees of freedom I own =        1918
   min and max degree       =           3          9

My Grid:
   number of vertices       =          84
   number of vertices I own =          84
   number of elements       =         276
   number of leaf elements  =         142
   leaf elements I own      =         142
   number of levels         =           8
   degrees of freedom       =        2981
   degrees of freedom I own =        2981
   min and max degree       =           3          9

My Grid:
   number of vertices       =          99
   number of vertices I own =          99
   number of elements       =         330
   number of leaf elements  =         169
   leaf elements I own      =         169
   number of levels         =           8
   degrees of freedom       =        3773
   degrees of freedom I own =        3773
   min and max degree       =           4         10

My Grid:
   number of vertices       =          99
   number of vertices I own =          99
   number of elements       =         330
   number of leaf elements  =         169
   leaf elements I own      =         169
   number of levels         =           8
   degrees of freedom       =        3773
   degrees of freedom I own =        3773
   min and max degree       =           4         10

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =          10
termination condition:
  maximum equations achieved
---------------------------------------------------------
