---------------------------------------------------------
           PHAML   Version 1.8.0

Output from slave number     1
  PDE id is     0
  Number of slave processors is     1

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert           infinity
  max_eq                   5000
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    PHASES
  print_grid_who     SLAVES
  print_linsys_when  NEVER
  print_error_when   NEVER
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree                      3
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            HP_ADAPTIVE
  edge_rule          MINIMUM_RULE
  hp_strategy        HP_PRIOR2P_E
  refterm            DOUBLE_NEQ_SMOOTH
  derefine           false
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    false
  solver             MG_SOLVER
  mg_cycles          infinity
  mg_tol             MG_ERREST_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_FUDOP
---------------------------------------------------------

My Grid:
   number of vertices       =           9
   number of vertices I own =           9
   number of elements       =           8
   number of leaf elements  =           8
   leaf elements I own      =           8
   number of levels         =           1
   degrees of freedom       =          49
   degrees of freedom I own =          49
   min and max degree       =           3          3

My Grid:
   number of vertices       =          16
   number of vertices I own =          16
   number of elements       =          28
   number of leaf elements  =          18
   leaf elements I own      =          18
   number of levels         =           3
   degrees of freedom       =         100
   degrees of freedom I own =         100
   min and max degree       =           3          3

My Grid:
   number of vertices       =          29
   number of vertices I own =          29
   number of elements       =          72
   number of leaf elements  =          40
   leaf elements I own      =          40
   number of levels         =           5
   degrees of freedom       =         205
   degrees of freedom I own =         205
   min and max degree       =           3          3

My Grid:
   number of vertices       =          58
   number of vertices I own =          58
   number of elements       =         172
   number of leaf elements  =          90
   leaf elements I own      =          90
   number of levels         =           6
   degrees of freedom       =         442
   degrees of freedom I own =         442
   min and max degree       =           3          3

My Grid:
   number of vertices       =         108
   number of vertices I own =         108
   number of elements       =         336
   number of leaf elements  =         172
   leaf elements I own      =         172
   number of levels         =           8
   degrees of freedom       =         838
   degrees of freedom I own =         838
   min and max degree       =           3          3

My Grid:
   number of vertices       =         195
   number of vertices I own =         195
   number of elements       =         676
   number of leaf elements  =         342
   leaf elements I own      =         342
   number of levels         =           9
   degrees of freedom       =        1615
   degrees of freedom I own =        1615
   min and max degree       =           3          4

My Grid:
   number of vertices       =         297
   number of vertices I own =         297
   number of elements       =        1076
   number of leaf elements  =         542
   leaf elements I own      =         542
   number of levels         =           9
   degrees of freedom       =        3143
   degrees of freedom I own =        3143
   min and max degree       =           3          5

My Grid:
   number of vertices       =         417
   number of vertices I own =         417
   number of elements       =        1544
   number of leaf elements  =         776
   leaf elements I own      =         776
   number of levels         =          10
   degrees of freedom       =        5408
   degrees of freedom I own =        5408
   min and max degree       =           3          6

My Grid:
   number of vertices       =         417
   number of vertices I own =         417
   number of elements       =        1544
   number of leaf elements  =         776
   leaf elements I own      =         776
   number of levels         =          10
   degrees of freedom       =        5408
   degrees of freedom I own =        5408
   min and max degree       =           3          6

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           7
termination condition:
  maximum equations achieved
---------------------------------------------------------
