---------------------------------------------------------
           PHAML   Version 1.8.0

Output from the master process
  PDE id is     0
  Number of slave processors is     4

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert           infinity
  max_eq                   5000
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    PHASES
  print_grid_who     MASTER
  print_linsys_when  NEVER
  print_error_when   NEVER
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            HP_ADAPTIVE
  edge_rule          MINIMUM_RULE
  hp_strategy        HP_SMOOTH_PRED
  sp_gamma_h          4.0000000000E+00
  sp_gamma_p          4.0000000000E-01
  refterm            DOUBLE_NEQ_SMOOTH
  derefine           false
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    false
  solver             MG_SOLVER
  mg_cycles          infinity
  mg_tol             MG_ERREST_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_FUDOP
---------------------------------------------------------

Total Grid:
   number of vertices      =           9
   number of leaf elements =           8
   number of levels        =           1
   degrees of freedom      =           9
   min and max degree      =           1          1

Total Grid:
   number of vertices      =          13
   number of leaf elements =          15
   number of levels        =           3
   degrees of freedom      =          20
   min and max degree      =           1          2

Total Grid:
   number of vertices      =          16
   number of leaf elements =          18
   number of levels        =           3
   degrees of freedom      =          40
   min and max degree      =           1          2

Total Grid:
   number of vertices      =          20
   number of leaf elements =          24
   number of levels        =           3
   degrees of freedom      =          75
   min and max degree      =           1          3

Total Grid:
   number of vertices      =          24
   number of leaf elements =          32
   number of levels        =           4
   degrees of freedom      =         168
   min and max degree      =           1          4

Total Grid:
   number of vertices      =          27
   number of leaf elements =          38
   number of levels        =           5
   degrees of freedom      =         310
   min and max degree      =           1          6

Total Grid:
   number of vertices      =          37
   number of leaf elements =          58
   number of levels        =           5
   degrees of freedom      =         656
   min and max degree      =           1          7

Total Grid:
   number of vertices      =          57
   number of leaf elements =          94
   number of levels        =           7
   degrees of freedom      =        1195
   min and max degree      =           1          7

Total Grid:
   number of vertices      =          85
   number of leaf elements =         144
   number of levels        =           7
   degrees of freedom      =        2305
   min and max degree      =           1          7

Total Grid:
   number of vertices      =         142
   number of leaf elements =         250
   number of levels        =           8
   degrees of freedom      =        4646
   min and max degree      =           2          8

Total Grid:
   number of vertices      =         155
   number of leaf elements =         276
   number of levels        =           9
   degrees of freedom      =        5185
   min and max degree      =           2          8

Total Grid:
   number of vertices      =         155
   number of leaf elements =         276
   number of levels        =           9
   degrees of freedom      =        5185
   min and max degree      =           2          8

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =          10
termination condition:
  maximum equations achieved
---------------------------------------------------------
