---------------------------------------------------------
           PHAML   Version 1.6.2

Output from the master process
  PDE id is     0
  Number of slave processors is     4

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert           infinity
  max_eq                   3500
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    PHASES
  print_grid_who     MASTER
  print_linsys_when  NEVER
  print_error_when   NEVER
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            HP_ADAPTIVE
  edge_rule          MINIMUM_RULE
  hp_strategy        HP_BIGGER_ERRIND
  refterm            DOUBLE_NEQ_SMOOTH
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    false
  solver             MG_SOLVER
  mg_cycles                  50
  mg_tol             MG_ERREST_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_FUDOP
---------------------------------------------------------

Total Grid:
   number of vertices      =           9
   number of leaf elements =           8
   number of levels        =           1
   degrees of freedom      =           9
   min and max degree      =           1          1

Total Grid:
   number of vertices      =           9
   number of leaf elements =           8
   number of levels        =           1
   degrees of freedom      =          20
   min and max degree      =           1          3

Total Grid:
   number of vertices      =          13
   number of leaf elements =          14
   number of levels        =           4
   degrees of freedom      =          44
   min and max degree      =           1          3

Total Grid:
   number of vertices      =          16
   number of leaf elements =          19
   number of levels        =           5
   degrees of freedom      =          94
   min and max degree      =           1          5

Total Grid:
   number of vertices      =          20
   number of leaf elements =          25
   number of levels        =           5
   degrees of freedom      =         170
   min and max degree      =           1          5

Total Grid:
   number of vertices      =          26
   number of leaf elements =          35
   number of levels        =           6
   degrees of freedom      =         303
   min and max degree      =           1          7

Total Grid:
   number of vertices      =          34
   number of leaf elements =          48
   number of levels        =           7
   degrees of freedom      =         611
   min and max degree      =           1          7

Total Grid:
   number of vertices      =          42
   number of leaf elements =          62
   number of levels        =           7
   degrees of freedom      =        1195
   min and max degree      =           3          8

Total Grid:
   number of vertices      =          61
   number of leaf elements =          99
   number of levels        =           7
   degrees of freedom      =        1918
   min and max degree      =           3          9

Total Grid:
   number of vertices      =          84
   number of leaf elements =         142
   number of levels        =           8
   degrees of freedom      =        2981
   min and max degree      =           3          9

Total Grid:
   number of vertices      =          99
   number of leaf elements =         169
   number of levels        =           8
   degrees of freedom      =        3773
   min and max degree      =           4         10

Total Grid:
   number of vertices      =          99
   number of leaf elements =         169
   number of levels        =           8
   degrees of freedom      =        3773
   min and max degree      =           4         10

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =          10
termination condition:
  maximum equations achieved
---------------------------------------------------------
