---------------------------------------------------------
           PHAML   Version 1.6.2

Output from the master process
  PDE id is     0
  Number of slave processors is     4

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert           infinity
  max_eq                   5000
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    PHASES
  print_grid_who     MASTER
  print_linsys_when  NEVER
  print_error_when   NEVER
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree                      3
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            HP_ADAPTIVE
  edge_rule          MINIMUM_RULE
  hp_strategy        HP_PRIOR2P_E
  refterm            DOUBLE_NEQ_SMOOTH
  derefine           false
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    false
  solver             MG_SOLVER
  mg_cycles          infinity
  mg_tol             MG_ERREST_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_FUDOP
---------------------------------------------------------

Total Grid:
   number of vertices      =           9
   number of leaf elements =           8
   number of levels        =           1
   degrees of freedom      =          49
   min and max degree      =           3          3

Total Grid:
   number of vertices      =          16
   number of leaf elements =          18
   number of levels        =           3
   degrees of freedom      =         100
   min and max degree      =           3          3

Total Grid:
   number of vertices      =          29
   number of leaf elements =          40
   number of levels        =           5
   degrees of freedom      =         205
   min and max degree      =           3          3

Total Grid:
   number of vertices      =          58
   number of leaf elements =          90
   number of levels        =           6
   degrees of freedom      =         442
   min and max degree      =           3          3

Total Grid:
   number of vertices      =         108
   number of leaf elements =         172
   number of levels        =           8
   degrees of freedom      =         838
   min and max degree      =           3          3

Total Grid:
   number of vertices      =         203
   number of leaf elements =         360
   number of levels        =          11
   degrees of freedom      =        1752
   min and max degree      =           3          4

Total Grid:
   number of vertices      =         258
   number of leaf elements =         463
   number of levels        =          11
   degrees of freedom      =        2344
   min and max degree      =           3          5

Total Grid:
   number of vertices      =         292
   number of leaf elements =         528
   number of levels        =          11
   degrees of freedom      =        2736
   min and max degree      =           3          5

Total Grid:
   number of vertices      =         347
   number of leaf elements =         635
   number of levels        =          15
   degrees of freedom      =        3663
   min and max degree      =           3          5

Total Grid:
   number of vertices      =         442
   number of leaf elements =         825
   number of levels        =          15
   degrees of freedom      =        4956
   min and max degree      =           3          6

Total Grid:
   number of vertices      =         477
   number of leaf elements =         894
   number of levels        =          15
   degrees of freedom      =        5562
   min and max degree      =           3          6

Total Grid:
   number of vertices      =         477
   number of leaf elements =         894
   number of levels        =          15
   degrees of freedom      =        5562
   min and max degree      =           3          6

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =          10
termination condition:
  maximum equations achieved
---------------------------------------------------------
