---------------------------------------------------------
           PHAML   Version 1.8.0

Output from slave number     1
  PDE id is     0
  Number of slave processors is     1

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert           infinity
  max_eq                   5000
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    PHASES
  print_grid_who     SLAVES
  print_linsys_when  NEVER
  print_error_when   NEVER
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            HP_ADAPTIVE
  edge_rule          MINIMUM_RULE
  hp_strategy        HP_COEF_ROOT
  refterm            DOUBLE_NEQ_SMOOTH
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    false
  solver             MG_SOLVER
  mg_cycles          infinity
  mg_tol             MG_ERREST_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_FUDOP
---------------------------------------------------------

My Grid:
   number of vertices       =           9
   number of vertices I own =           9
   number of elements       =           8
   number of leaf elements  =           8
   leaf elements I own      =           8
   number of levels         =           1
   degrees of freedom       =           9
   degrees of freedom I own =           9
   min and max degree       =           1          1

My Grid:
   number of vertices       =          11
   number of vertices I own =          11
   number of elements       =          16
   number of leaf elements  =          12
   leaf elements I own      =          12
   number of levels         =           2
   degrees of freedom       =          22
   degrees of freedom I own =          22
   min and max degree       =           1          2

My Grid:
   number of vertices       =          16
   number of vertices I own =          16
   number of elements       =          28
   number of leaf elements  =          18
   leaf elements I own      =          18
   number of levels         =           3
   degrees of freedom       =          36
   degrees of freedom I own =          36
   min and max degree       =           1          2

My Grid:
   number of vertices       =          25
   number of vertices I own =          25
   number of elements       =          60
   number of leaf elements  =          34
   leaf elements I own      =          34
   number of levels         =           4
   degrees of freedom       =          74
   degrees of freedom I own =          74
   min and max degree       =           1          2

My Grid:
   number of vertices       =          58
   number of vertices I own =          58
   number of elements       =         172
   number of leaf elements  =          90
   leaf elements I own      =          90
   number of levels         =           6
   degrees of freedom       =         196
   degrees of freedom I own =         196
   min and max degree       =           1          2

My Grid:
   number of vertices       =          76
   number of vertices I own =          76
   number of elements       =         236
   number of leaf elements  =         122
   leaf elements I own      =         122
   number of levels         =           7
   degrees of freedom       =         292
   degrees of freedom I own =         292
   min and max degree       =           1          3

My Grid:
   number of vertices       =          93
   number of vertices I own =          93
   number of elements       =         276
   number of leaf elements  =         142
   leaf elements I own      =         142
   number of levels         =           8
   degrees of freedom       =         632
   degrees of freedom I own =         632
   min and max degree       =           1          3

My Grid:
   number of vertices       =         158
   number of vertices I own =         158
   number of elements       =         536
   number of leaf elements  =         272
   leaf elements I own      =         272
   number of levels         =           8
   degrees of freedom       =        1236
   degrees of freedom I own =        1236
   min and max degree       =           1          3

My Grid:
   number of vertices       =         295
   number of vertices I own =         295
   number of elements       =        1012
   number of leaf elements  =         510
   leaf elements I own      =         510
   number of levels         =           9
   degrees of freedom       =        2510
   degrees of freedom I own =        2510
   min and max degree       =           1          4

My Grid:
   number of vertices       =         459
   number of vertices I own =         459
   number of elements       =        1664
   number of leaf elements  =         836
   leaf elements I own      =         836
   number of levels         =          10
   degrees of freedom       =        4676
   degrees of freedom I own =        4676
   min and max degree       =           1          5

My Grid:
   number of vertices       =         462
   number of vertices I own =         462
   number of elements       =        1676
   number of leaf elements  =         842
   leaf elements I own      =         842
   number of levels         =          10
   degrees of freedom       =        5328
   degrees of freedom I own =        5328
   min and max degree       =           1          5

My Grid:
   number of vertices       =         462
   number of vertices I own =         462
   number of elements       =        1676
   number of leaf elements  =         842
   leaf elements I own      =         842
   number of levels         =          10
   degrees of freedom       =        5328
   degrees of freedom I own =        5328
   min and max degree       =           1          5

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =          10
termination condition:
  maximum equations achieved
---------------------------------------------------------
