---------------------------------------------------------
           PHAML   Version 1.8.0

Output from slave number     1
  PDE id is     0
  Number of slave processors is     1

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert           infinity
  max_eq                   3000
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    19
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    PHASES
  print_grid_who     SLAVES
  print_linsys_when  NEVER
  print_error_when   NEVER
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            HP_ADAPTIVE
  edge_rule          MINIMUM_RULE
  hp_strategy        HP_NEXT3P
  refterm            DOUBLE_NEQ_SMOOTH
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    false
  solver             MG_SOLVER
  mg_cycles          infinity
  mg_tol             MG_ERREST_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_FUDOP
---------------------------------------------------------

My Grid:
   number of vertices       =           9
   number of vertices I own =           9
   number of elements       =           8
   number of leaf elements  =           8
   leaf elements I own      =           8
   number of levels         =           1
   degrees of freedom       =           9
   degrees of freedom I own =           9
   min and max degree       =           1          1

My Grid:
   number of vertices       =          11
   number of vertices I own =          11
   number of elements       =          16
   number of leaf elements  =          12
   leaf elements I own      =          12
   number of levels         =           2
   degrees of freedom       =          22
   degrees of freedom I own =          22
   min and max degree       =           1          2

My Grid:
   number of vertices       =          12
   number of vertices I own =          12
   number of elements       =          20
   number of leaf elements  =          14
   leaf elements I own      =          14
   number of levels         =           2
   degrees of freedom       =          37
   degrees of freedom I own =          37
   min and max degree       =           1          3

My Grid:
   number of vertices       =          16
   number of vertices I own =          16
   number of elements       =          32
   number of leaf elements  =          20
   leaf elements I own      =          20
   number of levels         =           3
   degrees of freedom       =          82
   degrees of freedom I own =          82
   min and max degree       =           1          4

My Grid:
   number of vertices       =          20
   number of vertices I own =          20
   number of elements       =          40
   number of leaf elements  =          24
   leaf elements I own      =          24
   number of levels         =           3
   degrees of freedom       =         162
   degrees of freedom I own =         162
   min and max degree       =           1          5

My Grid:
   number of vertices       =          25
   number of vertices I own =          25
   number of elements       =          60
   number of leaf elements  =          34
   leaf elements I own      =          34
   number of levels         =           4
   degrees of freedom       =         301
   degrees of freedom I own =         301
   min and max degree       =           1          5

My Grid:
   number of vertices       =          38
   number of vertices I own =          38
   number of elements       =         106
   number of leaf elements  =          57
   leaf elements I own      =          57
   number of levels         =           5
   degrees of freedom       =         577
   degrees of freedom I own =         577
   min and max degree       =           1          6

My Grid:
   number of vertices       =          65
   number of vertices I own =          65
   number of elements       =         200
   number of leaf elements  =         104
   leaf elements I own      =         104
   number of levels         =           7
   degrees of freedom       =        1162
   degrees of freedom I own =        1162
   min and max degree       =           1          6

My Grid:
   number of vertices       =         109
   number of vertices I own =         109
   number of elements       =         358
   number of leaf elements  =         183
   leaf elements I own      =         183
   number of levels         =           7
   degrees of freedom       =        2604
   degrees of freedom I own =        2604
   min and max degree       =           1          8

My Grid:
   number of vertices       =         124
   number of vertices I own =         124
   number of elements       =         408
   number of leaf elements  =         208
   leaf elements I own      =         208
   number of levels         =           7
   degrees of freedom       =        3001
   degrees of freedom I own =        3001
   min and max degree       =           1          8

My Grid:
   number of vertices       =         124
   number of vertices I own =         124
   number of elements       =         408
   number of leaf elements  =         208
   leaf elements I own      =         208
   number of levels         =           7
   degrees of freedom       =        3001
   degrees of freedom I own =        3001
   min and max degree       =           1          8

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           9
termination condition:
  maximum equations achieved
---------------------------------------------------------
