---------------------------------------------------------
           PHAML   Version 1.6.2

Output from slave number     1
  PDE id is     0
  Number of slave processors is     1

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert           infinity
  max_eq                   5000
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    PHASES
  print_grid_who     SLAVES
  print_linsys_when  NEVER
  print_error_when   NEVER
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            HP_ADAPTIVE
  edge_rule          MINIMUM_RULE
  hp_strategy        HP_SMOOTH_PRED
  sp_gamma_h          4.0000000000E+00
  sp_gamma_p          4.0000000000E-01
  refterm            DOUBLE_NEQ_SMOOTH
  derefine           false
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    false
  solver             MG_SOLVER
  mg_cycles          infinity
  mg_tol             MG_ERREST_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_FUDOP
---------------------------------------------------------

My Grid:
   number of vertices       =           9
   number of vertices I own =           9
   number of elements       =           8
   number of leaf elements  =           8
   leaf elements I own      =           8
   number of levels         =           1
   degrees of freedom       =           9
   degrees of freedom I own =           9
   min and max degree       =           1          1

My Grid:
   number of vertices       =          13
   number of vertices I own =          13
   number of elements       =          22
   number of leaf elements  =          15
   leaf elements I own      =          15
   number of levels         =           3
   degrees of freedom       =          20
   degrees of freedom I own =          20
   min and max degree       =           1          2

My Grid:
   number of vertices       =          16
   number of vertices I own =          16
   number of elements       =          28
   number of leaf elements  =          18
   leaf elements I own      =          18
   number of levels         =           3
   degrees of freedom       =          40
   degrees of freedom I own =          40
   min and max degree       =           1          2

My Grid:
   number of vertices       =          20
   number of vertices I own =          20
   number of elements       =          40
   number of leaf elements  =          24
   leaf elements I own      =          24
   number of levels         =           3
   degrees of freedom       =          75
   degrees of freedom I own =          75
   min and max degree       =           1          3

My Grid:
   number of vertices       =          24
   number of vertices I own =          24
   number of elements       =          56
   number of leaf elements  =          32
   leaf elements I own      =          32
   number of levels         =           4
   degrees of freedom       =         200
   degrees of freedom I own =         200
   min and max degree       =           1          5

My Grid:
   number of vertices       =          26
   number of vertices I own =          26
   number of elements       =          64
   number of leaf elements  =          36
   leaf elements I own      =          36
   number of levels         =           5
   degrees of freedom       =         296
   degrees of freedom I own =         296
   min and max degree       =           1          5

My Grid:
   number of vertices       =          35
   number of vertices I own =          35
   number of elements       =         100
   number of leaf elements  =          54
   leaf elements I own      =          54
   number of levels         =           5
   degrees of freedom       =         529
   degrees of freedom I own =         529
   min and max degree       =           1          6

My Grid:
   number of vertices       =          53
   number of vertices I own =          53
   number of elements       =         160
   number of leaf elements  =          84
   leaf elements I own      =          84
   number of levels         =           7
   degrees of freedom       =        1266
   degrees of freedom I own =        1266
   min and max degree       =           1          8

My Grid:
   number of vertices       =          78
   number of vertices I own =          78
   number of elements       =         248
   number of leaf elements  =         128
   leaf elements I own      =         128
   number of levels         =           7
   degrees of freedom       =        2128
   degrees of freedom I own =        2128
   min and max degree       =           1          9

My Grid:
   number of vertices       =         104
   number of vertices I own =         104
   number of elements       =         344
   number of leaf elements  =         176
   leaf elements I own      =         176
   number of levels         =           8
   degrees of freedom       =        3643
   degrees of freedom I own =        3643
   min and max degree       =           1          9

My Grid:
   number of vertices       =         130
   number of vertices I own =         130
   number of elements       =         440
   number of leaf elements  =         224
   leaf elements I own      =         224
   number of levels         =           8
   degrees of freedom       =        5040
   degrees of freedom I own =        5040
   min and max degree       =           1          9

My Grid:
   number of vertices       =         130
   number of vertices I own =         130
   number of elements       =         440
   number of leaf elements  =         224
   leaf elements I own      =         224
   number of levels         =           8
   degrees of freedom       =        5040
   degrees of freedom I own =        5040
   min and max degree       =           1          9

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =          10
termination condition:
  maximum equations achieved
---------------------------------------------------------
