---------------------------------------------------------
           PHAML   Version 1.8.0

Output from slave number     1
  PDE id is     0
  Number of slave processors is     1

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert           infinity
  max_eq                   5000
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    PHASES
  print_grid_who     SLAVES
  print_linsys_when  NEVER
  print_error_when   NEVER
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            HP_ADAPTIVE
  edge_rule          MINIMUM_RULE
  hp_strategy        HP_COEF_DECAY
  refterm            DOUBLE_NEQ_SMOOTH
  derefine           false
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    false
  solver             MG_SOLVER
  mg_cycles          infinity
  mg_tol             MG_ERREST_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_FUDOP
---------------------------------------------------------

My Grid:
   number of vertices       =           9
   number of vertices I own =           9
   number of elements       =           8
   number of leaf elements  =           8
   leaf elements I own      =           8
   number of levels         =           1
   degrees of freedom       =           9
   degrees of freedom I own =           9
   min and max degree       =           1          1

My Grid:
   number of vertices       =           9
   number of vertices I own =           9
   number of elements       =           8
   number of leaf elements  =           8
   leaf elements I own      =           8
   number of levels         =           1
   degrees of freedom       =          20
   degrees of freedom I own =          20
   min and max degree       =           1          3

My Grid:
   number of vertices       =          10
   number of vertices I own =          10
   number of elements       =          12
   number of leaf elements  =          10
   leaf elements I own      =          10
   number of levels         =           2
   degrees of freedom       =          40
   degrees of freedom I own =          40
   min and max degree       =           1          3

My Grid:
   number of vertices       =          14
   number of vertices I own =          14
   number of elements       =          24
   number of leaf elements  =          16
   leaf elements I own      =          16
   number of levels         =           3
   degrees of freedom       =          75
   degrees of freedom I own =          75
   min and max degree       =           2          3

My Grid:
   number of vertices       =          27
   number of vertices I own =          27
   number of elements       =          68
   number of leaf elements  =          38
   leaf elements I own      =          38
   number of levels         =           4
   degrees of freedom       =         180
   degrees of freedom I own =         180
   min and max degree       =           2          3

My Grid:
   number of vertices       =          43
   number of vertices I own =          43
   number of elements       =         112
   number of leaf elements  =          60
   leaf elements I own      =          60
   number of levels         =           5
   degrees of freedom       =         294
   degrees of freedom I own =         294
   min and max degree       =           2          3

My Grid:
   number of vertices       =          58
   number of vertices I own =          58
   number of elements       =         172
   number of leaf elements  =          90
   leaf elements I own      =          90
   number of levels         =           6
   degrees of freedom       =         585
   degrees of freedom I own =         585
   min and max degree       =           2          4

My Grid:
   number of vertices       =         111
   number of vertices I own =         111
   number of elements       =         376
   number of leaf elements  =         192
   leaf elements I own      =         192
   number of levels         =           7
   degrees of freedom       =        1162
   degrees of freedom I own =        1162
   min and max degree       =           2          5

My Grid:
   number of vertices       =         200
   number of vertices I own =         200
   number of elements       =         728
   number of leaf elements  =         368
   leaf elements I own      =         368
   number of levels         =           8
   degrees of freedom       =        2407
   degrees of freedom I own =        2407
   min and max degree       =           2          7

My Grid:
   number of vertices       =         308
   number of vertices I own =         308
   number of elements       =        1124
   number of leaf elements  =         566
   leaf elements I own      =         566
   number of levels         =           8
   degrees of freedom       =        5007
   degrees of freedom I own =        5007
   min and max degree       =           2          7

My Grid:
   number of vertices       =         308
   number of vertices I own =         308
   number of elements       =        1124
   number of leaf elements  =         566
   leaf elements I own      =         566
   number of levels         =           8
   degrees of freedom       =        5007
   degrees of freedom I own =        5007
   min and max degree       =           2          7

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           9
termination condition:
  maximum equations achieved
---------------------------------------------------------
