---------------------------------------------------------
           PHAML   Version 1.8.0

Output from the master process
  PDE id is     0
  Number of slave processors is     4

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                 1000
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    FREQUENTLY
  print_grid_who     MASTER_ALL
  print_linsys_when  NEVER
  print_error_when   NEVER
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree                      4
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ_SMOOTH
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  postbalance        BALANCE_EQUATIONS
  ignore_quad_err    false
  solver             MG_SOLVER
  mg_cycles          infinity
  mg_tol             MG_ERREST_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_FUDOP
---------------------------------------------------------

Individual Grids:
   number of vertices       =           9          9          9          9
   number of vertices I own =           9          9          9          9
   number of elements       =           8          8          8          8
   number of leaf elements  =           8          8          8          8
   leaf elements I own      =           8          8          8          8
   number of levels         =           1          1          1          1
   degrees of freedom       =          81         81         81         81
   degrees of freedom I own =          81         81         81         81
   min degree               =           4          4          4          4
   max degree               =           4          4          4          4

Total Grid:
   number of vertices      =           9
   number of leaf elements =           8
   number of levels        =           1
   degrees of freedom      =          81
   min and max degree      =           4          4

Individual Grids:
   number of vertices       =           9          9          9          9
   number of vertices I own =           9          9          9          9
   number of elements       =           8          8          8          8
   number of leaf elements  =           8          8          8          8
   leaf elements I own      =           8          8          8          8
   number of levels         =           1          1          1          1
   degrees of freedom       =          81         81         81         81
   degrees of freedom I own =          81         81         81         81
   min degree               =           4          4          4          4
   max degree               =           4          4          4          4

Total Grid:
   number of vertices      =           9
   number of leaf elements =           8
   number of levels        =           1
   degrees of freedom      =          81
   min and max degree      =           4          4

Individual Grids:
   number of vertices       =          16         16         16         16
   number of vertices I own =          16         16         16         16
   number of elements       =          32         32         32         32
   number of leaf elements  =          20         20         20         20
   leaf elements I own      =          20         20         20         20
   number of levels         =           3          3          3          3
   degrees of freedom       =         181        181        181        181
   degrees of freedom I own =         181        181        181        181
   min degree               =           4          4          4          4
   max degree               =           4          4          4          4

Total Grid:
   number of vertices      =          16
   number of leaf elements =          20
   number of levels        =           3
   degrees of freedom      =         181
   min and max degree      =           4          4

Individual Grids:
   number of vertices       =          16         16         16         16
   number of vertices I own =          16         16         16         16
   number of elements       =          32         32         32         32
   number of leaf elements  =          20         20         20         20
   leaf elements I own      =          20         20         20         20
   number of levels         =           3          3          3          3
   degrees of freedom       =         181        181        181        181
   degrees of freedom I own =         181        181        181        181
   min degree               =           4          4          4          4
   max degree               =           4          4          4          4

Total Grid:
   number of vertices      =          16
   number of leaf elements =          20
   number of levels        =           3
   degrees of freedom      =         181
   min and max degree      =           4          4

Individual Grids:
   number of vertices       =          16         16         16         16
   number of vertices I own =          16         16         16         16
   number of elements       =          32         32         32         32
   number of leaf elements  =          20         20         20         20
   leaf elements I own      =          20         20         20         20
   number of levels         =           3          3          3          3
   degrees of freedom       =         181        181        181        181
   degrees of freedom I own =         181        181        181        181
   min degree               =           4          4          4          4
   max degree               =           4          4          4          4

Total Grid:
   number of vertices      =          16
   number of leaf elements =          20
   number of levels        =           3
   degrees of freedom      =         181
   min and max degree      =           4          4

Individual Grids:
   number of vertices       =          28         28         28         28
   number of vertices I own =          28         28         28         28
   number of elements       =          72         72         72         72
   number of leaf elements  =          40         40         40         40
   leaf elements I own      =          40         40         40         40
   number of levels         =           4          4          4          4
   degrees of freedom       =         349        349        349        349
   degrees of freedom I own =         349        349        349        349
   min degree               =           4          4          4          4
   max degree               =           4          4          4          4

Total Grid:
   number of vertices      =          28
   number of leaf elements =          40
   number of levels        =           4
   degrees of freedom      =         349
   min and max degree      =           4          4

Individual Grids:
   number of vertices       =          28         28         28         28
   number of vertices I own =          28         28         28         28
   number of elements       =          72         72         72         72
   number of leaf elements  =          40         40         40         40
   leaf elements I own      =          40         40         40         40
   number of levels         =           4          4          4          4
   degrees of freedom       =         349        349        349        349
   degrees of freedom I own =         349        349        349        349
   min degree               =           4          4          4          4
   max degree               =           4          4          4          4

Total Grid:
   number of vertices      =          28
   number of leaf elements =          40
   number of levels        =           4
   degrees of freedom      =         349
   min and max degree      =           4          4

Individual Grids:
   number of vertices       =          28         28         28         28
   number of vertices I own =          28         28         28         28
   number of elements       =          72         72         72         72
   number of leaf elements  =          40         40         40         40
   leaf elements I own      =          40         40         40         40
   number of levels         =           4          4          4          4
   degrees of freedom       =         349        349        349        349
   degrees of freedom I own =         349        349        349        349
   min degree               =           4          4          4          4
   max degree               =           4          4          4          4

Total Grid:
   number of vertices      =          28
   number of leaf elements =          40
   number of levels        =           4
   degrees of freedom      =         349
   min and max degree      =           4          4

Individual Grids:
   number of vertices       =          51         51         51         51
   number of vertices I own =          51         51         51         51
   number of elements       =         144        144        144        144
   number of leaf elements  =          76         76         76         76
   leaf elements I own      =          76         76         76         76
   number of levels         =           5          5          5          5
   degrees of freedom       =         657        657        657        657
   degrees of freedom I own =         657        657        657        657
   min degree               =           4          4          4          4
   max degree               =           4          4          4          4

Total Grid:
   number of vertices      =          51
   number of leaf elements =          76
   number of levels        =           5
   degrees of freedom      =         657
   min and max degree      =           4          4

Individual Grids:
   number of vertices       =          51         51         51         51
   number of vertices I own =          51         51         51         51
   number of elements       =         144        144        144        144
   number of leaf elements  =          76         76         76         76
   leaf elements I own      =          76         76         76         76
   number of levels         =           5          5          5          5
   degrees of freedom       =         657        657        657        657
   degrees of freedom I own =         657        657        657        657
   min degree               =           4          4          4          4
   max degree               =           4          4          4          4

Total Grid:
   number of vertices      =          51
   number of leaf elements =          76
   number of levels        =           5
   degrees of freedom      =         657
   min and max degree      =           4          4

Individual Grids:
   number of vertices       =          51         51         51         51
   number of vertices I own =          51         51         51         51
   number of elements       =         144        144        144        144
   number of leaf elements  =          76         76         76         76
   leaf elements I own      =          76         76         76         76
   number of levels         =           5          5          5          5
   degrees of freedom       =         657        657        657        657
   degrees of freedom I own =         657        657        657        657
   min degree               =           4          4          4          4
   max degree               =           4          4          4          4

Total Grid:
   number of vertices      =          51
   number of leaf elements =          76
   number of levels        =           5
   degrees of freedom      =         657
   min and max degree      =           4          4

Individual Grids:
   number of vertices       =          94         94         94         94
   number of vertices I own =          94         94         94         94
   number of elements       =         300        300        300        300
   number of leaf elements  =         154        154        154        154
   leaf elements I own      =         154        154        154        154
   number of levels         =           7          7          7          7
   degrees of freedom       =        1297       1297       1297       1297
   degrees of freedom I own =        1297       1297       1297       1297
   min degree               =           4          4          4          4
   max degree               =           4          4          4          4

Total Grid:
   number of vertices      =          94
   number of leaf elements =         154
   number of levels        =           7
   degrees of freedom      =        1297
   min and max degree      =           4          4

Individual Grids:
   number of vertices       =          94         94         94         94
   number of vertices I own =          94         94         94         94
   number of elements       =         300        300        300        300
   number of leaf elements  =         154        154        154        154
   leaf elements I own      =         154        154        154        154
   number of levels         =           7          7          7          7
   degrees of freedom       =        1297       1297       1297       1297
   degrees of freedom I own =        1297       1297       1297       1297
   min degree               =           4          4          4          4
   max degree               =           4          4          4          4

Total Grid:
   number of vertices      =          94
   number of leaf elements =         154
   number of levels        =           7
   degrees of freedom      =        1297
   min and max degree      =           4          4

Individual Grids:
   number of vertices       =          94         94         94         94
   number of vertices I own =          94         94         94         94
   number of elements       =         300        300        300        300
   number of leaf elements  =         154        154        154        154
   leaf elements I own      =         154        154        154        154
   number of levels         =           7          7          7          7
   degrees of freedom       =        1297       1297       1297       1297
   degrees of freedom I own =        1297       1297       1297       1297
   min degree               =           4          4          4          4
   max degree               =           4          4          4          4

Total Grid:
   number of vertices      =          94
   number of leaf elements =         154
   number of levels        =           7
   degrees of freedom      =        1297
   min and max degree      =           4          4

Individual Grids:
   number of vertices       =         193        193        193        193
   number of vertices I own =         193        193        193        193
   number of elements       =         656        656        656        656
   number of leaf elements  =         332        332        332        332
   leaf elements I own      =         332        332        332        332
   number of levels         =           7          7          7          7
   degrees of freedom       =        2761       2761       2761       2761
   degrees of freedom I own =        2761       2761       2761       2761
   min degree               =           4          4          4          4
   max degree               =           4          4          4          4

Total Grid:
   number of vertices      =         193
   number of leaf elements =         332
   number of levels        =           7
   degrees of freedom      =        2761
   min and max degree      =           4          4

Individual Grids:
   number of vertices       =         193        193        193        193
   number of vertices I own =         193        193        193        193
   number of elements       =         656        656        656        656
   number of leaf elements  =         332        332        332        332
   leaf elements I own      =         332        332        332        332
   number of levels         =           7          7          7          7
   degrees of freedom       =        2761       2761       2761       2761
   degrees of freedom I own =        2761       2761       2761       2761
   min degree               =           4          4          4          4
   max degree               =           4          4          4          4

Total Grid:
   number of vertices      =         193
   number of leaf elements =         332
   number of levels        =           7
   degrees of freedom      =        2761
   min and max degree      =           4          4

Individual Grids:
   number of vertices       =          87        101        101         91
   number of vertices I own =          54         39         50         50
   number of elements       =         282        348        348        298
   number of leaf elements  =         145        178        178        153
   leaf elements I own      =          82         83         84         83
   number of levels         =           7          7          7          7
   degrees of freedom       =        1215       1469       1469       1279
   degrees of freedom I own =         714        648        707        692
   min degree               =           4          4          4          4
   max degree               =           4          4          4          4

Total Grid:
   number of vertices      =         193
   number of leaf elements =         332
   number of levels        =           7
   degrees of freedom      =        2761
   min and max degree      =           4          4

Individual Grids:
   number of vertices       =         153        186        178        154
   number of vertices I own =          98         85         97         89
   number of elements       =         542        682        650        546
   number of leaf elements  =         275        345        329        277
   leaf elements I own      =         160        184        170        162
   number of levels         =          10         10         10         10
   degrees of freedom       =        2259       2811       2683       2275
   degrees of freedom I own =        1358       1438       1411       1322
   min degree               =           4          4          4          4
   max degree               =           4          4          4          4

Total Grid:
   number of vertices      =         369
   number of leaf elements =         676
   number of levels        =          10
   degrees of freedom      =        5529
   min and max degree      =           4          4

Individual Grids:
   number of vertices       =         153        186        178        154
   number of vertices I own =          98         85         97         89
   number of elements       =         542        682        650        546
   number of leaf elements  =         275        345        329        277
   leaf elements I own      =         160        184        170        162
   number of levels         =          10         10         10         10
   degrees of freedom       =        2259       2811       2683       2275
   degrees of freedom I own =        1358       1438       1411       1322
   min degree               =           4          4          4          4
   max degree               =           4          4          4          4

Total Grid:
   number of vertices      =         369
   number of leaf elements =         676
   number of levels        =          10
   degrees of freedom      =        5529
   min and max degree      =           4          4

Individual Grids:
   number of vertices       =         153        186        178        154
   number of vertices I own =          98         85         97         89
   number of elements       =         542        682        650        546
   number of leaf elements  =         275        345        329        277
   leaf elements I own      =         160        184        170        162
   number of levels         =          10         10         10         10
   degrees of freedom       =        2259       2811       2683       2275
   degrees of freedom I own =        1358       1438       1411       1322
   min degree               =           4          4          4          4
   max degree               =           4          4          4          4

Total Grid:
   number of vertices      =         369
   number of leaf elements =         676
   number of levels        =          10
   degrees of freedom      =        5529
   min and max degree      =           4          4

Individual Grids:
   number of vertices       =         246        295        288        258
   number of vertices I own =         175        168        181        172
   number of elements       =         890       1108       1074        934
   number of leaf elements  =         449        558        541        471
   leaf elements I own      =         298        352        326        318
   number of levels         =          10         10         10         10
   degrees of freedom       =        3675       4525       4395       3855
   degrees of freedom I own =        2494       2778       2683       2590
   min degree               =           4          4          4          4
   max degree               =           4          4          4          4

Total Grid:
   number of vertices      =         696
   number of leaf elements =        1294
   number of levels        =          10
   degrees of freedom      =       10545
   min and max degree      =           4          4

Individual Grids:
   number of vertices       =         246        295        288        258
   number of vertices I own =         175        168        181        172
   number of elements       =         890       1108       1074        934
   number of leaf elements  =         449        558        541        471
   leaf elements I own      =         298        352        326        318
   number of levels         =          10         10         10         10
   degrees of freedom       =        3675       4525       4395       3855
   degrees of freedom I own =        2494       2778       2683       2590
   min degree               =           4          4          4          4
   max degree               =           4          4          4          4

Total Grid:
   number of vertices      =         696
   number of leaf elements =        1294
   number of levels        =          10
   degrees of freedom      =       10545
   min and max degree      =           4          4

Individual Grids:
   number of vertices       =         246        295        288        258
   number of vertices I own =         175        168        181        172
   number of elements       =         890       1108       1074        934
   number of leaf elements  =         449        558        541        471
   leaf elements I own      =         298        352        326        318
   number of levels         =          10         10         10         10
   degrees of freedom       =        3675       4525       4395       3855
   degrees of freedom I own =        2494       2778       2683       2590
   min degree               =           4          4          4          4
   max degree               =           4          4          4          4

Total Grid:
   number of vertices      =         696
   number of leaf elements =        1294
   number of levels        =          10
   degrees of freedom      =       10545
   min and max degree      =           4          4

Individual Grids:
   number of vertices       =         434        518        500        474
   number of vertices I own =         341        339        353        362
   number of elements       =        1620       1988       1908       1778
   number of leaf elements  =         814        998        958        893
   leaf elements I own      =         611        705        658        689
   number of levels         =          11         11         11         11
   degrees of freedom       =        6617       8057       7745       7251
   degrees of freedom I own =        5036       5580       5363       5576
   min degree               =           4          4          4          4
   max degree               =           4          4          4          4

Total Grid:
   number of vertices      =        1395
   number of leaf elements =        2663
   number of levels        =          11
   degrees of freedom      =       21555
   min and max degree      =           4          4

Individual Grids:
   number of vertices       =         434        518        500        474
   number of vertices I own =         341        339        353        362
   number of elements       =        1620       1988       1908       1778
   number of leaf elements  =         814        998        958        893
   leaf elements I own      =         611        705        658        689
   number of levels         =          11         11         11         11
   degrees of freedom       =        6617       8057       7745       7251
   degrees of freedom I own =        5036       5580       5363       5576
   min degree               =           4          4          4          4
   max degree               =           4          4          4          4

Total Grid:
   number of vertices      =        1395
   number of leaf elements =        2663
   number of levels        =          11
   degrees of freedom      =       21555
   min and max degree      =           4          4

Individual Grids:
   number of vertices       =         434        518        500        474
   number of vertices I own =         341        339        353        362
   number of elements       =        1620       1988       1908       1778
   number of leaf elements  =         814        998        958        893
   leaf elements I own      =         611        705        658        689
   number of levels         =          11         11         11         11
   degrees of freedom       =        6617       8057       7745       7251
   degrees of freedom I own =        5036       5580       5363       5576
   min degree               =           4          4          4          4
   max degree               =           4          4          4          4

Total Grid:
   number of vertices      =        1395
   number of leaf elements =        2663
   number of levels        =          11
   degrees of freedom      =       21555
   min and max degree      =           4          4

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           8
termination condition:
  maximum vertices achieved
---------------------------------------------------------
