---------------------------------------------------------
           PHAML   Version 1.8.0

Output from the master process
  PDE id is     0
  Number of slave processors is     4

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                 1000
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    PHASES
  print_grid_who     MASTER_ALL
  print_linsys_when  NEVER
  print_error_when   NEVER
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ_SMOOTH
  derefine           true
  partition_method   RTK
  postbalance        BALANCE_ELEMENTS
  ignore_quad_err    false
  solver             MG_SOLVER
  mg_cycles                  10
  mg_tol             MG_ERREST_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_FUDOP
---------------------------------------------------------

Individual Grids:
   number of vertices       =           9          9          9          9
   number of vertices I own =           9          9          9          9
   number of elements       =           8          8          8          8
   number of leaf elements  =           8          8          8          8
   leaf elements I own      =           8          8          8          8
   number of levels         =           1          1          1          1
   degrees of freedom       =           9          9          9          9
   degrees of freedom I own =           9          9          9          9
   min degree               =           1          1          1          1
   max degree               =           1          1          1          1

Total Grid:
   number of vertices      =           9
   number of leaf elements =           8
   number of levels        =           1
   degrees of freedom      =           9
   min and max degree      =           1          1

Individual Grids:
   number of vertices       =          27         27         27         27
   number of vertices I own =          27         27         27         27
   number of elements       =          68         68         68         68
   number of leaf elements  =          38         38         38         38
   leaf elements I own      =          38         38         38         38
   number of levels         =           4          4          4          4
   degrees of freedom       =          27         27         27         27
   degrees of freedom I own =          27         27         27         27
   min degree               =           1          1          1          1
   max degree               =           1          1          1          1

Total Grid:
   number of vertices      =          27
   number of leaf elements =          38
   number of levels        =           4
   degrees of freedom      =          27
   min and max degree      =           1          1

Individual Grids:
   number of vertices       =          38         38         38         38
   number of vertices I own =          38         38         38         38
   number of elements       =          96         96         96         96
   number of leaf elements  =          52         52         52         52
   leaf elements I own      =          52         52         52         52
   number of levels         =           6          6          6          6
   degrees of freedom       =          38         38         38         38
   degrees of freedom I own =          38         38         38         38
   min degree               =           1          1          1          1
   max degree               =           1          1          1          1

Total Grid:
   number of vertices      =          38
   number of leaf elements =          52
   number of levels        =           6
   degrees of freedom      =          38
   min and max degree      =           1          1

Individual Grids:
   number of vertices       =          74         74         74         74
   number of vertices I own =          74         74         74         74
   number of elements       =         228        228        228        228
   number of leaf elements  =         118        118        118        118
   leaf elements I own      =         118        118        118        118
   number of levels         =           7          7          7          7
   degrees of freedom       =          74         74         74         74
   degrees of freedom I own =          74         74         74         74
   min degree               =           1          1          1          1
   max degree               =           1          1          1          1

Total Grid:
   number of vertices      =          74
   number of leaf elements =         118
   number of levels        =           7
   degrees of freedom      =          74
   min and max degree      =           1          1

Individual Grids:
   number of vertices       =         145        145        145        145
   number of vertices I own =         145        145        145        145
   number of elements       =         484        484        484        484
   number of leaf elements  =         246        246        246        246
   leaf elements I own      =         246        246        246        246
   number of levels         =           8          8          8          8
   degrees of freedom       =         145        145        145        145
   degrees of freedom I own =         145        145        145        145
   min degree               =           1          1          1          1
   max degree               =           1          1          1          1

Total Grid:
   number of vertices      =         145
   number of leaf elements =         246
   number of levels        =           8
   degrees of freedom      =         145
   min and max degree      =           1          1

Individual Grids:
   number of vertices       =         133        160        160        133
   number of vertices I own =          97         78         91         92
   number of elements       =         456        564        564        456
   number of leaf elements  =         232        286        286        232
   leaf elements I own      =         163        155        152        166
   number of levels         =           9         10         10          9
   degrees of freedom       =         133        160        160        133
   degrees of freedom I own =          97         78         91         92
   min degree               =           1          1          1          1
   max degree               =           1          1          1          1

Total Grid:
   number of vertices      =         358
   number of leaf elements =         636
   number of levels        =          10
   degrees of freedom      =         358
   min and max degree      =           1          1

Individual Grids:
   number of vertices       =         223        256        251        222
   number of vertices I own =         163        159        176        164
   number of elements       =         810        938        918        806
   number of leaf elements  =         409        473        463        407
   leaf elements I own      =         307        308        307        308
   number of levels         =          11         11         11         11
   degrees of freedom       =         223        256        251        222
   degrees of freedom I own =         163        159        176        164
   min degree               =           1          1          1          1
   max degree               =           1          1          1          1

Total Grid:
   number of vertices      =         662
   number of leaf elements =        1230
   number of levels        =          11
   degrees of freedom      =         662
   min and max degree      =           1          1

Individual Grids:
   number of vertices       =         427        468        466        426
   number of vertices I own =         356        328        353        350
   number of elements       =        1588       1766       1756       1584
   number of leaf elements  =         798        887        882        796
   leaf elements I own      =         657        657        657        657
   number of levels         =          12         12         12         12
   degrees of freedom       =         427        468        466        426
   degrees of freedom I own =         356        328        353        350
   min degree               =           1          1          1          1
   max degree               =           1          1          1          1

Total Grid:
   number of vertices      =        1387
   number of leaf elements =        2628
   number of levels        =          12
   degrees of freedom      =        1387
   min and max degree      =           1          1

Individual Grids:
   number of vertices       =         427        468        466        426
   number of vertices I own =         356        328        353        350
   number of elements       =        1588       1766       1756       1584
   number of leaf elements  =         798        887        882        796
   leaf elements I own      =         657        657        657        657
   number of levels         =          12         12         12         12
   degrees of freedom       =         427        468        466        426
   degrees of freedom I own =         356        328        353        350
   min degree               =           1          1          1          1
   max degree               =           1          1          1          1

Total Grid:
   number of vertices      =        1387
   number of leaf elements =        2628
   number of levels        =          12
   degrees of freedom      =        1387
   min and max degree      =           1          1

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           7
termination condition:
  maximum vertices achieved
---------------------------------------------------------
