---------------------------------------------------------
           PHAML   Version 1.6.2

Output from the master process
  PDE id is     0
  Number of slave processors is     4

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                  500
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    PHASES
  print_grid_who     MASTER
  print_linsys_when  NEVER
  print_error_when   PHASES
  print_error_who    MASTER
  print_error_what   ENERGY_LINF_L2_ERR
  print_errest_what  NEVER
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ_SMOOTH
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    false
  solver             MG_SOLVER
  inc_quad_order             20
  mg_cycles                   5
  mg_tol             MG_ERREST_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_FUDOP
---------------------------------------------------------

Total Grid:
   number of vertices      =           9
   number of leaf elements =           8
   number of levels        =           1
   degrees of freedom      =           9
   min and max degree      =           1          1

Norms of error:
   energy norm of error       2.4721400648E+00
   Linf norm of error         9.0800311241E-01
   L2 norm of error           3.6016701275E-01

Total Grid:
   number of vertices      =          27
   number of leaf elements =          38
   number of levels        =           4
   degrees of freedom      =          27
   min and max degree      =           1          1

Norms of error:
   energy norm of error       1.4285569706E+00
      reduced by              5.7786247266E-01
   Linf norm of error         3.3611661781E-01
      reduced by              3.7017121771E-01
   L2 norm of error           1.0578481416E-01
      reduced by              2.9371044658E-01

Total Grid:
   number of vertices      =          38
   number of leaf elements =          52
   number of levels        =           6
   degrees of freedom      =          38
   min and max degree      =           1          1

Norms of error:
   energy norm of error       1.3336077598E+00
      reduced by              9.3353487979E-01
   Linf norm of error         2.5752446224E-01
      reduced by              7.6617593001E-01
   L2 norm of error           8.1209399251E-02
      reduced by              7.6768485058E-01

Total Grid:
   number of vertices      =          74
   number of leaf elements =         118
   number of levels        =           7
   degrees of freedom      =          74
   min and max degree      =           1          1

Norms of error:
   energy norm of error       8.1773185667E-01
      reduced by              6.1317268939E-01
   Linf norm of error         1.0030661140E-01
      reduced by              3.8950323603E-01
   L2 norm of error           2.7744720748E-02
      reduced by              3.4164420626E-01

Total Grid:
   number of vertices      =         145
   number of leaf elements =         246
   number of levels        =           8
   degrees of freedom      =         145
   min and max degree      =           1          1

Norms of error:
   energy norm of error       5.1482030191E-01
      reduced by              6.2957104790E-01
   Linf norm of error         3.8239676169E-02
      reduced by              3.8122787357E-01
   L2 norm of error           1.3344605233E-02
      reduced by              4.8097817795E-01

Total Grid:
   number of vertices      =         345
   number of leaf elements =         613
   number of levels        =          10
   degrees of freedom      =         345
   min and max degree      =           1          1

Norms of error:
   energy norm of error       3.3131270261E-01
      reduced by              3.2177509452E-01
   Linf norm of error         3.0011186791E-02
      reduced by              7.8481801622E-01
   L2 norm of error           5.2179518079E-03
      reduced by              1.9550791188E-01

Total Grid:
   number of vertices      =         632
   number of leaf elements =        1177
   number of levels        =          11
   degrees of freedom      =         632
   min and max degree      =           1          1

Norms of error:
   energy norm of error       2.4590921898E-01
      reduced by              7.4222695671E-01
   Linf norm of error         1.7724892191E-02
      reduced by              5.9060950551E-01
   L2 norm of error           3.4256361471E-03
      reduced by              6.5650973279E-01

Total Grid:
   number of vertices      =         632
   number of leaf elements =        1177
   number of levels        =          11
   degrees of freedom      =         632
   min and max degree      =           1          1

Norms of error:
   energy norm of error       2.4590921898E-01
   Linf norm of error         1.7724892191E-02
   L2 norm of error           3.4256361471E-03

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           6
termination condition:
  maximum vertices achieved
---------------------------------------------------------
