---------------------------------------------------------
           PHAML   Version 1.6.2

Output from the master process
  PDE id is     0
  Number of slave processors is     4

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                  500
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    PHASES
  print_grid_who     MASTER
  print_linsys_when  NEVER
  print_error_when   PHASES
  print_error_who    MASTER
  print_error_what   ENERGY_LINF_L2_ERR
  print_errest_what  NEVER
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ_SMOOTH
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    false
  solver             MG_SOLVER
  mg_cycles                   5
  mg_tol             MG_ERREST_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_FUDOP
---------------------------------------------------------

Total Grid:
   number of vertices      =           9
   number of leaf elements =           8
   number of levels        =           1
   degrees of freedom      =           9
   min and max degree      =           1          1

Norms of error:
   energy norm of error       3.9346210541E-01
   Linf norm of error         5.3440026367E-02
   L2 norm of error           2.0123009324E-02

Total Grid:
   number of vertices      =          18
   number of leaf elements =          23
   number of levels        =           4
   degrees of freedom      =          18
   min and max degree      =           1          1

Norms of error:
   energy norm of error       2.4364372993E-01
      reduced by              6.1923048389E-01
   Linf norm of error         4.3512417675E-02
      reduced by              8.1422897093E-01
   L2 norm of error           1.2204791438E-02
      reduced by              6.0650925720E-01

Total Grid:
   number of vertices      =          38
   number of leaf elements =          57
   number of levels        =           6
   degrees of freedom      =          38
   min and max degree      =           1          1

Norms of error:
   energy norm of error       1.4384899061E-01
      reduced by              5.9040711064E-01
   Linf norm of error         1.1732851604E-02
      reduced by              2.6964375300E-01
   L2 norm of error           4.2088580356E-03
      reduced by              3.4485292576E-01

Total Grid:
   number of vertices      =          82
   number of leaf elements =         136
   number of levels        =           7
   degrees of freedom      =          82
   min and max degree      =           1          1

Norms of error:
   energy norm of error       1.0863487461E-01
      reduced by              7.5520081269E-01
   Linf norm of error         1.2115759768E-02
      reduced by              1.0326355584E+00
   L2 norm of error           3.0295038293E-03
      reduced by              7.1979235312E-01

Total Grid:
   number of vertices      =         163
   number of leaf elements =         288
   number of levels        =           9
   degrees of freedom      =         163
   min and max degree      =           1          1

Norms of error:
   energy norm of error       7.0728264697E-02
      reduced by              6.5106408001E-01
   Linf norm of error         3.0475510563E-03
      reduced by              2.5153610791E-01
   L2 norm of error           1.0041970966E-03
      reduced by              3.3147246321E-01

Total Grid:
   number of vertices      =         332
   number of leaf elements =         609
   number of levels        =           9
   degrees of freedom      =         332
   min and max degree      =           1          1

Norms of error:
   energy norm of error       5.7350722769E-02
      reduced by              4.0543001454E-01
   Linf norm of error         3.2771271874E-03
      reduced by              1.0753313486E+00
   L2 norm of error           8.5218506089E-04
      reduced by              4.2431165344E-01

Total Grid:
   number of vertices      =         632
   number of leaf elements =        1192
   number of levels        =          11
   degrees of freedom      =         632
   min and max degree      =           1          1

Norms of error:
   energy norm of error       4.1726950491E-02
      reduced by              7.2757497161E-01
   Linf norm of error         3.2157994405E-03
      reduced by              9.8128612552E-01
   L2 norm of error           5.3144726303E-04
      reduced by              6.2362893628E-01

Total Grid:
   number of vertices      =         632
   number of leaf elements =        1192
   number of levels        =          11
   degrees of freedom      =         632
   min and max degree      =           1          1

Norms of error:
   energy norm of error       4.1726950491E-02
   Linf norm of error         3.2157994405E-03
   L2 norm of error           5.3144726303E-04

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           6
termination condition:
  maximum vertices achieved
---------------------------------------------------------
