---------------------------------------------------------
           PHAML   Version 1.6.2

Output from slave number     1
  PDE id is     0
  Number of slave processors is     1

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                  500
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    PHASES
  print_grid_who     SLAVES
  print_linsys_when  NEVER
  print_error_when   PHASES
  print_error_who    SLAVES
  print_error_what   ENERGY_LINF_L2_ERR
  print_errest_what  NEVER
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ_SMOOTH
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    false
  solver             MG_SOLVER
  mg_cycles                   5
  mg_tol             MG_ERREST_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_FUDOP
---------------------------------------------------------

My Grid:
   number of vertices       =           9
   number of vertices I own =           9
   number of elements       =           8
   number of leaf elements  =           8
   leaf elements I own      =           8
   number of levels         =           1
   degrees of freedom       =           9
   degrees of freedom I own =           9
   min and max degree       =           1          1

Norms of error:
   energy norm of error       3.9346210541E-01
   Linf norm of error         5.3440026367E-02
   L2 norm of error           2.0123009324E-02

My Grid:
   number of vertices       =          18
   number of vertices I own =          18
   number of elements       =          38
   number of leaf elements  =          23
   leaf elements I own      =          23
   number of levels         =           4
   degrees of freedom       =          18
   degrees of freedom I own =          18
   min and max degree       =           1          1

Norms of error:
   energy norm of error       2.4364372993E-01
      reduced by              6.1923048389E-01
   Linf norm of error         4.3512417675E-02
      reduced by              8.1422897093E-01
   L2 norm of error           1.2204791438E-02
      reduced by              6.0650925720E-01

My Grid:
   number of vertices       =          38
   number of vertices I own =          38
   number of elements       =         106
   number of leaf elements  =          57
   leaf elements I own      =          57
   number of levels         =           6
   degrees of freedom       =          38
   degrees of freedom I own =          38
   min and max degree       =           1          1

Norms of error:
   energy norm of error       1.4384899287E-01
      reduced by              5.9040711989E-01
   Linf norm of error         1.1733078695E-02
      reduced by              2.6964897200E-01
   L2 norm of error           4.2087772244E-03
      reduced by              3.4484630449E-01

My Grid:
   number of vertices       =          82
   number of vertices I own =          82
   number of elements       =         264
   number of leaf elements  =         136
   leaf elements I own      =         136
   number of levels         =           7
   degrees of freedom       =          82
   degrees of freedom I own =          82
   min and max degree       =           1          1

Norms of error:
   energy norm of error       1.0863487461E-01
      reduced by              7.5520080085E-01
   Linf norm of error         1.2115759754E-02
      reduced by              1.0326155708E+00
   L2 norm of error           3.0295038254E-03
      reduced by              7.1980617263E-01

My Grid:
   number of vertices       =         163
   number of vertices I own =         163
   number of elements       =         568
   number of leaf elements  =         288
   leaf elements I own      =         288
   number of levels         =           9
   degrees of freedom       =         163
   degrees of freedom I own =         163
   min and max degree       =           1          1

Norms of error:
   energy norm of error       7.0728264697E-02
      reduced by              6.5106408001E-01
   Linf norm of error         3.0475510567E-03
      reduced by              2.5153610823E-01
   L2 norm of error           1.0041970966E-03
      reduced by              3.3147246364E-01

My Grid:
   number of vertices       =         317
   number of vertices I own =         317
   number of elements       =        1152
   number of leaf elements  =         580
   leaf elements I own      =         580
   number of levels         =           9
   degrees of freedom       =         317
   degrees of freedom I own =         317
   min and max degree       =           1          1

Norms of error:
   energy norm of error       5.6565780693E-02
      reduced by              7.9976203198E-01
   Linf norm of error         3.3944811576E-03
      reduced by              1.1138389790E+00
   L2 norm of error           8.2892633737E-04
      reduced by              8.2546179447E-01

My Grid:
   number of vertices       =         652
   number of vertices I own =         652
   number of elements       =        2452
   number of leaf elements  =        1230
   leaf elements I own      =        1230
   number of levels         =          11
   degrees of freedom       =         652
   degrees of freedom I own =         652
   min and max degree       =           1          1

Norms of error:
   energy norm of error       3.8805857065E-02
      reduced by              6.8603061055E-01
   Linf norm of error         2.5641327461E-03
      reduced by              7.5538281906E-01
   L2 norm of error           4.4810620275E-04
      reduced by              5.4058627715E-01

My Grid:
   number of vertices       =         652
   number of vertices I own =         652
   number of elements       =        2452
   number of leaf elements  =        1230
   leaf elements I own      =        1230
   number of levels         =          11
   degrees of freedom       =         652
   degrees of freedom I own =         652
   min and max degree       =           1          1

Norms of error:
   energy norm of error       3.8805857065E-02
   Linf norm of error         2.5641327461E-03
   L2 norm of error           4.4810620275E-04

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           6
termination condition:
  maximum vertices achieved
---------------------------------------------------------
