---------------------------------------------------------
           PHAML   Version 1.6.2

Output from the master process
  PDE id is     0
  Number of slave processors is     1

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                  500
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    PHASES
  print_grid_who     MASTER
  print_linsys_when  NEVER
  print_error_when   PHASES
  print_error_who    MASTER
  print_error_what   ENERGY_LINF_L2_ERR
  print_errest_what  NEVER
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ_SMOOTH
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    true
  solver             LAPACK_INDEFINITE_SOLVER
---------------------------------------------------------

Total Grid:
   number of vertices      =           9
   number of leaf elements =           8
   number of levels        =           1
   degrees of freedom      =           9
   min and max degree      =           1          1

Norms of error:
   energy norm of error       2.5170345544E+00
   Linf norm of error         8.4136285745E-01
   L2 norm of error           3.4264553346E-01

Total Grid:
   number of vertices      =          29
   number of leaf elements =          40
   number of levels        =           5
   degrees of freedom      =          29
   min and max degree      =           1          1

Norms of error:
   energy norm of error       1.4536078698E+00
      reduced by              5.7750811059E-01
   Linf norm of error         2.5719284116E-01
      reduced by              3.0568599372E-01
   L2 norm of error           8.5883795995E-02
      reduced by              2.5064910413E-01

Total Grid:
   number of vertices      =          36
   number of leaf elements =          48
   number of levels        =           6
   degrees of freedom      =          36
   min and max degree      =           1          1

Norms of error:
   energy norm of error       1.4261143728E+00
      reduced by              9.8108602907E-01
   Linf norm of error         2.5719334345E-01
      reduced by              1.0000019530E+00
   L2 norm of error           8.5787341950E-02
      reduced by              9.9887692383E-01

Total Grid:
   number of vertices      =          81
   number of leaf elements =         132
   number of levels        =           7
   degrees of freedom      =          81
   min and max degree      =           1          1

Norms of error:
   energy norm of error       8.1453292089E-01
      reduced by              5.7115539708E-01
   Linf norm of error         9.8635920154E-02
      reduced by              3.8350883747E-01
   L2 norm of error           2.5740560363E-02
      reduced by              3.0005079745E-01

Total Grid:
   number of vertices      =         145
   number of leaf elements =         246
   number of levels        =           8
   degrees of freedom      =         145
   min and max degree      =           1          1

Norms of error:
   energy norm of error       5.1477469330E-01
      reduced by              6.3198758466E-01
   Linf norm of error         3.8152123508E-02
      reduced by              3.8679746129E-01
   L2 norm of error           1.2586449672E-02
      reduced by              4.8897341372E-01

Total Grid:
   number of vertices      =         358
   number of leaf elements =         636
   number of levels        =          10
   degrees of freedom      =         358
   min and max degree      =           1          1

Norms of error:
   energy norm of error       3.2063129467E-01
      reduced by              6.2285753134E-01
   Linf norm of error         3.0016950103E-02
      reduced by              7.8677010197E-01
   L2 norm of error           4.7039602748E-03
      reduced by              3.7373210059E-01

Total Grid:
   number of vertices      =         638
   number of leaf elements =        1188
   number of levels        =          11
   degrees of freedom      =         638
   min and max degree      =           1          1

Norms of error:
   energy norm of error       2.4525954335E-01
      reduced by              7.6492702811E-01
   Linf norm of error         1.0117907170E-02
      reduced by              3.3707312487E-01
   L2 norm of error           3.1466490752E-03
      reduced by              6.6893614984E-01

Total Grid:
   number of vertices      =         638
   number of leaf elements =        1188
   number of levels        =          11
   degrees of freedom      =         638
   min and max degree      =           1          1

Norms of error:
   energy norm of error       2.4525954335E-01
   Linf norm of error         1.0117907170E-02
   L2 norm of error           3.1466490752E-03

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           6
termination condition:
  maximum vertices achieved
---------------------------------------------------------
