---------------------------------------------------------
           PHAML   Version 1.8.0

Output from slave number     1
  PDE id is     1
  Number of slave processors is     1

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                  500
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    PHASES
  print_grid_who     SLAVES
  print_linsys_when  NEVER
  print_error_when   PHASES
  print_error_who    SLAVES
  print_error_what   ENERGY_LINF_L2_ERR
  print_errest_what  NEVER
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ_SMOOTH
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    true
  solver             MUMPS_NONSYM_SOLVER
---------------------------------------------------------

My Grid:
   number of vertices       =           9
   number of vertices I own =           9
   number of elements       =           8
   number of leaf elements  =           8
   leaf elements I own      =           8
   number of levels         =           1
   degrees of freedom       =           9
   degrees of freedom I own =           9
   min and max degree       =           1          1

Norms of error:
   energy norm of error       2.4861373529E+00
   Linf norm of error         8.6678053008E-01
   L2 norm of error           3.4682818904E-01

My Grid:
   number of vertices       =          27
   number of vertices I own =          27
   number of elements       =          68
   number of leaf elements  =          38
   leaf elements I own      =          38
   number of levels         =           4
   degrees of freedom       =          27
   degrees of freedom I own =          27
   min and max degree       =           1          1

Norms of error:
   energy norm of error       1.4289894006E+00
      reduced by              5.7478296559E-01
   Linf norm of error         3.3502401682E-01
      reduced by              3.8651539253E-01
   L2 norm of error           1.0339315452E-01
      reduced by              2.9811058556E-01

My Grid:
   number of vertices       =          36
   number of vertices I own =          36
   number of elements       =          88
   number of leaf elements  =          48
   leaf elements I own      =          48
   number of levels         =           6
   degrees of freedom       =          36
   degrees of freedom I own =          36
   min and max degree       =           1          1

Norms of error:
   energy norm of error       1.4256031121E+00
      reduced by              9.9763029136E-01
   Linf norm of error         2.5754586882E-01
      reduced by              7.6873852586E-01
   L2 norm of error           8.8710368664E-02
      reduced by              8.5799073520E-01

My Grid:
   number of vertices       =          81
   number of vertices I own =          81
   number of elements       =         256
   number of leaf elements  =         132
   leaf elements I own      =         132
   number of levels         =           7
   degrees of freedom       =          81
   degrees of freedom I own =          81
   min and max degree       =           1          1

Norms of error:
   energy norm of error       8.1449084065E-01
      reduced by              5.7133071173E-01
   Linf norm of error         1.0003637355E-01
      reduced by              3.8842158103E-01
   L2 norm of error           2.6717584661E-02
      reduced by              3.0117769843E-01

My Grid:
   number of vertices       =         145
   number of vertices I own =         145
   number of elements       =         484
   number of leaf elements  =         246
   leaf elements I own      =         246
   number of levels         =           8
   degrees of freedom       =         145
   degrees of freedom I own =         145
   min and max degree       =           1          1

Norms of error:
   energy norm of error       5.1476957393E-01
      reduced by              6.3201395061E-01
   Linf norm of error         3.8208434176E-02
      reduced by              3.8194541463E-01
   L2 norm of error           1.3105597805E-02
      reduced by              4.9052330035E-01

My Grid:
   number of vertices       =         358
   number of vertices I own =         358
   number of elements       =        1264
   number of leaf elements  =         636
   leaf elements I own      =         636
   number of levels         =          10
   degrees of freedom       =         358
   degrees of freedom I own =         358
   min and max degree       =           1          1

Norms of error:
   energy norm of error       3.2066443471E-01
      reduced by              6.2292810405E-01
   Linf norm of error         3.0017068663E-02
      reduced by              7.8561368217E-01
   L2 norm of error           4.8765495446E-03
      reduced by              3.7209668853E-01

My Grid:
   number of vertices       =         638
   number of vertices I own =         638
   number of elements       =        2368
   number of leaf elements  =        1188
   leaf elements I own      =        1188
   number of levels         =          11
   degrees of freedom       =         638
   degrees of freedom I own =         638
   min and max degree       =           1          1

Norms of error:
   energy norm of error       2.4526697540E-01
      reduced by              7.6487115142E-01
   Linf norm of error         1.0119481562E-02
      reduced by              3.3712424342E-01
   L2 norm of error           3.2684972803E-03
      reduced by              6.7024793871E-01

My Grid:
   number of vertices       =         638
   number of vertices I own =         638
   number of elements       =        2368
   number of leaf elements  =        1188
   leaf elements I own      =        1188
   number of levels         =          11
   degrees of freedom       =         638
   degrees of freedom I own =         638
   min and max degree       =           1          1

Norms of error:
   energy norm of error       2.4526697540E-01
   Linf norm of error         1.0119481562E-02
   L2 norm of error           3.2684972803E-03

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           6
termination condition:
  maximum vertices achieved
---------------------------------------------------------
