---------------------------------------------------------
           PHAML   Version 1.8.0

Output from the master process
  PDE id is     1
  Number of slave processors is     4

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                  500
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    PHASES
  print_grid_who     MASTER
  print_linsys_when  NEVER
  print_error_when   PHASES
  print_error_who    MASTER
  print_error_what   ENERGY_LINF_L2_ERR
  print_errest_what  NEVER
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ_SMOOTH
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    true
  solver             MUMPS_NONSYM_SOLVER
---------------------------------------------------------

Total Grid:
   number of vertices      =           9
   number of leaf elements =           8
   number of levels        =           1
   degrees of freedom      =           9
   min and max degree      =           1          1

Norms of error:
   energy norm of error       2.4861373529E+00
   Linf norm of error         8.6678053008E-01
   L2 norm of error           3.4682818904E-01

Total Grid:
   number of vertices      =          27
   number of leaf elements =          38
   number of levels        =           4
   degrees of freedom      =          27
   min and max degree      =           1          1

Norms of error:
   energy norm of error       1.4289894006E+00
      reduced by              5.7478296559E-01
   Linf norm of error         3.3502401682E-01
      reduced by              3.8651539253E-01
   L2 norm of error           1.0339315452E-01
      reduced by              2.9811058556E-01

Total Grid:
   number of vertices      =          36
   number of leaf elements =          48
   number of levels        =           6
   degrees of freedom      =          36
   min and max degree      =           1          1

Norms of error:
   energy norm of error       1.4256031121E+00
      reduced by              9.9763029136E-01
   Linf norm of error         2.5754586882E-01
      reduced by              7.6873852586E-01
   L2 norm of error           8.8710368664E-02
      reduced by              8.5799073520E-01

Total Grid:
   number of vertices      =          81
   number of leaf elements =         132
   number of levels        =           7
   degrees of freedom      =          81
   min and max degree      =           1          1

Norms of error:
   energy norm of error       8.1449084065E-01
      reduced by              5.7133071173E-01
   Linf norm of error         1.0003637355E-01
      reduced by              3.8842158103E-01
   L2 norm of error           2.6717584661E-02
      reduced by              3.0117769843E-01

Total Grid:
   number of vertices      =         145
   number of leaf elements =         246
   number of levels        =           8
   degrees of freedom      =         145
   min and max degree      =           1          1

Norms of error:
   energy norm of error       5.1476957393E-01
      reduced by              6.3201395061E-01
   Linf norm of error         3.8208434176E-02
      reduced by              3.8194541463E-01
   L2 norm of error           1.3105597805E-02
      reduced by              4.9052330035E-01

Total Grid:
   number of vertices      =         345
   number of leaf elements =         613
   number of levels        =          10
   degrees of freedom      =         345
   min and max degree      =           1          1

Norms of error:
   energy norm of error       3.3127091478E-01
      reduced by              3.2176621498E-01
   Linf norm of error         3.0017047254E-02
      reduced by              7.8561312187E-01
   L2 norm of error           5.1150790705E-03
      reduced by              1.9514863597E-01

Total Grid:
   number of vertices      =         634
   number of leaf elements =        1183
   number of levels        =          11
   degrees of freedom      =         634
   min and max degree      =           1          1

Norms of error:
   energy norm of error       2.4557474086E-01
      reduced by              7.4131090266E-01
   Linf norm of error         1.0651830446E-02
      reduced by              3.5485936895E-01
   L2 norm of error           3.3028356222E-03
      reduced by              6.4570568249E-01

Total Grid:
   number of vertices      =         634
   number of leaf elements =        1183
   number of levels        =          11
   degrees of freedom      =         634
   min and max degree      =           1          1

Norms of error:
   energy norm of error       2.4557474086E-01
   Linf norm of error         1.0651830446E-02
   L2 norm of error           3.3028356222E-03

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           6
termination condition:
  maximum vertices achieved
---------------------------------------------------------
