---------------------------------------------------------
           PHAML   Version 1.8.0

Output from the master process
  PDE id is     0
  Number of slave processors is     4

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                  500
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    PHASES
  print_grid_who     MASTER
  print_linsys_when  NEVER
  print_error_when   PHASES
  print_error_who    MASTER
  print_error_what   ENERGY_LINF_L2_ERR
  print_errest_what  NEVER
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ_SMOOTH
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    true
  solver             PETSC_CG_SOLVER
  preconditioner     PETSC_SOR_PRECONDITION
  petsc_matrix_free  false
  petsc_rtol           1.0000000000E-10
  petsc_atol         default
  petsc_dtol         default
  petsc_maxits       default
  petsc_sor_omega    default
  petsc_sor_its      default
  petsc_sor_lits     default
---------------------------------------------------------

Total Grid:
   number of vertices      =           9
   number of leaf elements =           8
   number of levels        =           1
   degrees of freedom      =           9
   min and max degree      =           1          1

Norms of error:
   energy norm of error       2.4791277665E+00
   Linf norm of error         8.7914044620E-01
   L2 norm of error           3.5000011056E-01

Total Grid:
   number of vertices      =          27
   number of leaf elements =          38
   number of levels        =           4
   degrees of freedom      =          27
   min and max degree      =           1          1

Norms of error:
   energy norm of error       1.4285608772E+00
      reduced by              5.7623527780E-01
   Linf norm of error         3.3631662747E-01
      reduced by              3.8255164908E-01
   L2 norm of error           1.0582747319E-01
      reduced by              3.0236411359E-01

Total Grid:
   number of vertices      =          38
   number of leaf elements =          52
   number of levels        =           6
   degrees of freedom      =          38
   min and max degree      =           1          1

Norms of error:
   energy norm of error       1.3336106253E+00
      reduced by              9.3353433272E-01
   Linf norm of error         2.5754956769E-01
      reduced by              7.6579492853E-01
   L2 norm of error           8.1304197609E-02
      reduced by              7.6827117914E-01

Total Grid:
   number of vertices      =          74
   number of leaf elements =         118
   number of levels        =           7
   degrees of freedom      =          74
   min and max degree      =           1          1

Norms of error:
   energy norm of error       8.1773933945E-01
      reduced by              6.1317698281E-01
   Linf norm of error         1.0042930999E-01
      reduced by              3.8994167566E-01
   L2 norm of error           2.7878277941E-02
      reduced by              3.4288854403E-01

Total Grid:
   number of vertices      =         145
   number of leaf elements =         246
   number of levels        =           8
   degrees of freedom      =         145
   min and max degree      =           1          1

Norms of error:
   energy norm of error       5.1482098270E-01
      reduced by              6.2956611950E-01
   Linf norm of error         3.8245739773E-02
      reduced by              3.8082248873E-01
   L2 norm of error           1.3402251692E-02
      reduced by              4.8074173450E-01

Total Grid:
   number of vertices      =         345
   number of leaf elements =         613
   number of levels        =          10
   degrees of freedom      =         345
   min and max degree      =           1          1

Norms of error:
   energy norm of error       1.1458032057E+01
      reduced by              1.1128171191E+01
   Linf norm of error         5.1125134258E+00
      reduced by              1.3367537028E+02
   L2 norm of error           8.6335282702E-02
      reduced by              3.2209245388E+00

Total Grid:
   number of vertices      =         434
   number of leaf elements =         802
   number of levels        =          19
   degrees of freedom      =         434
   min and max degree      =           1          1

Norms of error:
   energy norm of error       3.2552482228E-01
      reduced by              2.8410186031E-02
   Linf norm of error         3.0012061209E-02
      reduced by              5.8703144050E-03
   L2 norm of error           5.2029765432E-03
      reduced by              6.0264776814E-02

Total Grid:
   number of vertices      =        1236
   number of leaf elements =        2348
   number of levels        =          19
   degrees of freedom      =        1236
   min and max degree      =           1          1

Norms of error:
   energy norm of error       1.8082696962E-01
      reduced by              5.5549364362E-01
   Linf norm of error         8.3805919944E-03
      reduced by              2.7924080042E-01
   L2 norm of error           1.7038891650E-03
      reduced by              3.2748353771E-01

Total Grid:
   number of vertices      =        1236
   number of leaf elements =        2348
   number of levels        =          19
   degrees of freedom      =        1236
   min and max degree      =           1          1

Norms of error:
   energy norm of error       1.8082696962E-01
   Linf norm of error         8.3805919944E-03
   L2 norm of error           1.7038891650E-03

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           7
termination condition:
  maximum vertices achieved
---------------------------------------------------------
