---------------------------------------------------------
           PHAML   Version 1.6.2

Output from the master process
  PDE id is     0
  Number of slave processors is     4

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                  500
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    PHASES
  print_grid_who     MASTER
  print_linsys_when  NEVER
  print_error_when   PHASES
  print_error_who    MASTER
  print_error_what   ENERGY_LINF_L2_ERR
  print_errest_what  NEVER
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree                      4
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ_SMOOTH
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    true
  solver             PETSC_CG_SOLVER
  preconditioner     PETSC_SOR_PRECONDITION
  petsc_matrix_free  false
  petsc_rtol           1.0000000000E-10
  petsc_atol         default
  petsc_dtol         default
  petsc_maxits       default
  petsc_sor_omega    default
  petsc_sor_its      default
  petsc_sor_lits     default
---------------------------------------------------------

Total Grid:
   number of vertices      =           9
   number of leaf elements =           8
   number of levels        =           1
   degrees of freedom      =          81
   min and max degree      =           4          4

Norms of error:
   energy norm of error       5.4351354768E-02
   Linf norm of error         1.0764133619E-02
   L2 norm of error           4.3498770418E-03

Total Grid:
   number of vertices      =          16
   number of leaf elements =          20
   number of levels        =           3
   degrees of freedom      =         181
   min and max degree      =           4          4

Norms of error:
   energy norm of error       1.5675043625E-02
      reduced by              2.8840207741E-01
   Linf norm of error         5.0396380578E-03
      reduced by              4.6818798762E-01
   L2 norm of error           8.6422250307E-04
      reduced by              1.9867745566E-01

Total Grid:
   number of vertices      =          28
   number of leaf elements =          40
   number of levels        =           4
   degrees of freedom      =         349
   min and max degree      =           4          4

Norms of error:
   energy norm of error       3.3910488124E-03
      reduced by              2.1633425039E-01
   Linf norm of error         4.1139235162E-04
      reduced by              8.1631328857E-02
   L2 norm of error           1.2138113631E-04
      reduced by              1.4045125634E-01

Total Grid:
   number of vertices      =          51
   number of leaf elements =          76
   number of levels        =           5
   degrees of freedom      =         657
   min and max degree      =           4          4

Norms of error:
   energy norm of error       5.6559898786E-04
      reduced by              1.6679175652E-01
   Linf norm of error         5.8530715741E-05
      reduced by              1.4227468136E-01
   L2 norm of error           1.6251858042E-05
      reduced by              1.3389113445E-01

Total Grid:
   number of vertices      =          94
   number of leaf elements =         154
   number of levels        =           7
   degrees of freedom      =        1297
   min and max degree      =           4          4

Norms of error:
   energy norm of error       1.8147028180E-04
      reduced by              3.2084619261E-01
   Linf norm of error         1.2339343933E-05
      reduced by              2.1081826484E-01
   L2 norm of error           3.4898428532E-06
      reduced by              2.1473500717E-01

Total Grid:
   number of vertices      =         193
   number of leaf elements =         332
   number of levels        =           7
   degrees of freedom      =        2761
   min and max degree      =           4          4

Norms of error:
   energy norm of error       2.5633855963E-05
      reduced by              1.4125649505E-01
   Linf norm of error         1.5330848749E-06
      reduced by              1.2424362943E-01
   L2 norm of error           3.6953618170E-07
      reduced by              1.0588906070E-01

Total Grid:
   number of vertices      =         376
   number of leaf elements =         692
   number of levels        =          11
   degrees of freedom      =        5653
   min and max degree      =           4          4

Norms of error:
   energy norm of error       9.7581065159E-06
      reduced by              1.9033629841E-01
   Linf norm of error         8.9455860075E-07
      reduced by              5.8350233270E-01
   L2 norm of error           1.0330965707E-07
      reduced by              1.3978287132E-01

Total Grid:
   number of vertices      =         708
   number of leaf elements =        1315
   number of levels        =          11
   degrees of freedom      =       10719
   min and max degree      =           4          4

Norms of error:
   energy norm of error       1.8524586080E-06
      reduced by              1.8983791630E-01
   Linf norm of error         7.1060707790E-08
      reduced by              7.9436615702E-02
   L2 norm of error           1.5434488758E-08
      reduced by              1.4940025160E-01

Total Grid:
   number of vertices      =         708
   number of leaf elements =        1315
   number of levels        =          11
   degrees of freedom      =       10719
   min and max degree      =           4          4

Norms of error:
   energy norm of error       1.8524586080E-06
   Linf norm of error         7.1060707790E-08
   L2 norm of error           1.5434488758E-08

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           7
termination condition:
  maximum vertices achieved
---------------------------------------------------------
