---------------------------------------------------------
           PHAML   Version 1.6.2

Output from slave number     1
  PDE id is     0
  Number of slave processors is     1

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert           infinity
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  term_energy_err     4.0000000000E-02
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    FINAL
  print_grid_who     SLAVES
  print_linsys_when  NEVER
  print_error_when   FINAL
  print_error_who    SLAVES
  print_error_what   NEVER
  print_errest_what  ENERGY_ERREST
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ_SMOOTH
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    false
  solver             MG_SOLVER
  mg_cycles          infinity
  mg_tol             MG_ERREST_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_FUDOP
---------------------------------------------------------

My Grid:
   number of vertices       =         145
   number of vertices I own =         145
   number of elements       =         504
   number of leaf elements  =         256
   leaf elements I own      =         256
   number of levels         =           6
   degrees of freedom       =         145
   degrees of freedom I own =         145
   min and max degree       =           1          1

Norms of error:
   energy error estimate      2.6187090813E-02
      effectivity             2.6187090813E-02

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           4
termination condition:
  energy error estimate achieved
---------------------------------------------------------
