from simple_wrapper import (Phaml,
        H_UNIFORM, H_ADAPTIVE, P_UNIFORM, P_ADAPTIVE, HP_ADAPTIVE,

        HP_BIGGER_ERRIND, HP_APRIORI, HP_PRIOR2P_E, HP_PRIOR2P_H1, HP_T3S,
        HP_ALTERNATE, HP_TYPEPARAM, HP_COEF_DECAY, HP_COEF_ROOT,
        HP_SMOOTH_PRED, HP_NEXT3P, HP_REFSOLN_EDGE, HP_REFSOLN_ELEM, HP_NLP,

        HIERARCHICAL_COEFFICIENT, TRUE_DIFF, LOCAL_PROBLEM_H, LOCAL_PROBLEM_P,
        INITIAL_CONDITION, EXPLICIT_ERRIND, EQUILIBRATED_RESIDUAL,
        REFSOLN_ERREST)
