---------------------------------------------------------
           PHAML   Version 1.6.2

Output from the master process
  PDE id is     0
  Number of slave processors is     1

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert           infinity
  max_eq                    500
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    PHASES
  print_grid_who     MASTER
  print_linsys_when  NEVER
  print_error_when   PHASES
  print_error_who    MASTER
  print_error_what   ENERGY_LINF_L2_ERR
  print_errest_what  NEVER
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree                      4
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    true
  solver             LAPACK_SPD_SOLVER
---------------------------------------------------------

Total Grid:
   number of vertices      =           9
   number of leaf elements =           8
   number of levels        =           1
   degrees of freedom      =          81
   min and max degree      =           4          4

Norms of error:
   energy norm of error       5.4351354665E-02
   Linf norm of error         1.0764133692E-02
   L2 norm of error           4.3498770589E-03

Total Grid:
   number of vertices      =          15
   number of leaf elements =          18
   number of levels        =           3
   degrees of freedom      =         165
   min and max degree      =           4          4

Norms of error:
   energy norm of error       2.1492481417E-02
      reduced by              3.9543598406E-01
   Linf norm of error         5.0396379709E-03
      reduced by              4.6818797640E-01
   L2 norm of error           1.2174315723E-03
      reduced by              2.7987723694E-01

Total Grid:
   number of vertices      =          27
   number of leaf elements =          38
   number of levels        =           4
   degrees of freedom      =         333
   min and max degree      =           4          4

Norms of error:
   energy norm of error       3.6733790796E-03
      reduced by              1.7091461001E-01
   Linf norm of error         4.1467102463E-04
      reduced by              8.2281907357E-02
   L2 norm of error           1.3517586122E-04
      reduced by              1.1103364189E-01

Total Grid:
   number of vertices      =          39
   number of leaf elements =          58
   number of levels        =           5
   degrees of freedom      =         501
   min and max degree      =           4          4

Norms of error:
   energy norm of error       1.2247198976E-03
      reduced by              3.3340416848E-01
   Linf norm of error         2.8171120326E-04
      reduced by              6.7936071374E-01
   L2 norm of error           4.2098025308E-05
      reduced by              3.1143153021E-01

Total Grid:
   number of vertices      =          39
   number of leaf elements =          58
   number of levels        =           5
   degrees of freedom      =         501
   min and max degree      =           4          4

Norms of error:
   energy norm of error       1.2247198976E-03
   Linf norm of error         2.8171120326E-04
   L2 norm of error           4.2098025308E-05

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           3
termination condition:
  maximum equations achieved
---------------------------------------------------------
