---------------------------------------------------------
           PHAML   Version 1.8.0

Output from the master process
  PDE id is     0
  Number of slave processors is     4

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                 1000
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    PHASES
  print_grid_who     MASTER
  print_linsys_when  NEVER
  print_error_when   PHASES
  print_error_who    MASTER
  print_error_what   ENERGY_LINF_ERR
  print_errest_what  ENERGY_LINF_ERREST
  print_time_when    NEVER
  print_eval_when    PHASES
  print_eval_who     MASTER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           250
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ_SMOOTH
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    false
  solver             MG_SOLVER
  mg_cycles                  10
  mg_tol             MG_NO_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_FUDOP
  eigensolver        ARPACK_SOLVER
  num_eval                    1
  lambda0            -infinity
  scale_evec         SCALE_LINF
  arpack_ncv                 20
  arpack_maxit              100
  arpack_tol          1.0000000000E-10
---------------------------------------------------------

Total Grid:
   number of vertices      =         145
   number of leaf elements =         256
   number of levels        =           1
   degrees of freedom      =         145
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       8.5657831087E-01
   energy error estimate      3.3353373990E-01
      effectivity             3.8937915620E-01
   Linf norm of error         1.3374885086E-01
   Linf error estimate        9.8650670987E-02
      effectivity             7.3758144726E-01

Total Grid:
   number of vertices      =         275
   number of leaf elements =         516
   number of levels        =           7
   degrees of freedom      =         275
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       3.7678755958E-01
      reduced by              4.3987520441E-01
   energy error estimate      9.4698089886E-02
      reduced by              2.8392356921E-01
      effectivity             2.5133019251E-01
   Linf norm of error         2.7322464301E-02
      reduced by              2.0428186205E-01
   Linf error estimate        4.2589603745E-03
      reduced by              4.3172137928E-02
      effectivity             1.5587760780E-01

Eigenvalues and error estimates:
     9.8630549324E+00  6.5466620391E-02

Total Grid:
   number of vertices      =         639
   number of leaf elements =        1244
   number of levels        =           9
   degrees of freedom      =         639
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       1.9965194880E-01
      reduced by              2.6493967718E-01
   energy error estimate      4.9246641187E-02
      reduced by              2.6001918965E-01
      effectivity             2.4666246176E-01
   Linf norm of error         7.3661449170E-03
      reduced by              2.6960031261E-01
   Linf error estimate        1.4651092429E-03
      reduced by              3.4400631000E-01
      effectivity             1.9889769471E-01

Eigenvalues and error estimates:
     9.7176761525E+00  1.9685539323E-02

Total Grid:
   number of vertices      =        1209
   number of leaf elements =        2384
   number of levels        =          10
   degrees of freedom      =        1209
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       1.3842335118E-01
      reduced by              6.9332331596E-01
   energy error estimate      3.3412934100E-02
      reduced by              6.7848148208E-01
      effectivity             2.4138220766E-01
   Linf norm of error         5.6077307965E-03
      reduced by              7.6128434340E-01
   Linf error estimate        7.6136263527E-04
      reduced by              5.1966270704E-01
      effectivity             1.3577018279E-01

Eigenvalues and error estimates:
     9.6875164402E+00  9.2130593715E-03

Total Grid:
   number of vertices      =        1209
   number of leaf elements =        2384
   number of levels        =          10
   degrees of freedom      =        1209
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       1.3842335118E-01
   energy error estimate      3.3412934100E-02
      effectivity             2.4138220766E-01
   Linf norm of error         5.6077307965E-03
   Linf error estimate        7.6136263527E-04
      effectivity             1.3577018279E-01

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           3
termination condition:
  maximum vertices achieved
---------------------------------------------------------
