---------------------------------------------------------
           PHAML   Version 1.6.2

Output from slave number     1
  PDE id is     0
  Number of slave processors is     1

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                 1000
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    PHASES
  print_grid_who     SLAVES
  print_linsys_when  NEVER
  print_error_when   PHASES
  print_error_who    SLAVES
  print_error_what   ENERGY_LINF_ERR
  print_errest_what  ENERGY_LINF_ERREST
  print_time_when    NEVER
  print_eval_when    PHASES
  print_eval_who     SLAVES
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           250
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ_SMOOTH
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    false
  solver             MG_SOLVER
  mg_cycles                  10
  mg_tol             MG_NO_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_FUDOP
  eigensolver        ARPACK_SOLVER
  num_eval                    1
  lambda0            -infinity
  scale_evec         SCALE_M
  arpack_ncv                 20
  arpack_maxit              100
  arpack_tol          1.0000000000E-10
---------------------------------------------------------

My Grid:
   number of vertices       =         145
   number of vertices I own =         145
   number of elements       =         256
   number of leaf elements  =         256
   leaf elements I own      =         256
   number of levels         =           1
   degrees of freedom       =         145
   degrees of freedom I own =         145
   min and max degree       =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       1.2216930218E+00
   energy error estimate      4.5104233769E-01
      effectivity             3.6919449456E-01
   Linf norm of error         3.5231397525E-01
   Linf error estimate        1.3340668104E-01
      effectivity             3.7865849900E-01

My Grid:
   number of vertices       =         283
   number of vertices I own =         283
   number of elements       =         808
   number of leaf elements  =         532
   leaf elements I own      =         532
   number of levels         =           7
   degrees of freedom       =         283
   degrees of freedom I own =         283
   min and max degree       =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       7.1502584210E-01
      reduced by              5.8527455699E-01
   energy error estimate      1.1307915292E-01
      reduced by              2.5070629400E-01
      effectivity             1.5814694555E-01
   Linf norm of error         2.2291895605E-01
      reduced by              6.3272811104E-01
   Linf error estimate        5.1713635486E-03
      reduced by              3.8763902289E-02
      effectivity             2.3198401967E-02

Eigenvalues and error estimates:
     9.8569429510E+00  7.6372540416E-02

My Grid:
   number of vertices       =         615
   number of vertices I own =         615
   number of elements       =        2136
   number of leaf elements  =        1196
   leaf elements I own      =        1196
   number of levels         =           8
   degrees of freedom       =         615
   degrees of freedom I own =         615
   min and max degree       =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       6.0188342021E-01
      reduced by              8.4176456957E-01
   energy error estimate      5.9944694638E-02
      reduced by              5.3011269619E-01
      effectivity             9.9595191735E-02
   Linf norm of error         2.1973065598E-01
      reduced by              9.8569749238E-01
   Linf error estimate        1.3914141687E-03
      reduced by              2.6906137146E-01
      effectivity             6.3323625121E-03

Eigenvalues and error estimates:
     9.7138816524E+00  2.4729198651E-02

My Grid:
   number of vertices       =        1205
   number of vertices I own =        1205
   number of elements       =        4496
   number of leaf elements  =        2376
   leaf elements I own      =        2376
   number of levels         =          10
   degrees of freedom       =        1205
   degrees of freedom I own =        1205
   min and max degree       =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       5.7700825315E-01
      reduced by              9.5867112097E-01
   energy error estimate      4.0178287004E-02
      reduced by              6.7025592918E-01
      effectivity             6.9632083744E-02
   Linf norm of error         2.1860101644E-01
      reduced by              9.9485898071E-01
   Linf error estimate        6.6982436927E-04
      reduced by              4.8139826683E-01
      effectivity             3.0641411470E-03

Eigenvalues and error estimates:
     9.6849561486E+00  1.0753314383E-02

My Grid:
   number of vertices       =        1205
   number of vertices I own =        1205
   number of elements       =        4496
   number of leaf elements  =        2376
   leaf elements I own      =        2376
   number of levels         =          10
   degrees of freedom       =        1205
   degrees of freedom I own =        1205
   min and max degree       =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       5.7700825315E-01
   energy error estimate      4.0178287004E-02
      effectivity             6.9632083744E-02
   Linf norm of error         2.1860101644E-01
   Linf error estimate        6.6982436927E-04
      effectivity             3.0641411470E-03

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           3
termination condition:
  maximum vertices achieved
---------------------------------------------------------
