---------------------------------------------------------
           PHAML   Version 1.8.0

Output from the master process
  PDE id is     0
  Number of slave processors is     1

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                 1000
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    PHASES
  print_grid_who     MASTER
  print_linsys_when  NEVER
  print_error_when   PHASES
  print_error_who    MASTER
  print_error_what   NEVER
  print_errest_what  ENERGY_LINF_ERREST
  print_time_when    NEVER
  print_eval_when    PHASES
  print_eval_who     MASTER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           250
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ_SMOOTH
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    true
  solver             LAPACK_INDEFINITE_SOLVER
  eigensolver        ARPACK_SOLVER
  num_eval                    3
  lambda0             5.0000000000E+01
  scale_evec         SCALE_LINF
  lambda0_side       EIGEN_LEFT
  transformation     SHIFT_INVERT
  arpack_ncv                 20
  arpack_maxit              100
  arpack_tol          1.0000000000E-10
---------------------------------------------------------

Total Grid:
   number of vertices      =         145
   number of leaf elements =         256
   number of levels        =           1
   degrees of freedom      =         145
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy error estimate      1.0669305515E+00
      effectivity             1.0669305515E+00
   Linf error estimate        2.1437006904E-01
      effectivity             2.1437006904E-01
 Eigenvector           2
   energy error estimate      1.5022014751E+00
   Linf error estimate        3.2371124797E-01
 Eigenvector           3
   energy error estimate      1.7397737746E+00
   Linf error estimate        4.1052118999E-01

Total Grid:
   number of vertices      =         311
   number of leaf elements =         588
   number of levels        =           6
   degrees of freedom      =         311
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy error estimate      6.0925026723E-01
      reduced by              5.7103085707E-01
      effectivity             6.0925026723E-01
   Linf error estimate        5.8502533108E-02
      reduced by              2.7290439086E-01
      effectivity             5.8502533108E-02
 Eigenvector           2
   energy error estimate      5.5827104276E-01
      reduced by              3.7163526464E-01
   Linf error estimate        4.4942567408E-02
      reduced by              1.3883535926E-01
 Eigenvector           3
   energy error estimate      5.4861195712E-01
      reduced by              3.1533522640E-01
   Linf error estimate        3.8539413390E-02
      reduced by              9.3879230427E-02

Eigenvalues and error estimates:
     4.5911041305E+01  5.1311359507E-01
     4.8368752031E+01  4.7121663379E-01
     4.9170082335E+01  3.5690092864E-01

Total Grid:
   number of vertices      =         629
   number of leaf elements =        1224
   number of levels        =           8
   degrees of freedom      =         629
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy error estimate      3.1762423457E-01
      reduced by              5.2133622529E-01
      effectivity             3.1762423457E-01
   Linf error estimate        1.0537015868E-02
      reduced by              1.8011213033E-01
      effectivity             1.0537015868E-02
 Eigenvector           2
   energy error estimate      3.1753884164E-01
      reduced by              5.6878974067E-01
   Linf error estimate        1.0960596860E-02
      reduced by              2.4388007833E-01
 Eigenvector           3
   energy error estimate      4.2445307131E-01
      reduced by              7.7368541791E-01
   Linf error estimate        2.3379978035E-02
      reduced by              6.0665111319E-01

Eigenvalues and error estimates:
     4.6055623780E+01  1.4946203015E-01
     4.7390048449E+01  1.4178456949E-01
     4.9640268750E+01  2.2238152304E-01

Total Grid:
   number of vertices      =        1295
   number of leaf elements =        2556
   number of levels        =           9
   degrees of freedom      =        1295
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy error estimate      2.2042118367E-01
      reduced by              6.9396840569E-01
      effectivity             2.2042118367E-01
   Linf error estimate        6.0779789931E-03
      reduced by              5.7682166084E-01
      effectivity             6.0779789931E-03
 Eigenvector           2
   energy error estimate      2.1468233253E-01
      reduced by              6.7608211777E-01
   Linf error estimate        5.2233936743E-03
      reduced by              4.7656106151E-01
 Eigenvector           3
   energy error estimate      2.4076538824E-01
      reduced by              5.6723676777E-01
   Linf error estimate        4.8631592910E-03
      reduced by              2.0800529769E-01

Eigenvalues and error estimates:
     4.5486406035E+01  7.6322469789E-02
     4.6841089423E+01  5.6689450247E-02
     4.8848702713E+01  7.5108509133E-02

Total Grid:
   number of vertices      =        1295
   number of leaf elements =        2556
   number of levels        =           9
   degrees of freedom      =        1295
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy error estimate      2.2042118367E-01
      effectivity             2.2042118367E-01
   Linf error estimate        6.0779789931E-03
      effectivity             6.0779789931E-03
 Eigenvector           2
   energy error estimate      2.1468233253E-01
   Linf error estimate        5.2233936743E-03
 Eigenvector           3
   energy error estimate      2.4076538824E-01
   Linf error estimate        4.8631592910E-03

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           3
termination condition:
  maximum vertices achieved
---------------------------------------------------------
