---------------------------------------------------------
           PHAML   Version 1.6.2

Output from slave number     1
  PDE id is     0
  Number of slave processors is     1

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                  350
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    PHASES
  print_grid_who     SLAVES
  print_linsys_when  NEVER
  print_error_when   PHASES
  print_error_who    SLAVES
  print_error_what   ENERGY_LINF_ERR
  print_errest_what  ENERGY_LINF_ERREST
  print_time_when    NEVER
  print_eval_when    PHASES
  print_eval_who     SLAVES
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree                      4
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ_SMOOTH
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    true
  solver             CG_SOLVER
  preconditioner     MG_PRECONDITION
  mg_cycles                   2
  mg_tol             MG_NO_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_NONE
  krylov_iter               100
  krylov_tol          1.0000000000E-10
  eigensolver        ARPACK_SOLVER
  num_eval                    1
  lambda0            -infinity
  scale_evec         SCALE_LINF
  arpack_ncv                 20
  arpack_maxit              100
  arpack_tol          1.0000000000E-10
---------------------------------------------------------

My Grid:
   number of vertices       =         145
   number of vertices I own =         145
   number of elements       =         256
   number of leaf elements  =         256
   leaf elements I own      =         256
   number of levels         =           1
   degrees of freedom       =        2113
   degrees of freedom I own =        2113
   min and max degree       =           4          4

Norms of error:
 Eigenvector           1
   energy norm of error       1.9291194674E-02
   energy error estimate      2.0838285000E-02
      effectivity             1.0801967090E+00
   Linf norm of error         6.7057031516E-03
   Linf error estimate        8.5395447631E-03
      effectivity             1.2734749168E+00

My Grid:
   number of vertices       =         249
   number of vertices I own =         249
   number of elements       =         672
   number of leaf elements  =         464
   leaf elements I own      =         464
   number of levels         =           6
   degrees of freedom       =        3777
   degrees of freedom I own =        3777
   min and max degree       =           4          4

Norms of error:
 Eigenvector           1
   energy norm of error       1.0080791800E-03
      reduced by              5.2255922821E-02
   energy error estimate      1.1666447616E-03
      reduced by              5.5985641889E-02
      effectivity             1.1572947688E+00
   Linf norm of error         1.1708408869E-04
      reduced by              1.7460374557E-02
   Linf error estimate        2.4718860827E-04
      reduced by              2.8946344931E-02
      effectivity             2.1112058096E+00

Eigenvalues and error estimates:
     9.6592611974E+00  2.1665776512E-07

My Grid:
   number of vertices       =         457
   number of vertices I own =         457
   number of elements       =        1504
   number of leaf elements  =         880
   leaf elements I own      =         880
   number of levels         =           6
   degrees of freedom       =        7105
   degrees of freedom I own =        7105
   min and max degree       =           4          4

Norms of error:
 Eigenvector           1
   energy norm of error       1.0687201201E-04
      reduced by              1.0601549375E-01
   energy error estimate      1.2258998125E-04
      reduced by              1.0507909972E-01
      effectivity             1.1470728298E+00
   Linf norm of error         8.3809370828E-06
      reduced by              7.1580495491E-02
   Linf error estimate        1.5900607564E-05
      reduced by              6.4325810464E-02
      effectivity             1.8972350475E+00

Eigenvalues and error estimates:
     9.6592582962E+00  1.5609740394E-09

My Grid:
   number of vertices       =         457
   number of vertices I own =         457
   number of elements       =        1504
   number of leaf elements  =         880
   leaf elements I own      =         880
   number of levels         =           6
   degrees of freedom       =        7105
   degrees of freedom I own =        7105
   min and max degree       =           4          4

Norms of error:
 Eigenvector           1
   energy norm of error       1.0687201201E-04
   energy error estimate      1.2258998125E-04
      effectivity             1.1470728298E+00
   Linf norm of error         8.3809370828E-06
   Linf error estimate        1.5900607564E-05
      effectivity             1.8972350475E+00

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           2
termination condition:
  maximum vertices achieved
---------------------------------------------------------
