---------------------------------------------------------
           PHAML   Version 1.8.0

Output from slave number     1
  PDE id is     0
  Number of slave processors is     1

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                  350
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    PHASES
  print_grid_who     SLAVES
  print_linsys_when  NEVER
  print_error_when   PHASES
  print_error_who    SLAVES
  print_error_what   ENERGY_LINF_ERR
  print_errest_what  ENERGY_LINF_ERREST
  print_time_when    NEVER
  print_eval_when    PHASES
  print_eval_who     SLAVES
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree                      4
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ_SMOOTH
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    true
  solver             CG_SOLVER
  preconditioner     MG_PRECONDITION
  mg_cycles                   2
  mg_tol             MG_NO_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_NONE
  krylov_iter               100
  krylov_tol          1.0000000000E-10
  eigensolver        ARPACK_SOLVER
  num_eval                    1
  lambda0            -infinity
  scale_evec         SCALE_LINF
  arpack_ncv                 20
  arpack_maxit              100
  arpack_tol          1.0000000000E-10
---------------------------------------------------------

My Grid:
   number of vertices       =         145
   number of vertices I own =         145
   number of elements       =         256
   number of leaf elements  =         256
   leaf elements I own      =         256
   number of levels         =           1
   degrees of freedom       =        2113
   degrees of freedom I own =        2113
   min and max degree       =           4          4

Norms of error:
 Eigenvector           1
   energy norm of error       1.9291194674E-02
   energy error estimate      2.0838285000E-02
      effectivity             1.0801967090E+00
   Linf norm of error         6.7057031516E-03
   Linf error estimate        8.5395447631E-03
      effectivity             1.2734749168E+00

My Grid:
   number of vertices       =         197
   number of vertices I own =         197
   number of elements       =         464
   number of leaf elements  =         360
   leaf elements I own      =         360
   number of levels         =           6
   degrees of freedom       =        2945
   degrees of freedom I own =        2945
   min and max degree       =           4          4

Norms of error:
 Eigenvector           1
   energy norm of error       1.5455193698E-03
      reduced by              8.0115275175E-02
   energy error estimate      1.9662271505E-03
      reduced by              9.4356476576E-02
      effectivity             1.2722112637E+00
   Linf norm of error         1.2061459316E-04
      reduced by              1.7986867363E-02
   Linf error estimate        4.8584113755E-04
      reduced by              5.6893095712E-02
      effectivity             4.0280460664E+00

Eigenvalues and error estimates:
     9.6592642276E+00  7.1408500964E-07

My Grid:
   number of vertices       =         337
   number of vertices I own =         337
   number of elements       =        1024
   number of leaf elements  =         640
   leaf elements I own      =         640
   number of levels         =           6
   degrees of freedom       =        5185
   degrees of freedom I own =        5185
   min and max degree       =           4          4

Norms of error:
 Eigenvector           1
   energy norm of error       1.8987513607E-04
      reduced by              1.2285522898E-01
   energy error estimate      2.1732081910E-04
      reduced by              1.1052681225E-01
      effectivity             1.1445459558E+00
   Linf norm of error         1.2040525508E-05
      reduced by              9.9826440500E-02
   Linf error estimate        3.5189421625E-05
      reduced by              7.2429893037E-02
      effectivity             2.9225818759E+00

Eigenvalues and error estimates:
     9.6592583587E+00  3.4933338325E-08

My Grid:
   number of vertices       =         699
   number of vertices I own =         699
   number of elements       =        2472
   number of leaf elements  =        1364
   leaf elements I own      =        1364
   number of levels         =           7
   degrees of freedom       =       10977
   degrees of freedom I own =       10977
   min and max degree       =           4          4

Norms of error:
 Eigenvector           1
   energy norm of error       2.4187148679E-05
      reduced by              1.2738449688E-01
   energy error estimate      2.9827305292E-05
      reduced by              1.3725010524E-01
      effectivity             1.2331881566E+00
   Linf norm of error         1.1237350486E-06
      reduced by              9.3329402262E-02
   Linf error estimate        2.7187430492E-06
      reduced by              7.7260236845E-02
      effectivity             2.4193808431E+00

Eigenvalues and error estimates:
     9.6592582646E+00  1.0732449359E-09

My Grid:
   number of vertices       =         699
   number of vertices I own =         699
   number of elements       =        2472
   number of leaf elements  =        1364
   leaf elements I own      =        1364
   number of levels         =           7
   degrees of freedom       =       10977
   degrees of freedom I own =       10977
   min and max degree       =           4          4

Norms of error:
 Eigenvector           1
   energy norm of error       2.4187148679E-05
   energy error estimate      2.9827305292E-05
      effectivity             1.2331881566E+00
   Linf norm of error         1.1237350486E-06
   Linf error estimate        2.7187430492E-06
      effectivity             2.4193808431E+00

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           3
termination condition:
  maximum vertices achieved
---------------------------------------------------------
