---------------------------------------------------------
           PHAML   Version 1.8.0

Output from the master process
  PDE id is     0
  Number of slave processors is     4

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                  350
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    PHASES
  print_grid_who     MASTER
  print_linsys_when  NEVER
  print_error_when   PHASES
  print_error_who    MASTER
  print_error_what   ENERGY_LINF_ERR
  print_errest_what  ENERGY_LINF_ERREST
  print_time_when    NEVER
  print_eval_when    PHASES
  print_eval_who     MASTER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree                      4
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ_SMOOTH
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    true
  solver             CG_SOLVER
  preconditioner     MG_PRECONDITION
  mg_cycles                   2
  mg_tol             MG_NO_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_NONE
  krylov_iter               100
  krylov_tol          1.0000000000E-10
  eigensolver        ARPACK_SOLVER
  num_eval                    1
  lambda0            -infinity
  scale_evec         SCALE_LINF
  arpack_ncv                 20
  arpack_maxit              100
  arpack_tol          1.0000000000E-10
---------------------------------------------------------

Total Grid:
   number of vertices      =         145
   number of leaf elements =         256
   number of levels        =           1
   degrees of freedom      =        2113
   min and max degree      =           4          4

Norms of error:
 Eigenvector           1
   energy norm of error       1.9291194674E-02
   energy error estimate      2.0838285000E-02
      effectivity             1.0801967090E+00
   Linf norm of error         6.7057031516E-03
   Linf error estimate        8.5395447631E-03
      effectivity             1.2734749168E+00

Total Grid:
   number of vertices      =         197
   number of leaf elements =         360
   number of levels        =           6
   degrees of freedom      =        2945
   min and max degree      =           4          4

Norms of error:
 Eigenvector           1
   energy norm of error       1.5455193694E-03
      reduced by              4.0057637577E-02
   energy error estimate      1.9662271478E-03
      reduced by              4.7178238223E-02
      effectivity             1.2722112623E+00
   Linf norm of error         1.2061459378E-04
      reduced by              1.7986867455E-02
   Linf error estimate        4.8584113750E-04
      reduced by              5.6893095707E-02
      effectivity             4.0280460455E+00

Eigenvalues and error estimates:
     9.6592642276E+00  7.1408500955E-07

Total Grid:
   number of vertices      =         341
   number of leaf elements =         648
   number of levels        =           6
   degrees of freedom      =        5249
   min and max degree      =           4          4

Norms of error:
 Eigenvector           1
   energy norm of error       1.8600983598E-04
      reduced by              1.2035425739E-01
   energy error estimate      2.1406517540E-04
      reduced by              1.0887103031E-01
      effectivity             1.1508271822E+00
   Linf norm of error         1.2040525189E-05
      reduced by              9.9826437343E-02
   Linf error estimate        3.5189420047E-05
      reduced by              7.2429889796E-02
      effectivity             2.9225818223E+00

Eigenvalues and error estimates:
     9.6592583539E+00  3.4933259780E-08

Total Grid:
   number of vertices      =         691
   number of leaf elements =        1348
   number of levels        =           7
   degrees of freedom      =       10849
   min and max degree      =           4          4

Norms of error:
 Eigenvector           1
   energy norm of error       2.4592988445E-05
      reduced by              1.3221337633E-01
   energy error estimate      3.0144301940E-05
      reduced by              1.4081833667E-01
      effectivity             1.2257274876E+00
   Linf norm of error         1.1293887924E-06
      reduced by              9.3798964305E-02
   Linf error estimate        2.7187427300E-06
      reduced by              7.7260231239E-02
      effectivity             2.4072690896E+00

Eigenvalues and error estimates:
     9.6592582646E+00  1.0732474559E-09

Total Grid:
   number of vertices      =         691
   number of leaf elements =        1348
   number of levels        =           7
   degrees of freedom      =       10849
   min and max degree      =           4          4

Norms of error:
 Eigenvector           1
   energy norm of error       2.4592988445E-05
   energy error estimate      3.0144301940E-05
      effectivity             1.2257274876E+00
   Linf norm of error         1.1293887924E-06
   Linf error estimate        2.7187427300E-06
      effectivity             2.4072690896E+00

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           3
termination condition:
  maximum vertices achieved
---------------------------------------------------------
