---------------------------------------------------------
           PHAML   Version 1.6.2

Output from slave number     1
  PDE id is     0
  Number of slave processors is     1

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                 1000
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    NEVER
  print_linsys_when  NEVER
  print_error_when   FINAL
  print_error_who    SLAVES
  print_error_what   NEVER
  print_errest_what  LINF_ERREST
  print_time_when    NEVER
  print_eval_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           250
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ_SMOOTH
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    false
  solver             MG_SOLVER
  mg_cycles                  10
  mg_tol             MG_NO_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_FUDOP
  eigensolver        ARPACK_SOLVER
  num_eval                    3
  lambda0            -infinity
  scale_evec         SCALE_LINF
  arpack_ncv                 20
  arpack_maxit              100
  arpack_tol          1.0000000000E-10
---------------------------------------------------------

Norms of error:
 Eigenvector           1
   Linf error estimate        1.2859240691E-03
      effectivity             1.2859240691E-03
 Eigenvector           2
   Linf error estimate        1.6846762651E-03
 Eigenvector           3
   Linf error estimate        1.8743432051E-03

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           3
termination condition:
  maximum vertices achieved
---------------------------------------------------------
eigenvalues  9.687125312410E+00 2.199116945801E+01 2.392225027427E+01
error estimates  2.081705139821E-05 8.777572549761E-05 1.724562342554E-04
max linear system residual  4.647779568350E-10
ave linear system residual  1.276072501324E-11
eigensystem residuals  9.581050263914E-12 4.760107640149E-11 4.632617113414E-11
arpack iterations           2
arpack number converged           3
arpack number of OP*x          37
arpack number of B*x         110
arpack number of reorthogonalizatons          36
arpack error flag           0
error estimate for evec 2  1.684676265137E-03
