---------------------------------------------------------
           PHAML   Version 1.8.0

Output from slave number     1
  PDE id is     0
  Number of slave processors is     1

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                 1000
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    NEVER
  print_linsys_when  NEVER
  print_error_when   FINAL
  print_error_who    SLAVES
  print_error_what   NEVER
  print_errest_what  LINF_ERREST
  print_time_when    NEVER
  print_eval_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           250
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ_SMOOTH
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    false
  solver             MG_SOLVER
  mg_cycles                  10
  mg_tol             MG_NO_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_FUDOP
  eigensolver        ARPACK_SOLVER
  num_eval                    3
  lambda0            -infinity
  scale_evec         SCALE_LINF
  arpack_ncv                 20
  arpack_maxit              100
  arpack_tol          1.0000000000E-10
---------------------------------------------------------

Norms of error:
 Eigenvector           1
   Linf error estimate        9.9926254577E-04
      effectivity             9.9926254577E-04
 Eigenvector           2
   Linf error estimate        1.3776156402E-03
 Eigenvector           3
   Linf error estimate        3.3693329139E-03

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           3
termination condition:
  maximum vertices achieved
---------------------------------------------------------
eigenvalues  9.688659557947E+00 2.199447691815E+01 2.394163349248E+01
error estimates  2.348586370702E-05 9.311412475090E-05 2.818198873515E-04
max linear system residual  6.464344798618E-10
ave linear system residual  1.755130442392E-11
eigensystem residuals  1.306355171552E-11 5.094010219407E-11 3.288378299449E-11
arpack iterations           2
arpack number converged           3
arpack number of OP*x          37
arpack number of B*x         108
arpack number of reorthogonalizatons          34
arpack error flag           0
error estimate for evec 2  1.377615640206E-03
