---------------------------------------------------------
           PHAML   Version 1.8.0

Output from slave number     1
  PDE id is     0
  Number of slave processors is     1

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                 1000
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    PHASES
  print_grid_who     SLAVES
  print_linsys_when  NEVER
  print_error_when   PHASES
  print_error_who    SLAVES
  print_error_what   ENERGY_LINF_ERR
  print_errest_what  ENERGY_LINF_ERREST
  print_time_when    NEVER
  print_eval_when    PHASES
  print_eval_who     SLAVES
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           250
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ_SMOOTH
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    false
  solver             MG_SOLVER
  mg_cycles                  10
  mg_tol             MG_NO_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_FUDOP
  eigensolver        ARPACK_SOLVER
  num_eval                    1
  lambda0            -infinity
  scale_evec         SCALE_M
  arpack_ncv                 20
  arpack_maxit              100
  arpack_tol          1.0000000000E-10
---------------------------------------------------------

My Grid:
   number of vertices       =         145
   number of vertices I own =         145
   number of elements       =         256
   number of leaf elements  =         256
   leaf elements I own      =         256
   number of levels         =           1
   degrees of freedom       =         145
   degrees of freedom I own =         145
   min and max degree       =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       1.2216930218E+00
   energy error estimate      4.5104233769E-01
      effectivity             3.6919449456E-01
   Linf norm of error         3.5231397525E-01
   Linf error estimate        1.3340668104E-01
      effectivity             3.7865849900E-01

My Grid:
   number of vertices       =         275
   number of vertices I own =         275
   number of elements       =         776
   number of leaf elements  =         516
   leaf elements I own      =         516
   number of levels         =           7
   degrees of freedom       =         275
   degrees of freedom I own =         275
   min and max degree       =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       7.1974218064E-01
      reduced by              5.8913505096E-01
   energy error estimate      1.1576860521E-01
      reduced by              2.5666904310E-01
      effectivity             1.6084732607E-01
   Linf norm of error         2.2250200985E-01
      reduced by              6.3154466038E-01
   Linf error estimate        5.2065876177E-03
      reduced by              3.9027937559E-02
      effectivity             2.3400182413E-02

Eigenvalues and error estimates:
     9.8630549324E+00  8.0033075006E-02

My Grid:
   number of vertices       =         613
   number of vertices I own =         613
   number of elements       =        2128
   number of leaf elements  =        1192
   leaf elements I own      =        1192
   number of levels         =           8
   degrees of freedom       =         613
   degrees of freedom I own =         613
   min and max degree       =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       6.0125616022E-01
      reduced by              8.3537713419E-01
   energy error estimate      5.9850842109E-02
      reduced by              5.1698681174E-01
      effectivity             9.9543000253E-02
   Linf norm of error         2.1962025133E-01
      reduced by              9.8704839332E-01
   Linf error estimate        1.3915362847E-03
      reduced by              2.6726454769E-01
      effectivity             6.3361018679E-03

Eigenvalues and error estimates:
     9.7131319943E+00  2.4590873665E-02

My Grid:
   number of vertices       =        1201
   number of vertices I own =        1201
   number of elements       =        4480
   number of leaf elements  =        2368
   leaf elements I own      =        2368
   number of levels         =          10
   degrees of freedom       =        1201
   degrees of freedom I own =        1201
   min and max degree       =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       5.7714458713E-01
      reduced by              9.5989800241E-01
   energy error estimate      4.0313319279E-02
      reduced by              6.7356310887E-01
      effectivity             6.9849601258E-02
   Linf norm of error         2.1861618307E-01
      reduced by              9.9542816177E-01
   Linf error estimate        6.6983815472E-04
      reduced by              4.8136592778E-01
      effectivity             3.0639916282E-03

Eigenvalues and error estimates:
     9.6851126775E+00  1.0796065722E-02

My Grid:
   number of vertices       =        1201
   number of vertices I own =        1201
   number of elements       =        4480
   number of leaf elements  =        2368
   leaf elements I own      =        2368
   number of levels         =          10
   degrees of freedom       =        1201
   degrees of freedom I own =        1201
   min and max degree       =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       5.7714458713E-01
   energy error estimate      4.0313319279E-02
      effectivity             6.9849601258E-02
   Linf norm of error         2.1861618307E-01
   Linf error estimate        6.6983815472E-04
      effectivity             3.0639916282E-03

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           3
termination condition:
  maximum vertices achieved
---------------------------------------------------------
