---------------------------------------------------------
           PHAML   Version 1.6.2

Output from the master process
  PDE id is     0
  Number of slave processors is     4

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                 1000
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    PHASES
  print_grid_who     MASTER
  print_linsys_when  NEVER
  print_error_when   PHASES
  print_error_who    MASTER
  print_error_what   ENERGY_LINF_ERR
  print_errest_what  ENERGY_LINF_ERREST
  print_time_when    NEVER
  print_eval_when    PHASES
  print_eval_who     MASTER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           250
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ_SMOOTH
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    false
  solver             MG_SOLVER
  mg_cycles                  10
  mg_tol             MG_NO_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_FUDOP
  eigensolver        ARPACK_SOLVER
  num_eval                    1
  lambda0            -infinity
  scale_evec         SCALE_M
  arpack_ncv                 20
  arpack_maxit              100
  arpack_tol          1.0000000000E-10
---------------------------------------------------------

Total Grid:
   number of vertices      =         145
   number of leaf elements =         256
   number of levels        =           1
   degrees of freedom      =         145
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       1.2216930218E+00
   energy error estimate      4.5104233769E-01
      effectivity             3.6919449456E-01
   Linf norm of error         3.5231397525E-01
   Linf error estimate        1.3340668104E-01
      effectivity             3.7865849900E-01

Total Grid:
   number of vertices      =         283
   number of leaf elements =         532
   number of levels        =           7
   degrees of freedom      =         283
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       7.1502584210E-01
      reduced by              5.8527455699E-01
   energy error estimate      1.1307915292E-01
      reduced by              2.5070629400E-01
      effectivity             1.5814694555E-01
   Linf norm of error         2.2291895605E-01
      reduced by              6.3272811104E-01
   Linf error estimate        5.1713635486E-03
      reduced by              3.8763902289E-02
      effectivity             2.3198401967E-02

Eigenvalues and error estimates:
     9.8569429510E+00  7.6372540416E-02

Total Grid:
   number of vertices      =         591
   number of leaf elements =        1148
   number of levels        =           8
   degrees of freedom      =         591
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       6.0331404046E-01
      reduced by              4.2188268237E-01
   energy error estimate      6.1482260391E-02
      reduced by              2.7185497416E-01
      effectivity             1.0190755770E-01
   Linf norm of error         2.1980407622E-01
      reduced by              9.8602685081E-01
   Linf error estimate        1.6454407485E-03
      reduced by              3.1818315093E-01
      effectivity             7.4859428306E-03

Eigenvalues and error estimates:
     9.7155816750E+00  2.5784098482E-02

Total Grid:
   number of vertices      =        1295
   number of leaf elements =        2556
   number of levels        =          10
   degrees of freedom      =        1295
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       5.7461594784E-01
      reduced by              9.5243257955E-01
   energy error estimate      3.8616958933E-02
      reduced by              6.2809920596E-01
      effectivity             6.7204815804E-02
   Linf norm of error         2.1849868934E-01
      reduced by              9.9406113436E-01
   Linf error estimate        6.6160889629E-04
      reduced by              4.0208612609E-01
      effectivity             3.0279764985E-03

Eigenvalues and error estimates:
     9.6822301408E+00  1.0109365626E-02

Total Grid:
   number of vertices      =        1295
   number of leaf elements =        2556
   number of levels        =          10
   degrees of freedom      =        1295
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       5.7461594784E-01
   energy error estimate      3.8616958933E-02
      effectivity             6.7204815804E-02
   Linf norm of error         2.1849868934E-01
   Linf error estimate        6.6160889629E-04
      effectivity             3.0279764985E-03

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           3
termination condition:
  maximum vertices achieved
---------------------------------------------------------
