---------------------------------------------------------
           PHAML   Version 1.8.0

Output from the master process
  PDE id is     0
  Number of slave processors is     1

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                 1000
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    PHASES
  print_grid_who     MASTER
  print_linsys_when  NEVER
  print_error_when   PHASES
  print_error_who    MASTER
  print_error_what   NEVER
  print_errest_what  ENERGY_LINF_ERREST
  print_time_when    NEVER
  print_eval_when    PHASES
  print_eval_who     MASTER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           250
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ_SMOOTH
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    true
  solver             LAPACK_INDEFINITE_SOLVER
  eigensolver        ARPACK_SOLVER
  num_eval                    3
  lambda0             5.0000000000E+01
  scale_evec         SCALE_LINF
  lambda0_side       EIGEN_BOTH
  transformation     SHIFT_INVERT
  arpack_ncv                 20
  arpack_maxit              100
  arpack_tol          1.0000000000E-10
---------------------------------------------------------

Total Grid:
   number of vertices      =         145
   number of leaf elements =         256
   number of levels        =           1
   degrees of freedom      =         145
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy error estimate      1.5022014751E+00
      effectivity             1.5022014751E+00
   Linf error estimate        3.2371124797E-01
      effectivity             3.2371124797E-01
 Eigenvector           2
   energy error estimate      1.7397737746E+00
   Linf error estimate        4.1052118999E-01
 Eigenvector           3
   energy error estimate      1.3182929653E+00
   Linf error estimate        2.0753070496E-01

Total Grid:
   number of vertices      =         323
   number of leaf elements =         612
   number of levels        =           6
   degrees of freedom      =         323
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy error estimate      5.3384115364E-01
      reduced by              3.5537253988E-01
      effectivity             5.3384115364E-01
   Linf error estimate        4.3728629640E-02
      reduced by              1.3508529566E-01
      effectivity             4.3728629640E-02
 Eigenvector           2
   energy error estimate      5.6248621907E-01
      reduced by              3.2330997700E-01
   Linf error estimate        3.7965864888E-02
      reduced by              9.2482107657E-02
 Eigenvector           3
   energy error estimate      7.0576664723E-01
      reduced by              5.3536403955E-01
   Linf error estimate        5.8795193636E-02
      reduced by              2.8330840801E-01

Eigenvalues and error estimates:
     4.7712126108E+01  4.2210288525E-01
     4.9226368276E+01  3.8346648503E-01
     5.1446406142E+01  5.5747472354E-01

Total Grid:
   number of vertices      =         653
   number of leaf elements =        1272
   number of levels        =           8
   degrees of freedom      =         653
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy error estimate      3.1297200508E-01
      reduced by              5.8626429032E-01
      effectivity             3.1297200508E-01
   Linf error estimate        1.0712990532E-02
      reduced by              2.4498802317E-01
      effectivity             1.0712990532E-02
 Eigenvector           2
   energy error estimate      3.5902815126E-01
      reduced by              6.3828790660E-01
   Linf error estimate        1.3061334187E-02
      reduced by              3.4402835879E-01
 Eigenvector           3
   energy error estimate      4.3934851829E-01
      reduced by              6.2251244092E-01
   Linf error estimate        1.8998057739E-02
      reduced by              3.2312263239E-01

Eigenvalues and error estimates:
     4.7357629288E+01  1.3306428380E-01
     4.9470844373E+01  1.7000200562E-01
     5.1486951900E+01  2.3704489567E-01

Total Grid:
   number of vertices      =        1249
   number of leaf elements =        2464
   number of levels        =           8
   degrees of freedom      =        1249
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy error estimate      2.4459289925E-01
      reduced by              7.8151686183E-01
      effectivity             2.4459289925E-01
   Linf error estimate        5.6451737700E-03
      reduced by              5.2694658447E-01
      effectivity             5.6451737700E-03
 Eigenvector           2
   energy error estimate      2.6505582643E-01
      reduced by              7.3825917409E-01
   Linf error estimate        5.6962175936E-03
      reduced by              4.3611299672E-01
 Eigenvector           3
   energy error estimate      3.0981861703E-01
      reduced by              7.0517733447E-01
   Linf error estimate        1.5021901974E-02
      reduced by              7.9070724915E-01

Eigenvalues and error estimates:
     4.8849643364E+01  7.5097299518E-02
     5.0822229331E+01  9.2233569095E-02
     5.2825917273E+01  1.3389954797E-01

Total Grid:
   number of vertices      =        1249
   number of leaf elements =        2464
   number of levels        =           8
   degrees of freedom      =        1249
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy error estimate      2.4459289925E-01
      effectivity             2.4459289925E-01
   Linf error estimate        5.6451737700E-03
      effectivity             5.6451737700E-03
 Eigenvector           2
   energy error estimate      2.6505582643E-01
   Linf error estimate        5.6962175936E-03
 Eigenvector           3
   energy error estimate      3.0981861703E-01
   Linf error estimate        1.5021901974E-02

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           3
termination condition:
  maximum vertices achieved
---------------------------------------------------------
