---------------------------------------------------------
           PHAML   Version 1.8.0

Output from the master process
  PDE id is     0
  Number of slave processors is     4

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                 1000
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    PHASES
  print_grid_who     MASTER
  print_linsys_when  NEVER
  print_error_when   PHASES
  print_error_who    MASTER
  print_error_what   ENERGY_LINF_ERR
  print_errest_what  ENERGY_LINF_ERREST
  print_time_when    NEVER
  print_eval_when    PHASES
  print_eval_who     MASTER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           250
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ_SMOOTH
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    false
  solver             MG_SOLVER
  mg_cycles                  10
  mg_tol             MG_NO_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_FUDOP
  eigensolver        ARPACK_SOLVER
  num_eval                    3
  lambda0            -infinity
  scale_evec         SCALE_LINF
  arpack_ncv                 20
  arpack_maxit              100
  arpack_tol          1.0000000000E-10
---------------------------------------------------------

Total Grid:
   number of vertices      =         145
   number of leaf elements =         256
   number of levels        =           1
   degrees of freedom      =         145
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       8.5657831087E-01
   energy error estimate      3.3353373990E-01
      effectivity             3.8937915620E-01
   Linf norm of error         1.3374885086E-01
   Linf error estimate        9.8650670987E-02
      effectivity             7.3758144726E-01
 Eigenvector           2
   energy error estimate      6.0198892665E-01
   Linf error estimate        1.1114181550E-01
 Eigenvector           3
   energy error estimate      7.2589558900E-01
   Linf error estimate        1.7696540623E-01

Total Grid:
   number of vertices      =         313
   number of leaf elements =         592
   number of levels        =           6
   degrees of freedom      =         313
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       3.7459628522E-01
      reduced by              4.3731703274E-01
   energy error estimate      1.0116796447E-01
      reduced by              3.0332153053E-01
      effectivity             2.7007199074E-01
   Linf norm of error         3.0168635697E-02
      reduced by              2.2556183102E-01
   Linf error estimate        7.0249079451E-03
      reduced by              7.1209935775E-02
      effectivity             2.3285467781E-01
 Eigenvector           2
   energy error estimate      2.4385876599E-01
      reduced by              4.0508845794E-01
   Linf error estimate        1.7117115120E-02
      reduced by              1.5401147662E-01
 Eigenvector           3
   energy error estimate      2.2823068948E-01
      reduced by              3.1441255869E-01
   Linf error estimate        1.1978776601E-02
      reduced by              6.7689933621E-02

Eigenvalues and error estimates:
     9.8607300457E+00  7.3373471034E-02
     2.2534720804E+01  1.6599334777E-01
     2.4526354310E+01  1.4758206929E-01

Total Grid:
   number of vertices      =         631
   number of leaf elements =        1228
   number of levels        =           8
   degrees of freedom      =         631
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       2.0456884667E-01
      reduced by              2.7305242303E-01
   energy error estimate      5.7250962513E-02
      reduced by              2.8295005643E-01
      effectivity             2.7986158911E-01
   Linf norm of error         1.2082225120E-02
      reduced by              4.0048960919E-01
   Linf error estimate        2.5147111385E-03
      reduced by              3.5797068917E-01
      effectivity             2.0813311402E-01
 Eigenvector           2
   energy error estimate      9.6309379999E-02
      reduced by              1.9746958779E-01
   Linf error estimate        4.9988708353E-03
      reduced by              2.9203933024E-01
 Eigenvector           3
   energy error estimate      1.2033732445E-01
      reduced by              2.6363090067E-01
   Linf error estimate        3.6400412099E-03
      reduced by              3.0387420446E-01

Eigenvalues and error estimates:
     9.7208972241E+00  2.4074718165E-02
     1.6866351722E+01  4.2331959835E-02
     2.2111327709E+01  4.9504695191E-02

Total Grid:
   number of vertices      =        1323
   number of leaf elements =        2612
   number of levels        =          10
   degrees of freedom      =        1323
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       1.3282419860E-01
      reduced by              6.4928849507E-01
   energy error estimate      3.6614236316E-02
      reduced by              6.3953922709E-01
      effectivity             2.7565938062E-01
   Linf norm of error         5.0996531277E-03
      reduced by              4.2207896949E-01
   Linf error estimate        9.9909238562E-04
      reduced by              3.9729906562E-01
      effectivity             1.9591379268E-01
 Eigenvector           2
   energy error estimate      6.0878029967E-02
      reduced by              6.3210904242E-01
   Linf error estimate        1.3290840727E-03
      reduced by              2.6587685829E-01
 Eigenvector           3
   energy error estimate      7.3542706863E-02
      reduced by              6.1113795903E-01
   Linf error estimate        1.3843431288E-03
      reduced by              3.8030974074E-01

Eigenvalues and error estimates:
     9.6853251413E+00  1.0056495102E-02
     1.6791934012E+01  2.0987996769E-02
     2.1985440476E+01  1.9450559096E-02

Total Grid:
   number of vertices      =        1323
   number of leaf elements =        2612
   number of levels        =          10
   degrees of freedom      =        1323
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       1.3282419860E-01
   energy error estimate      3.6614236316E-02
      effectivity             2.7565938062E-01
   Linf norm of error         5.0996531277E-03
   Linf error estimate        9.9909238562E-04
      effectivity             1.9591379268E-01
 Eigenvector           2
   energy error estimate      6.0878029967E-02
   Linf error estimate        1.3290840727E-03
 Eigenvector           3
   energy error estimate      7.3542706863E-02
   Linf error estimate        1.3843431288E-03

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           3
termination condition:
  maximum vertices achieved
---------------------------------------------------------
