---------------------------------------------------------
           PHAML   Version 1.8.0

Output from the master process
  PDE id is     0
  Number of slave processors is     4

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                 1000
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    PHASES
  print_grid_who     MASTER
  print_linsys_when  NEVER
  print_error_when   PHASES
  print_error_who    MASTER
  print_error_what   ENERGY_LINF_ERR
  print_errest_what  ENERGY_LINF_ERREST
  print_time_when    NEVER
  print_eval_when    PHASES
  print_eval_who     MASTER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           250
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ_SMOOTH
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    false
  solver             MG_SOLVER
  mg_cycles                  10
  mg_tol             MG_NO_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_FUDOP
  eigensolver        ARPACK_SOLVER
  num_eval                    1
  lambda0            -infinity
  scale_evec         SCALE_LINF
  arpack_ncv                  5
  arpack_maxit                1
  arpack_tol          1.0000000000E-01
---------------------------------------------------------

Total Grid:
   number of vertices      =         145
   number of leaf elements =         256
   number of levels        =           1
   degrees of freedom      =         145
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       8.5658380409E-01
   energy error estimate      3.3354746408E-01
      effectivity             3.8939268112E-01
   Linf norm of error         1.3375783342E-01
   Linf error estimate        9.8652144015E-02
      effectivity             7.3754292734E-01

Total Grid:
   number of vertices      =         275
   number of leaf elements =         516
   number of levels        =           7
   degrees of freedom      =         275
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       3.7678663835E-01
      reduced by              4.3987130803E-01
   energy error estimate      9.4697878840E-02
      reduced by              2.8391125414E-01
      effectivity             2.5133024689E-01
   Linf norm of error         2.7321642603E-02
      reduced by              2.0426200025E-01
   Linf error estimate        4.2589367650E-03
      reduced by              4.3171253981E-02
      effectivity             1.5588143169E-01

Eigenvalues and error estimates:
     9.8630549324E+00  6.5466537705E-02

Total Grid:
   number of vertices      =         639
   number of leaf elements =        1244
   number of levels        =           9
   degrees of freedom      =         639
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       1.9965193919E-01
      reduced by              2.6494031220E-01
   energy error estimate      4.9246637253E-02
      reduced by              2.6001974836E-01
      effectivity             2.4666245393E-01
   Linf norm of error         7.3661668600E-03
      reduced by              2.6960922398E-01
   Linf error estimate        1.4651089852E-03
      reduced by              3.4400815649E-01
      effectivity             1.9889706723E-01

Eigenvalues and error estimates:
     9.7176761525E+00  1.9685529054E-02

Total Grid:
   number of vertices      =        1209
   number of leaf elements =        2384
   number of levels        =          10
   degrees of freedom      =        1209
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       1.3842335399E-01
      reduced by              6.9332336342E-01
   energy error estimate      3.3412934848E-02
      reduced by              6.7848155147E-01
      effectivity             2.4138220816E-01
   Linf norm of error         5.6077225241E-03
      reduced by              7.6128095260E-01
   Linf error estimate        7.6136277914E-04
      reduced by              5.1966289665E-01
      effectivity             1.3577040873E-01

Eigenvalues and error estimates:
     9.6875164402E+00  9.2130602646E-03

Total Grid:
   number of vertices      =        1209
   number of leaf elements =        2384
   number of levels        =          10
   degrees of freedom      =        1209
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       1.3842335399E-01
   energy error estimate      3.3412934848E-02
      effectivity             2.4138220816E-01
   Linf norm of error         5.6077225241E-03
   Linf error estimate        7.6136277914E-04
      effectivity             1.3577040873E-01

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           3
termination condition:
  maximum vertices achieved
---------------------------------------------------------
