---------------------------------------------------------
           PHAML   Version 1.8.0

Output from slave number     1
  PDE id is     0
  Number of slave processors is     1

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                 1000
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    PHASES
  print_grid_who     SLAVES
  print_linsys_when  NEVER
  print_error_when   PHASES
  print_error_who    SLAVES
  print_error_what   ENERGY_LINF_ERR
  print_errest_what  ENERGY_LINF_ERREST
  print_time_when    NEVER
  print_eval_when    PHASES
  print_eval_who     SLAVES
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           250
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ_SMOOTH
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    false
  solver             MG_SOLVER
  mg_cycles                  10
  mg_tol             MG_NO_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_FUDOP
  eigensolver        ARPACK_SOLVER
  num_eval                    1
  lambda0            -infinity
  scale_evec         SCALE_LINF
  arpack_ncv                 20
  arpack_maxit              100
  arpack_tol          1.0000000000E-10
---------------------------------------------------------

My Grid:
   number of vertices       =         145
   number of vertices I own =         145
   number of elements       =         256
   number of leaf elements  =         256
   leaf elements I own      =         256
   number of levels         =           1
   degrees of freedom       =         145
   degrees of freedom I own =         145
   min and max degree       =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       8.5657831087E-01
   energy error estimate      3.3353373990E-01
      effectivity             3.8937915620E-01
   Linf norm of error         1.3374885086E-01
   Linf error estimate        9.8650670987E-02
      effectivity             7.3758144726E-01

My Grid:
   number of vertices       =         275
   number of vertices I own =         275
   number of elements       =         776
   number of leaf elements  =         516
   leaf elements I own      =         516
   number of levels         =           7
   degrees of freedom       =         275
   degrees of freedom I own =         275
   min and max degree       =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       3.7678755958E-01
      reduced by              4.3987520441E-01
   energy error estimate      9.4698089886E-02
      reduced by              2.8392356921E-01
      effectivity             2.5133019251E-01
   Linf norm of error         2.7322464301E-02
      reduced by              2.0428186205E-01
   Linf error estimate        4.2589603745E-03
      reduced by              4.3172137928E-02
      effectivity             1.5587760780E-01

Eigenvalues and error estimates:
     9.8630549324E+00  6.5466620391E-02

My Grid:
   number of vertices       =         613
   number of vertices I own =         613
   number of elements       =        2128
   number of leaf elements  =        1192
   leaf elements I own      =        1192
   number of levels         =           8
   degrees of freedom       =         613
   degrees of freedom I own =         613
   min and max degree       =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       1.9143728201E-01
      reduced by              5.0807750186E-01
   energy error estimate      4.9073342332E-02
      reduced by              5.1820836504E-01
      effectivity             2.5634161652E-01
   Linf norm of error         6.7347327001E-03
      reduced by              2.4649067616E-01
   Linf error estimate        1.1409586575E-03
      reduced by              2.6789604909E-01
      effectivity             1.6941409680E-01

Eigenvalues and error estimates:
     9.7131319943E+00  2.0162729865E-02

My Grid:
   number of vertices       =        1201
   number of vertices I own =        1201
   number of elements       =        4480
   number of leaf elements  =        2368
   leaf elements I own      =        2368
   number of levels         =          10
   degrees of freedom       =        1201
   degrees of freedom I own =        1201
   min and max degree       =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       1.3235863528E-01
      reduced by              6.9139424616E-01
   energy error estimate      3.3081227576E-02
      reduced by              6.7411808537E-01
      effectivity             2.4993630001E-01
   Linf norm of error         5.1212613603E-03
      reduced by              7.6042533361E-01
   Linf error estimate        5.4967114669E-04
      reduced by              4.8176254508E-01
      effectivity             1.0733120378E-01

Eigenvalues and error estimates:
     9.6851126775E+00  8.8592830723E-03

My Grid:
   number of vertices       =        1201
   number of vertices I own =        1201
   number of elements       =        4480
   number of leaf elements  =        2368
   leaf elements I own      =        2368
   number of levels         =          10
   degrees of freedom       =        1201
   degrees of freedom I own =        1201
   min and max degree       =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       1.3235863528E-01
   energy error estimate      3.3081227576E-02
      effectivity             2.4993630001E-01
   Linf norm of error         5.1212613603E-03
   Linf error estimate        5.4967114669E-04
      effectivity             1.0733120378E-01

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           3
termination condition:
  maximum vertices achieved
---------------------------------------------------------
