---------------------------------------------------------
           PHAML   Version 1.8.0

Output from slave number     1
  PDE id is     0
  Number of slave processors is     1

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                 1000
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    PHASES
  print_grid_who     SLAVES
  print_linsys_when  NEVER
  print_error_when   PHASES
  print_error_who    SLAVES
  print_error_what   ENERGY_LINF_ERR
  print_errest_what  ENERGY_LINF_ERREST
  print_time_when    NEVER
  print_eval_when    PHASES
  print_eval_who     SLAVES
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           250
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ_SMOOTH
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    false
  solver             MG_SOLVER
  mg_cycles                  10
  mg_tol             MG_NO_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_FUDOP
  eigensolver        ARPACK_SOLVER
  num_eval                    1
  lambda0            -infinity
  scale_evec         SCALE_L2
  arpack_ncv                 20
  arpack_maxit              100
  arpack_tol          1.0000000000E-10
---------------------------------------------------------

My Grid:
   number of vertices       =         145
   number of vertices I own =         145
   number of elements       =         256
   number of leaf elements  =         256
   leaf elements I own      =         256
   number of levels         =           1
   degrees of freedom       =         145
   degrees of freedom I own =         145
   min and max degree       =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       9.2418223348E-01
   energy error estimate      2.8332650253E-01
      effectivity             3.0656995154E-01
   Linf norm of error         2.3597607583E-01
   Linf error estimate        8.3800666136E-02
      effectivity             3.5512356853E-01

My Grid:
   number of vertices       =         275
   number of vertices I own =         275
   number of elements       =         776
   number of leaf elements  =         516
   leaf elements I own      =         516
   number of levels         =           7
   degrees of freedom       =         275
   degrees of freedom I own =         275
   min and max degree       =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       2.1393817476E+00
      reduced by              2.3148916632E+00
   energy error estimate      1.5472754565E-02
      reduced by              5.4611038598E-02
      effectivity             7.2323485899E-03
   Linf norm of error         8.3693340562E-01
      reduced by              3.5466875304E+00
   Linf error estimate        6.9587304938E-04
      reduced by              8.3039083275E-03
      effectivity             8.3145569852E-04

Eigenvalues and error estimates:
     9.8630549324E+00  1.0696614375E-02

My Grid:
   number of vertices       =         613
   number of vertices I own =         613
   number of elements       =        2128
   number of leaf elements  =        1192
   leaf elements I own      =        1192
   number of levels         =           8
   degrees of freedom       =         613
   degrees of freedom I own =         613
   min and max degree       =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       2.3160781207E+00
      reduced by              1.0825922598E+00
   energy error estimate      4.5784622819E-03
      reduced by              2.9590479591E-01
      effectivity             1.9768168616E-03
   Linf norm of error         9.0671328238E-01
      reduced by              1.0833756620E+00
   Linf error estimate        1.0644956978E-04
      reduced by              1.5297268643E-01
      effectivity             1.1740157759E-04

Eigenvalues and error estimates:
     9.7131319943E+00  1.8811495977E-03

My Grid:
   number of vertices       =        1201
   number of vertices I own =        1201
   number of elements       =        4480
   number of leaf elements  =        2368
   leaf elements I own      =        2368
   number of levels         =          10
   degrees of freedom       =        1201
   degrees of freedom I own =        1201
   min and max degree       =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       2.3918512152E+00
      reduced by              1.0327161221E+00
   energy error estimate      2.1002671549E-03
      reduced by              4.5872763073E-01
      effectivity             8.7809272650E-04
   Linf norm of error         9.3651181323E-01
      reduced by              1.0328643370E+00
   Linf error estimate        3.4897624424E-05
      reduced by              3.2783246092E-01
      effectivity             3.7263410809E-05

Eigenvalues and error estimates:
     9.6851126775E+00  5.6245981835E-04

My Grid:
   number of vertices       =        1201
   number of vertices I own =        1201
   number of elements       =        4480
   number of leaf elements  =        2368
   leaf elements I own      =        2368
   number of levels         =          10
   degrees of freedom       =        1201
   degrees of freedom I own =        1201
   min and max degree       =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       2.3918512152E+00
   energy error estimate      2.1002671549E-03
      effectivity             8.7809272650E-04
   Linf norm of error         9.3651181323E-01
   Linf error estimate        3.4897624424E-05
      effectivity             3.7263410809E-05

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           3
termination condition:
  maximum vertices achieved
---------------------------------------------------------
