---------------------------------------------------------
           PHAML   Version 1.6.2

Output from slave number     1
  PDE id is     0
  Number of slave processors is     1

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                 1000
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    PHASES
  print_grid_who     SLAVES
  print_linsys_when  NEVER
  print_error_when   PHASES
  print_error_who    SLAVES
  print_error_what   ENERGY_LINF_ERR
  print_errest_what  ENERGY_LINF_ERREST
  print_time_when    NEVER
  print_eval_when    PHASES
  print_eval_who     SLAVES
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           250
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ_SMOOTH
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    false
  solver             MG_SOLVER
  mg_cycles                  10
  mg_tol             MG_NO_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_FUDOP
  eigensolver        ARPACK_SOLVER
  num_eval                    3
  lambda0            -infinity
  scale_evec         SCALE_LINF
  arpack_ncv                 20
  arpack_maxit              100
  arpack_tol          1.0000000000E-10
---------------------------------------------------------

My Grid:
   number of vertices       =         145
   number of vertices I own =         145
   number of elements       =         256
   number of leaf elements  =         256
   leaf elements I own      =         256
   number of levels         =           1
   degrees of freedom       =         145
   degrees of freedom I own =         145
   min and max degree       =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       8.5657831087E-01
   energy error estimate      3.3353373990E-01
      effectivity             3.8937915620E-01
   Linf norm of error         1.3374885086E-01
   Linf error estimate        9.8650670987E-02
      effectivity             7.3758144726E-01
 Eigenvector           2
   energy error estimate      6.0198892665E-01
   Linf error estimate        1.1114181550E-01
 Eigenvector           3
   energy error estimate      7.2589558900E-01
   Linf error estimate        1.7696540623E-01

My Grid:
   number of vertices       =         317
   number of vertices I own =         317
   number of elements       =         944
   number of leaf elements  =         600
   leaf elements I own      =         600
   number of levels         =           6
   degrees of freedom       =         317
   degrees of freedom I own =         317
   min and max degree       =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       3.7394493554E-01
      reduced by              4.3655662395E-01
   energy error estimate      1.0035714971E-01
      reduced by              3.0089054781E-01
      effectivity             2.6837413794E-01
   Linf norm of error         2.9972791817E-02
      reduced by              2.2409756513E-01
   Linf error estimate        7.0308648230E-03
      reduced by              7.1270319326E-02
      effectivity             2.3457490600E-01
 Eigenvector           2
   energy error estimate      1.6106762986E-01
      reduced by              2.6755912398E-01
   Linf error estimate        9.0429332994E-03
      reduced by              8.1363915630E-02
 Eigenvector           3
   energy error estimate      2.4244409516E-01
      reduced by              3.3399306847E-01
   Linf error estimate        1.7117593688E-02
      reduced by              9.6728473956E-02

Eigenvalues and error estimates:
     9.8600071855E+00  7.1653340411E-02
     1.7170757484E+01  1.0783104154E-01
     2.2534217024E+01  1.6253929499E-01

My Grid:
   number of vertices       =         599
   number of vertices I own =         599
   number of elements       =        2072
   number of leaf elements  =        1164
   leaf elements I own      =        1164
   number of levels         =           8
   degrees of freedom       =         599
   degrees of freedom I own =         599
   min and max degree       =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       2.1076258812E-01
      reduced by              5.6361931419E-01
   energy error estimate      5.7259114955E-02
      reduced by              5.7055341965E-01
      effectivity             2.7167589593E-01
   Linf norm of error         1.1878963776E-02
      reduced by              3.9632490188E-01
   Linf error estimate        2.2599228015E-03
      reduced by              3.2142885098E-01
      effectivity             1.9024578609E-01
 Eigenvector           2
   energy error estimate      1.1470565321E-01
      reduced by              7.1215832321E-01
   Linf error estimate        3.7040905315E-03
      reduced by              4.0961161703E-01
 Eigenvector           3
   energy error estimate      1.5699207056E-01
      reduced by              6.4753926244E-01
   Linf error estimate        7.1671588600E-03
      reduced by              4.1870130760E-01

Eigenvalues and error estimates:
     9.7246530595E+00  2.4676127320E-02
     2.2114830037E+01  5.2132388924E-02
     2.4101912311E+01  8.9954443995E-02

My Grid:
   number of vertices       =        1327
   number of vertices I own =        1327
   number of elements       =        4984
   number of leaf elements  =        2620
   leaf elements I own      =        2620
   number of levels         =           9
   degrees of freedom       =        1327
   degrees of freedom I own =        1327
   min and max degree       =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       1.3742607186E-01
      reduced by              6.5204205873E-01
   energy error estimate      3.7296634369E-02
      reduced by              6.5136588992E-01
      effectivity             2.7139416753E-01
   Linf norm of error         5.0216310622E-03
      reduced by              4.2273308994E-01
   Linf error estimate        1.2859240691E-03
      reduced by              5.6901238760E-01
      effectivity             2.5607697043E-01
 Eigenvector           2
   energy error estimate      7.6897293991E-02
      reduced by              6.7038800478E-01
   Linf error estimate        1.6846762651E-03
      reduced by              4.5481508910E-01
 Eigenvector           3
   energy error estimate      8.7685424076E-02
      reduced by              5.5853409515E-01
   Linf error estimate        1.8743432051E-03
      reduced by              2.6151830058E-01

Eigenvalues and error estimates:
     9.6871253124E+00  1.0127888277E-02
     2.1991169458E+01  2.0330042639E-02
     2.3922250274E+01  2.6282242359E-02

My Grid:
   number of vertices       =        1327
   number of vertices I own =        1327
   number of elements       =        4984
   number of leaf elements  =        2620
   leaf elements I own      =        2620
   number of levels         =           9
   degrees of freedom       =        1327
   degrees of freedom I own =        1327
   min and max degree       =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       1.3742607186E-01
   energy error estimate      3.7296634369E-02
      effectivity             2.7139416753E-01
   Linf norm of error         5.0216310622E-03
   Linf error estimate        1.2859240691E-03
      effectivity             2.5607697043E-01
 Eigenvector           2
   energy error estimate      7.6897293991E-02
   Linf error estimate        1.6846762651E-03
 Eigenvector           3
   energy error estimate      8.7685424076E-02
   Linf error estimate        1.8743432051E-03

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           3
termination condition:
  maximum vertices achieved
---------------------------------------------------------
