---------------------------------------------------------
           PHAML   Version 1.8.0

Output from the master process
  PDE id is     0
  Number of slave processors is     4

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                 1000
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    PHASES
  print_grid_who     MASTER
  print_linsys_when  NEVER
  print_error_when   PHASES
  print_error_who    MASTER
  print_error_what   ENERGY_LINF_ERR
  print_errest_what  ENERGY_LINF_ERREST
  print_time_when    NEVER
  print_eval_when    PHASES
  print_eval_who     MASTER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           250
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ_SMOOTH
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    false
  solver             MG_SOLVER
  mg_cycles                  10
  mg_tol             MG_NO_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_FUDOP
  eigensolver        ARPACK_SOLVER
  num_eval                    1
  lambda0            -infinity
  scale_evec         SCALE_M
  arpack_ncv                 20
  arpack_maxit              100
  arpack_tol          1.0000000000E-10
---------------------------------------------------------

Total Grid:
   number of vertices      =         145
   number of leaf elements =         256
   number of levels        =           1
   degrees of freedom      =         145
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       1.2216930218E+00
   energy error estimate      4.5104233769E-01
      effectivity             3.6919449456E-01
   Linf norm of error         3.5231397525E-01
   Linf error estimate        1.3340668104E-01
      effectivity             3.7865849900E-01

Total Grid:
   number of vertices      =         275
   number of leaf elements =         516
   number of levels        =           7
   degrees of freedom      =         275
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       7.1974218064E-01
      reduced by              5.8913505096E-01
   energy error estimate      1.1576860521E-01
      reduced by              2.5666904310E-01
      effectivity             1.6084732607E-01
   Linf norm of error         2.2250200985E-01
      reduced by              6.3154466038E-01
   Linf error estimate        5.2065876177E-03
      reduced by              3.9027937559E-02
      effectivity             2.3400182413E-02

Eigenvalues and error estimates:
     9.8630549324E+00  8.0033075006E-02

Total Grid:
   number of vertices      =         639
   number of leaf elements =        1244
   number of levels        =           9
   degrees of freedom      =         639
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       6.0511403286E-01
      reduced by              4.2036860500E-01
   energy error estimate      5.9987105917E-02
      reduced by              2.5908192384E-01
      effectivity             9.9133556089E-02
   Linf norm of error         2.1809537609E-01
      reduced by              9.8019508337E-01
   Linf error estimate        1.7846427942E-03
      reduced by              3.4276630400E-01
      effectivity             8.1828547959E-03

Eigenvalues and error estimates:
     9.7176761525E+00  2.3978864425E-02

Total Grid:
   number of vertices      =        1209
   number of leaf elements =        2384
   number of levels        =          10
   degrees of freedom      =        1209
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       5.7925321291E-01
      reduced by              9.5726289832E-01
   energy error estimate      4.0723935845E-02
      reduced by              6.7887815594E-01
      effectivity             7.0304203650E-02
   Linf norm of error         2.1880753496E-01
      reduced by              1.0032653552E+00
   Linf error estimate        9.2795451669E-04
      reduced by              5.1996652759E-01
      effectivity             4.2409623456E-03

Eigenvalues and error estimates:
     9.6875164402E+00  1.1228946182E-02

Total Grid:
   number of vertices      =        1209
   number of leaf elements =        2384
   number of levels        =          10
   degrees of freedom      =        1209
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       5.7925321291E-01
   energy error estimate      4.0723935845E-02
      effectivity             7.0304203650E-02
   Linf norm of error         2.1880753496E-01
   Linf error estimate        9.2795451669E-04
      effectivity             4.2409623456E-03

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           3
termination condition:
  maximum vertices achieved
---------------------------------------------------------
