---------------------------------------------------------
           PHAML   Version 1.6.2

Output from the master process
  PDE id is     0
  Number of slave processors is     4

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                 1000
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    NEVER
  print_linsys_when  NEVER
  print_error_when   FINAL
  print_error_who    MASTER
  print_error_what   NEVER
  print_errest_what  LINF_ERREST
  print_time_when    NEVER
  print_eval_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           250
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ_SMOOTH
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    false
  solver             MG_SOLVER
  mg_cycles                  10
  mg_tol             MG_NO_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_FUDOP
  eigensolver        ARPACK_SOLVER
  num_eval                    3
  lambda0            -infinity
  scale_evec         SCALE_LINF
  arpack_ncv                 20
  arpack_maxit              100
  arpack_tol          1.0000000000E-10
---------------------------------------------------------

Norms of error:
 Eigenvector           1
   Linf error estimate        1.0007067797E-03
      effectivity             1.0007067797E-03
 Eigenvector           2
   Linf error estimate        1.3304936576E-03
 Eigenvector           3
   Linf error estimate        1.5305781114E-03

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           3
termination condition:
  maximum vertices achieved
---------------------------------------------------------
eigenvalues  9.686192782556E+00 1.679367533765E+01 2.199014706274E+01
error estimates  4.483550914364E-03 9.464427479500E-03 9.315806154430E-03
max linear system residual  2.223450200358E-10
ave linear system residual  6.298664647246E-12
eigensystem residuals  3.586493868057E-11 8.297354548726E-11 2.910153432188E-11
arpack iterations           2
arpack number converged           3
arpack number of OP*x          37
arpack number of B*x         110
arpack number of reorthogonalizatons          36
arpack error flag           0
error estimate for evec 2  1.330493657595E-03
