---------------------------------------------------------
           PHAML   Version 1.8.0

Output from the master process
  PDE id is     0
  Number of slave processors is     4

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                 1000
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    PHASES
  print_grid_who     MASTER
  print_linsys_when  NEVER
  print_error_when   PHASES
  print_error_who    MASTER
  print_error_what   ENERGY_LINF_ERR
  print_errest_what  ENERGY_LINF_ERREST
  print_time_when    NEVER
  print_eval_when    PHASES
  print_eval_who     MASTER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           250
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ_SMOOTH
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    false
  solver             MG_SOLVER
  mg_cycles                  10
  mg_tol             MG_NO_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_FUDOP
  eigensolver        ARPACK_SOLVER
  num_eval                    1
  lambda0            -infinity
  scale_evec         SCALE_L2
  arpack_ncv                 20
  arpack_maxit              100
  arpack_tol          1.0000000000E-10
---------------------------------------------------------

Total Grid:
   number of vertices      =         145
   number of leaf elements =         256
   number of levels        =           1
   degrees of freedom      =         145
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       9.2418223348E-01
   energy error estimate      2.8332650253E-01
      effectivity             3.0656995154E-01
   Linf norm of error         2.3597607583E-01
   Linf error estimate        8.3800666136E-02
      effectivity             3.5512356853E-01

Total Grid:
   number of vertices      =         275
   number of leaf elements =         516
   number of levels        =           7
   degrees of freedom      =         275
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       2.1393817476E+00
      reduced by              2.3148916632E+00
   energy error estimate      1.5472754565E-02
      reduced by              5.4611038598E-02
      effectivity             7.2323485899E-03
   Linf norm of error         8.3693340562E-01
      reduced by              3.5466875304E+00
   Linf error estimate        6.9587304938E-04
      reduced by              8.3039083275E-03
      effectivity             8.3145569852E-04

Eigenvalues and error estimates:
     9.8630549324E+00  1.0696614375E-02

Total Grid:
   number of vertices      =         639
   number of leaf elements =        1244
   number of levels        =           9
   degrees of freedom      =         639
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       2.3208237475E+00
      reduced by              5.4240524162E-01
   energy error estimate      4.4973602807E-03
      reduced by              1.4533159760E-01
      effectivity             1.9378293098E-03
   Linf norm of error         9.0868455190E-01
      reduced by              1.0857310101E+00
   Linf error estimate        1.3379844711E-04
      reduced by              1.9227421902E-01
      effectivity             1.4724410889E-04

Eigenvalues and error estimates:
     9.7176761525E+00  1.7977462122E-03

Total Grid:
   number of vertices      =        1209
   number of leaf elements =        2384
   number of levels        =          10
   degrees of freedom      =        1209
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       2.3923142236E+00
      reduced by              1.0308039231E+00
   energy error estimate      2.1156127263E-03
      reduced by              4.7041210716E-01
      effectivity             8.8433731046E-04
   Linf norm of error         9.3668282109E-01
      reduced by              1.0308118688E+00
   Linf error estimate        4.8207334192E-05
      reduced by              3.6029815916E-01
      effectivity             5.1466017211E-05

Eigenvalues and error estimates:
     9.6875164402E+00  5.8334492854E-04

Total Grid:
   number of vertices      =        1209
   number of leaf elements =        2384
   number of levels        =          10
   degrees of freedom      =        1209
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       2.3923142236E+00
   energy error estimate      2.1156127263E-03
      effectivity             8.8433731046E-04
   Linf norm of error         9.3668282109E-01
   Linf error estimate        4.8207334192E-05
      effectivity             5.1466017211E-05

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           3
termination condition:
  maximum vertices achieved
---------------------------------------------------------
