---------------------------------------------------------
           PHAML   Version 1.8.0

Output from slave number     1
  PDE id is     0
  Number of slave processors is     1

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                 1000
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    PHASES
  print_grid_who     SLAVES
  print_linsys_when  NEVER
  print_error_when   PHASES
  print_error_who    SLAVES
  print_error_what   NEVER
  print_errest_what  ENERGY_LINF_ERREST
  print_time_when    NEVER
  print_eval_when    PHASES
  print_eval_who     SLAVES
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           250
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ_SMOOTH
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    true
  solver             LAPACK_INDEFINITE_SOLVER
  eigensolver        ARPACK_SOLVER
  num_eval                    3
  lambda0             5.0000000000E+01
  scale_evec         SCALE_LINF
  lambda0_side       EIGEN_RIGHT
  transformation     SHIFT_INVERT
  arpack_ncv                 20
  arpack_maxit              100
  arpack_tol          1.0000000000E-10
---------------------------------------------------------

My Grid:
   number of vertices       =         145
   number of vertices I own =         145
   number of elements       =         256
   number of leaf elements  =         256
   leaf elements I own      =         256
   number of levels         =           1
   degrees of freedom       =         145
   degrees of freedom I own =         145
   min and max degree       =           1          1

Norms of error:
 Eigenvector           1
   energy error estimate      1.5022014747E+00
      effectivity             1.5022014747E+00
   Linf error estimate        3.2371124795E-01
      effectivity             3.2371124795E-01
 Eigenvector           2
   energy error estimate      1.3182929653E+00
   Linf error estimate        2.0753070496E-01
 Eigenvector           3
   energy error estimate      1.5056819197E+00
   Linf error estimate        2.1094898472E-01

My Grid:
   number of vertices       =         295
   number of vertices I own =         295
   number of elements       =         856
   number of leaf elements  =         556
   leaf elements I own      =         556
   number of levels         =           5
   degrees of freedom       =         295
   degrees of freedom I own =         295
   min and max degree       =           1          1

Norms of error:
 Eigenvector           1
   energy error estimate      7.4578582216E-01
      reduced by              4.9646191589E-01
      effectivity             7.4578582216E-01
   Linf error estimate        5.3585141161E-02
      reduced by              1.6553376350E-01
      effectivity             5.3585141161E-02
 Eigenvector           2
   energy error estimate      7.4521253123E-01
      reduced by              5.6528598030E-01
   Linf error estimate        6.3441770983E-02
      reduced by              3.0569823870E-01
 Eigenvector           3
   energy error estimate      8.7589858047E-01
      reduced by              5.8172882931E-01
   Linf error estimate        7.0834893658E-02
      reduced by              3.3579158369E-01

Eigenvalues and error estimates:
     5.2039725028E+01  6.2778531120E-01
     5.3587386453E+01  5.9550308673E-01
     6.0819300018E+01  7.5819978964E-01

My Grid:
   number of vertices       =         589
   number of vertices I own =         589
   number of elements       =        2032
   number of leaf elements  =        1144
   leaf elements I own      =        1144
   number of levels         =           7
   degrees of freedom       =         589
   degrees of freedom I own =         589
   min and max degree       =           1          1

Norms of error:
 Eigenvector           1
   energy error estimate      3.6107697075E-01
      reduced by              4.8415638916E-01
      effectivity             3.6107697075E-01
   Linf error estimate        1.8389578427E-02
      reduced by              3.4318428633E-01
      effectivity             1.8389578427E-02
 Eigenvector           2
   energy error estimate      4.3066359996E-01
      reduced by              5.7790708276E-01
   Linf error estimate        1.7727782692E-02
      reduced by              2.7943391896E-01
 Eigenvector           3
   energy error estimate      4.4656281176E-01
      reduced by              5.0983392566E-01
   Linf error estimate        2.4270838539E-02
      reduced by              3.4263958460E-01

Eigenvalues and error estimates:
     4.4303344760E+01  1.7184886537E-01
     5.1653648930E+01  2.0968223494E-01
     5.3896509557E+01  2.3027206997E-01

My Grid:
   number of vertices       =        1313
   number of vertices I own =        1313
   number of elements       =        4928
   number of leaf elements  =        2592
   leaf elements I own      =        2592
   number of levels         =           8
   degrees of freedom       =        1313
   degrees of freedom I own =        1313
   min and max degree       =           1          1

Norms of error:
 Eigenvector           1
   energy error estimate      2.5121875148E-01
      reduced by              6.9574847423E-01
      effectivity             2.5121875148E-01
   Linf error estimate        5.0377482617E-03
      reduced by              2.7394582653E-01
      effectivity             5.0377482617E-03
 Eigenvector           2
   energy error estimate      2.4215437797E-01
      reduced by              5.6228197135E-01
   Linf error estimate        5.3191760019E-03
      reduced by              3.0004745063E-01
 Eigenvector           3
   energy error estimate      3.4049368288E-01
      reduced by              7.6247657420E-01
   Linf error estimate        1.8247752246E-02
      reduced by              7.5183855792E-01

Eigenvalues and error estimates:
     5.0807346380E+01  8.3931952460E-02
     5.2657026952E+01  7.5144990763E-02
     5.4198947739E+01  2.0875946765E-01

My Grid:
   number of vertices       =        1313
   number of vertices I own =        1313
   number of elements       =        4928
   number of leaf elements  =        2592
   leaf elements I own      =        2592
   number of levels         =           8
   degrees of freedom       =        1313
   degrees of freedom I own =        1313
   min and max degree       =           1          1

Norms of error:
 Eigenvector           1
   energy error estimate      2.5121875148E-01
      effectivity             2.5121875148E-01
   Linf error estimate        5.0377482617E-03
      effectivity             5.0377482617E-03
 Eigenvector           2
   energy error estimate      2.4215437797E-01
   Linf error estimate        5.3191760019E-03
 Eigenvector           3
   energy error estimate      3.4049368288E-01
   Linf error estimate        1.8247752246E-02

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           3
termination condition:
  maximum vertices achieved
---------------------------------------------------------
