---------------------------------------------------------
           PHAML   Version 1.8.0

Output from slave number     1
  PDE id is     0
  Number of slave processors is     1

Subroutine phaml_solve_pde parameters:
  max_elem                 2000
  max_vert           infinity
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    PHASES
  print_grid_who     SLAVES
  print_linsys_when  NEVER
  print_error_when   FINAL
  print_error_who    SLAVES
  print_error_what   LINF_ERR
  print_errest_what  NEVER
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ_SMOOTH
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    false
  solver             MG_SOLVER
  mg_cycles                  20
  mg_tol             MG_ERREST_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_FUDOP
---------------------------------------------------------

My Grid:
   number of vertices       =        1361
   number of vertices I own =        1361
   number of elements       =        2104
   number of leaf elements  =        2104
   leaf elements I own      =        2104
   number of levels         =           1
   degrees of freedom       =        1361
   degrees of freedom I own =        1361
   min and max degree       =           1          1

My Grid:
   number of vertices       =        1852
   number of vertices I own =        1852
   number of elements       =        4068
   number of leaf elements  =        3086
   leaf elements I own      =        3086
   number of levels         =           6
   degrees of freedom       =        1852
   degrees of freedom I own =        1852
   min and max degree       =           1          1

My Grid:
   number of vertices       =        1852
   number of vertices I own =        1852
   number of elements       =        4068
   number of leaf elements  =        3086
   leaf elements I own      =        3086
   number of levels         =           6
   degrees of freedom       =        1852
   degrees of freedom I own =        1852
   min and max degree       =           1          1

Norms of error:
   Linf norm of error         1.5527116163E-04

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           1
termination condition:
  maximum elements achieved
---------------------------------------------------------
