#! /bin/sh

set -e

PREFIX=../src
gfortran -fPIC -c -o iso_c_utilities.o iso_c_utilities.f90
gfortran -fPIC -I$PREFIX/modules -c -o simple.o simple.f90
gfortran -fPIC -I$PREFIX/modules -c -o pde.o pde.f90
#f2py --f90flags="-fPIC" -I$PREFIX/modules -c -m simple simple.f90 pde.o $PREFIX/lib/libphaml.a
